### ISSUE TITLE
New meta field for recorded video on online workshops

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#1003]
Add a new meta field to the online workshops (`meeting`) to add the WPTV URL of recorded online workshops. This just needs to be a text field with URL validation.

**Comment by outdoor2kode** [comment]
@hlashbrooke I'm wondering where is the best place to add the text field for WPTV URL?

#### Is it custom fields? 
<img width="1649" alt="image" src="https://user-images.githubusercontent.com/18050944/213251409-16ade622-bafa-491b-9ba6-844556c363d7.png">
<img width="1609" alt="image" src="https://user-images.githubusercontent.com/18050944/213252027-8fe65dc2-33f7-46c8-98e9-252e031e96e6.png">


#### Or adding a new one similar to the `language` on the right-hand side? Which would also show a new column on the `All meetings` page.
<img width="1913" alt="image" src="https://user-images.githubusercontent.com/18050944/213251842-5ad3d4e8-6e32-4fe4-8a94-9ce363408765.png">
<img width="1744" alt="image" src="https://user-images.githubusercontent.com/18050944/213252519-b81c2847-aa23-4af5-b3d3-4bb45bea4217.png">

And I'm also curious about where this metadata would be used?

Thanks.

**Comment by adamwoodnz** [comment]
> Or adding a new one similar to the language on the right-hand side? Which would also show a new column on the All meetings page.

@renintw I believe this was the intention

And from memory on the front end there would be a new link on past meetings in the modal:

![Screen Shot 2023-01-19 at 4 01 23 PM](https://user-images.githubusercontent.com/1017872/213345528-43839576-36c5-48fe-aefe-a042fc7a5153.jpg)

**Comment by outdoor2kode** [comment]
@adamwoodnz 
> And from memory on the front end there would be a new link on past meetings in the modal:

I'm not quite sure which page or format "past meetings" refers to, so I tried to search through the Slack history using keywords but couldn't find any relevant discussions. Do you remember if the link should go to a Make post that has a section for past meetings, or should all the past online workshops be gathered in one post (like an archive page)? If it's the latter, I'm curious if there were any discussions on the style for that archive page. 

Or, is it [this page](https://wordpress.tv/category/learn-wordpress-online-workshops/) that the `View recorded online workshops` button on this [page](https://learn.wordpress.org/online-workshops/) links to? If so, since we already have the button, do we still want to add an additional link in the modal? 

Thanks!

**Comment by adamwoodnz** [comment]
> I'm not quite sure which page or format "past meetings" refers to, so I tried to search through the Slack history using keywords but couldn't find any relevant discussions. Do you remember if the link should go to a Make post that has a section for past meetings, or should all the past online workshops be gathered in one post (like an archive page)? If it's the latter, I'm curious if there were any discussions on the style for that archive page.
> 
> Or, is it [this page](https://wordpress.tv/category/learn-wordpress-online-workshops/) that the `View recorded online workshops` button on this [page](https://learn.wordpress.org/online-workshops/) links to? If so, since we already have the button, do we still want to add an additional link in the modal?

@renintw Sorry for the delayed response and lack of detail. For meetings that have already occurred and been recorded, there would be a new link in the modal with text like 'View recording' and the URL would be to the wordpress.tv item as entered in the meta field, eg.

Modal for meeting which occurred in the past and has a filled WPTV URL meta field:
![Screen Shot 2023-03-21 at 12 04 29 PM](https://user-images.githubusercontent.com/1017872/226485110-3fb217b1-4c01-4a23-badc-94ab0dfbb22a.jpg)

URL: https://wordpress.tv/2023/03/14/designers-developers-cats-dogs-living-in-harmony/

NOTE: IMO we should also consider not showing the 'register' or 'add to calendar' links for these past events, maybe ask in [#meta-learn](https://wordpress.slack.com/archives/C01KC5VDQBC)

**Comment by outdoor2kode** [comment]
@adamwoodnz No worries 🙂 Thanks for the clarification. I've opened a new PR in meeting-calendar as I'm thinking that it's a more suitable place for adding the wptv url meta field. I could see that there are also recordings for other meetings, so I thought adding to meeting-calendar might benefit other sites that use the plugin. 

And for the not showing `register` or `add to calendar` suggestion, I've asked in #meta-learn. But I was thinking, if in the end, we decide to make these two links disappear after the events are over, it may need to add some time checks to verify if the event end, and it probably should only be done in the learn repo rather than the meeting calendar as not sure if other users also want to remove them. What do you think?

**Comment by adamwoodnz** [comment]
> not sure if other users also want to remove them

Yeah maybe there's some value in being able to get back to where registration was happening, or adding to calendar as a record of when the user attended, but it doesn't seem very useful, and could be confusing. Let's see what the Learn folks say...

I'll take a look at the PR tomorrow 🙏

**Comment by kaitohm** [comment]
Thanks for working on this!

> And for the not showing register or add to calendar suggestion

Could we change the text `Register for event` to `Event details and registration`? Then, we could keep the link there even after the event concludes, and hopefully there'd be little confusion.

`Add to Google Calendar` could disappear after the event concludes. Is that implementation difficult?

> For meetings that have already occurred and been recorded, there would be a new link in the modal with text like 'View recording' and the URL would be to the wordpress.tv item as entered in the meta field, eg.

Could this text/link be shown only if the new wptv field has been filled in for an event, rather than after an event has concluded? The reason is, some recordings take a few days before they're processed. And at other times, a recording is never posted. So I think the check should be whether the filed has a value, rather than if the event has concluded.

The text `View recording` works for me 👍

**Comment by outdoor2kode** [comment]
@bsanevans Thanks for the feedback!

> Could we change the text Register for event to Event details and registration?

No problem 👍 

> Add to Google Calendar could disappear after the event concludes. Is that implementation difficult?

It is doable, but currently, Neso has some higher-priority tasks to work on. Additionally, some time-related functions are deprecated and need to be replaced (the functions are expected to be used to check if an event is concluded). So, I've created an [issue](https://github.com/WordPress/Learn/issues/1447#issue-1646622892) for this and will wait until the higher-priority tasks and function replacements are completed before circling back to this one.

> Could this text/link be shown only if the new wptv field has been filled in for an event, rather than after an event has concluded? The reason is, some recordings take a few days before they're processed. And at other times, a recording is never posted. So I think the check should be whether the filed has a value, rather than if the event has concluded.

The link on the modal wouldn't appear if the wptv field wasn't filled in. The check is currently whether the field has a value 👍

**Comment by kaitohm** [comment]
That all sounds perfect. Thanks @renintw 🙌
