### ISSUE TITLE
Quizzes for workshops

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#108]
In order to have a reliable data point as a success metric for the workshops, we're going to need to implement an automatically-graded quiz for viewers to take when they have finished watching. This issue serves as a discussion to decide how we are going to implement this.

The features we need to have here include:

- A UI to create a quiz of 5-10 multiple choice questions as part of each workshop - ideally, this would be within the post edit screen for the workshop.
- Workshop viewers would be able to complete the quiz and see their grade automatically as soon as they have submitted their answers.
- In order to complete the quiz and have the grade stored, users would need to be logged in, so we would need to have an easy flow for people to create a .org profile before doing the quiz without losing their place on the site.
- Quiz grades would need to be stored in the database - Sensei achieves this by storing them as a comment (with a custom comment type) on the lesson post with the comment "author" being the learner who took the quiz.
- A dashboard UI where we could keep track of grades that people get - this would need to include average grades per workshop, as well as average grade across all the workshops.

In order to do this, we have two options:
1. Install Sensei on Learn (it's already [elsewhere on .org](https://wordpress.org/contributor-training/) so there's no technical issue with using it here).
2. Build our own quiz functionality, perhaps forking some of the code from Sensei if possible/necessary.

The two big issues with using Sensei for this would be:
1. Sensei is quite opinionated with regards to templates and CPTs, so adapting it to the Learn CPT structure and templates would be a lot of work and it probably wouldn't look or work as well as we would like.
2. Sensei has a lot of overhead of features that we would never use - including question types, UI elements that would really get in the way, and a lot of processing that would slow things down unnecessarily.

I'm not writing the code here, but my preference would be to build our own quiz functionality so that we don't end up with a whole bunch of features that we won't ever use, and we can make it work as smoothly as possible for our use case.

**Comment by hlashbrooke** [comment]
This could replace the need for using the speaker feedback tool as discussed in #10, or we could adapt the speaker feedback tool to work as a quiz of sorts. Or we could continue using both, but viewers would probably be unlikely to do a quiz _and_ submit speaker feedback.

**Comment by coreymckrill** [comment]
* I would probably prefer to use Sensei rather than rolling our own. I can't count the number of times that the phrase "we will never use that feature" has turned out to be untrue a few months after it has been uttered. Having lots of extra features gives us flexibility to experiment. From a momentum perspective, I think it would be faster to use the pre-built solution now, and then in 6 months to a year, when we've got this program ironed out, we can re-evaluate. If it turns out that Sensei's extra cruft is really getting in the way, we could then roll our own based on the actual usage data.
* I like the idea of combining workshop feedback and quiz into one thing, if possible. Otherwise, I don't see much incentive for people to take the quiz. Unless... maybe it's required in order to register for a discussion group?

**Comment by CdrMarks** [comment]
> Having lots of extra features gives us flexibility to experiment. From a momentum perspective, I think it would be faster to use the pre-built solution now, and then in 6 months to a year, when we've got this program ironed out, we can re-evaluate. 

I agree.

> If it turns out that Sensei's extra cruft is really getting in the way, we could then roll our own based on the actual usage data.

There are several [hooks available](https://docs.woocommerce.com/sensei-apidocs/hook-docs.html) if we needed to remove or filter particular functionality.

**Comment by StevenDufresne** [comment]
We haven't made any progress here. What are our next steps?

**Comment by hlashbrooke** [comment]
Chatted with @coreymckrill about this and it looks like Sensei will be the best option here, and might require some dev work to integrate it with the block editor. I'm going to check-in with the Sensei team to see what their plans are for Gutenberg integration and if there's anything we can do to work with them on this.

We also floated the idea of using quizzes for groups of workshops, rather than a quiz for each one. I really like the idea as it will put less onus on each presenter to come up with a series of questions for their workshops and will make it easier for people to take quizzes. We could use the existing series taxonomy as the grouping and have a quiz for each series, or make it more flexible and have custom grouping for each quiz. I think the custom grouping could be quite effective as it would mean we can make things more useful.

@CdrMarks (and everyone else) I'd be interested to hear your thoughts on the idea of quizzes applying to a group of workshops rather than for each workshop.

**Comment by coreymckrill** [comment]
I like the idea of separating quizzes from individual workshops. But I think it does mean that there would need to be a planned curriculum and workshops created specifically to cover certain parts of a topic, so that the score you get from a quiz is meaningful. Maybe there are already plans around this, I'm not sure.

**Comment by courtneyr-dev** [comment]
I request we specifically collaborate with training team on terms like "workshops" "courses" etc.  We have used these terms for quite a while, and need that type of taxonomy.  

I am interested also in integrating an LMS potentially for lesson plans. However, lesson plans are for instructors to give.  I'm thinking of a way that students/attendees could later take the related quiz when they are online themselves. Do we have additional functionality like code-checking? I would love a way to present to participants in a lesson  - go change your "week starts on" setting, or append some CSS to the Customizer.  I don't think there's a great way to achieve that yet.  Do we have any suggestions/ideas on that?

**Comment by hlashbrooke** [comment]
@courane01 What kind of language would you like to see used in terms of workshop, course, etc.? Currently we're using "workshop" to denote a specific video, and "series" to denote a series of workshops that flow together. We're not using "course" anywhere and don't currently have specific plans for that, so it would be helpful to know how you envision it all being used.

@coreymckrill Let's go ahead with setting up Sensei and we can use the sensei "lessons" to create the quizzes, wlthough on the frontend we won't use the term "lessons" since that wouldn't really fit with how we're using them.

**Comment by coreymckrill** [comment]
> We're not using "course" anywhere and don't currently have specific plans for that, so it would be helpful to know how you envision it all being used.

Sensei uses "course" for a group of lessons, so even if we're not using that functionality, the term will be used in the back end, which would be confusing if we also started using "course" to mean something else like a group of lesson plans.

**Comment by coreymckrill** [comment]
@hlashbrooke Ok, Sensei is activated on the site. You may want to go in an tweak some of the [settings](https://learn.wordpress.org/wp-admin/admin.php?page=sensei-settings).

**Comment by hlashbrooke** [comment]
Great! I've edited the setting to work for us, and will work on the best way to manage the content for it. In terms of development work, I think we can close this issue now. If there are further tweaks that need to be made for the layout or anything similar then I will log those as new issues that are specific to what is needed. Right now the main decisions that need to be made and implemented are not dev-related.

There will also be a follow-up issue regarding how we track grades and how we display that on the front end, especially on user profiles.

**Comment by courtneyr-dev** [comment]
If we can use "courses" on the published end, it would be ideal.  Our mockups had Workshops for several years, so Courses seems like a decent pivot.  Those that would be seeking curriculum for a grouping of Lesson Plans would understand "Courses" and later, some term for a grouping of courses.  

Pathways for lesson plans like "website builder", "front end developer", "back end developer" are stretch goals at this time, but have been on the radar since 2014 roughly.  Colleges would call them majors.  We need a less official term than that. 

Are we able to adjust the admin interface taxonomy to denote "Workshop courses"? Or "Training Courses"?   Clearing up confusing in the editor for a smaller group would be easier than accounting for published users?  Or maybe I'm misunderstanding where the conflict may be?
