### ISSUE TITLE
Handbook pages don't show the handbook sidebar

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#111]
We have activated the .org handbook plugin on Learn and created a few handbook pages - example: https://learn.wordpress.org/handbook/. We have also added the 'Handbook Pages' widget to the widget area for the handbook sidebar, but the widget does not show on the frontend. I'm guessing this is because the theme is overriding the handbook page template, so could this please get sorted out so we see the handbook pages widget correctly? You can remove the "Suggestions" widget from the handbook sidebar completely.

**Comment by coreymckrill** [comment]
@hlashbrooke The Learn theme doesn't support any of the handbook functionality at all. However, the `wporg-breathe` theme does, which is what is used on all the Make sites. Since Learn is its own subdirectory multisite network, what if, instead of trying to cram the handbook markup and style into the Learn theme, we added a new site, `learn.wordpress.org/handbook` and then used it for all the Learn documentation?

**Comment by CdrMarks** [comment]
I like this approach.

What would the URL be for the initial handbook page and the handbook child pages?  One of the handbooks I published is at the URL: https://learn.wordpress.org/handbook/handbook/create-a-workshop/

**Comment by coreymckrill** [comment]
> What would the URL be for the initial handbook page and the handbook child pages?

Ah good point. Having it be https://learn.wordpress.org/handbook/handbook/ wouldn't be that great. It looks like the Handbook plugin will recognize `welcome` as the slug of the top level page, so it could be https://learn.wordpress.org/handbook/welcome/.

Or, we could make the site slug `documentation` or `wiki` or something. Then it could be https://learn.wordpress.org/documentation/handbook/

**Comment by hlashbrooke** [comment]
This sounds like a good way forward to me!

I like the URL learn.wordpress.org/handbook, then we have /welcome as the starting page.

**Comment by coreymckrill** [comment]
The one drawback, which I forgot about, is that the web server for learn.wordpress.org is not currently configured to support subdirectory multisite. There's a systems request that we'll have to wait on before we can proceed here:

https://make.wordpress.org/systems/2020/08/08/add-nginx-config-to-support-subdirectory-sites-on-learn-wordpress-org/

**Comment by CdrMarks** [comment]
@coreymckrill was the new site created already?  When I browse to https://learn.wordpress.org/handbook/handbook/create-a-workshop/ I see a white page.  We haven't advertised these URLs yet, though I was about to share it with a new presenter.

**Comment by coreymckrill** [comment]
The new site is created, but there's no content in it yet, because we won't be able to access the Dashboard until that systems request is completed.

**Comment by CdrMarks** [comment]
FYI, this [systems request](https://make.wordpress.org/systems/2020/08/08/add-nginx-config-to-support-subdirectory-sites-on-learn-wordpress-org/) is done.

I created a Handbook post with the slug `welcome` on the initial revision.  On publish, the permalink became https://learn.wordpress.org/handbook/handbook.  Browsing to this URL shows me a 404 page.

**Comment by coreymckrill** [comment]
D'oh, apparently the Handbook plugin automatically changes the URL of the root page:
https://github.com/WordPress/wordpress.org/blob/master/wordpress.org/public_html/wp-content/plugins/handbook/inc/handbook.php#L259-L275

:/

So maybe we should rethink the site's subdirectory slug again. What about `meta` since it's a site about making the Learn site? Then we would have: `https://learn.wordpress.org/meta/handbook/`

**Comment by coffee2code** [comment]
As discovered, the frontend aspects of having handbooks are left pretty much to the theme. So having a subsite with the wporg-breathe theme (as has been done) gets you that stuff for free.

However, the plugin presumes that a handbook is _part of a site_ and not _the whole site_ itself, so it'll live relative to some slug ("handbook" by default). In the current scenario, that gets you the undesired `https://learn.wordpress.org/handbook/handbook/` path.

Support for a "welcome" page is more as a way of recognizing a page to be shown as the root of the handbook. The "welcome" slug of that page is not intended to be shown. (In short, a page called "welcome" will be shown at https://wlearn.wordpress.org/handbook/handbook/ path in the current configuration.

So, there are 2 things that can be done with minimal effort:

1. As Corey suggests, rename the site's slug to something other than "handbook", so that the handbook can live at `/{$site_slug}/handbook/`. That makes it possible to have other non-handbook documentation located elsewhere on the site, though that may not be appropriate.
2. The handbook's slug can be changed, but it has to be something and it'll still be the parent of all handbook pages. `https://learn.wordpress.org/handbook/welcome` suggests the handbook slug is "welcome". All other handbook pages will be relative to that, which is likely not what you want (e.g. `https://learn.wordpress.org/welcome/create-a-course/how-to-do-this-thing`

The first option seems to be the easiest to do and results in the cleanest URL structure. But you may have to address what the non-handbook parts of the site are like.

**Comment by coffee2code** [comment]
Incidentally, I have [fixed a bug](https://meta.trac.wordpress.org/changeset/10274) preventing the 'welcome' landing page from appearing.

I also enabled the sidebar widget for listing the handbook pages.

**Comment by CdrMarks** [comment]
How important is the handbook sidebar?  Is that what provides the chapters seen on the left on this [handbook](https://make.wordpress.org/community/handbook/wordcamp-organizer/)?

It would really be ideal if the handbook could be part of the Learn site and not in a separate site.  What features are missing from the Learn theme that causes the handbook functionality to be unsupported?

**Comment by coreymckrill** [comment]
The WordPress.org Breathe theme has a lot of specialized markup and CSS to accommodate the way that handbooks work and how the content looks. Extracting it all from Breathe and integrating it into the Learn theme that we have on the main site would be a big task, and I don't think it's something we'd want to spend time on, especially since as Scott mentions, we get it for free by using the Breathe theme.

I've changed the site slug to `meta`, so now main Handbook page is now accessible at https://learn.wordpress.org/meta/handbook/

It appears that the expected Handbook layout, including the sidebar, is now showing up, so I'm going to go ahead and close this. If there are other things we need to address on this separate site, let's open new issues and include the `[Component] Meta` label on them.
