### ISSUE TITLE
Learn WordPress Content Error Report - Get Found Using the Media Library Quiz

### ISSUE THREAD

**Issue by porg** [WordPress/Learn#1138]
# Error Description
- Content URL: [Get Found Using the Media Library Quiz](https://learn.wordpress.org/quiz/get-found-using-the-media-library/)

> What happens if you delete an image from the MEDIA LIBRARY?
> 1. The image will still exist in the media library.
> 2. The image will also be deleted from the media library.
> 3. The image will still appear on a post or a page for a few days, but eventually will leave a broken image.

- I answered 2, which is factually correct. But the quiz defined 3 as the correct answer.
- This is wrong. This is not a "general truth" but only a "specific" (given if…) truth.
- For users which have this image cached it's true ("a specific truth") but not a general truth (answer 2 meets that general truth criterion).
- Please revise the question or the possible answers. It's misleading non tech savvy users.

# Error Report Checklist:
- [ ] Error Validated
- [ ] Error fix proposed
- [ ] Error fix reviewed
- [ ] Error fix published

**Comment by jomarieminney** [comment]
I can see the reasoning behind this - the same responses have been used for both questions (what happens when I delete an image from a post/page, vs when I delete from the media library). However, technically "The image will also be deleted from the media library" will always be correct if the question is "What happens if you delete an image from the MEDIA LIBRARY?" so I agree it will be confusing for users. Perhaps three better options might be:
1. The image will still be available in the media library but references to the image will be removed from the page/post
2. The image will no longer be available in the media library and will result in broken links on your website
3. The image will no longer be available in the media library and references to the image will be removed from the page/post

**Comment by porg** [comment]
Good 3 choices.

Small correction for 2) "will result in broken image references on your website". Not  "broken links", because an image can be linked to e.g. it's media page, its source image (possible intercepted by a LightBox), or not linked at all. So "broken link" is wrong, if we want to be very correct.

**Comment by jomarieminney** [comment]
Agree, good suggestion :)

Jo Minney
0413 287 708

On 11 May 2023, at 22:28, porg ***@***.***> wrote:

﻿

Good 3 choices.

Small correction for 2) "will result in broken image references on your website". Not "broken links", because an image can be linked to e.g. it's media page, its source image (possible intercepted by a LightBox), or not linked at all. So "broken link" is wrong, if we want to be very correct.

**Comment by jomarieminney** [comment]
Agreed good suggestion :)

**Comment by kaitohm** [comment]
Thank you! I've updated the question with the suggestions made here. I've also updated the options under "What happens if you delete an image from a POST or a PAGE?" to mimic the changes made to this one.
