### ISSUE TITLE
Theme: Lesson Plans archive shows some posts twice

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/Learn#116]
On the [Lesson Plan archive](https://learn.wordpress.org/lesson-plans/), some of the lesson plans appear twice in the results, not necessarily adjacent to each other. For example, the "Child Themes Twenty Sixteen" lesson plan appears on the first page of the archive, and again on the second page of the archive. I've checked the URLs and they are not separate posts.

**Comment by StevenDufresne** [comment]
Is this still happening? I can't reproduce the example you added.

**Comment by coreymckrill** [comment]
I can't reproduce it now either. Guess I will close this as "works for me"

**Comment by iandunn** [comment]
I can still see it, e.g., https://learn.wordpress.org/lesson-plans/theme/ `dashboard icons` and `static vs content`

**Comment by StevenDufresne** [comment]
Yep, I see it as well, with the last 2 lesson plans on the first page. Nice catch!

**Comment by coreymckrill** [comment]
Huh, I do not see doubles of either of those in the `theme` category. @iandunn are you looking at production or your sandbox?

**Comment by CdrMarks** [comment]
I confirm seeing the duplicates of the ones Ian saw on production.

The first occurrences are seen on https://learn.wordpress.org/lesson-plans/theme/

The duplicate occurrences are seen on https://learn.wordpress.org/lesson-plans/theme/page/2/

**Comment by iandunn** [comment]
Yeah, sorry, I assumed it only happened on pagination boundaries, but didn't mention that explicitly. I was looking at prod.

**Comment by jrastaban** [comment]
I think the issue is that items are being pulled in a random order. I did some testing using ?x=x and the listed items on the page are different each time. It is the same page but if you bust the cache and you get new results.

The outcome is that the second query grabs the last 3 items from a new random query not related to what was seen on page 1 and displays those. A quick solution would be to list them in a specific order though I suspect they are random so the same ones aren't always first.

**Comment by jrastaban** [comment]
I saw that the Workshops are ordered ascendingly so I went ahead and put together a patch that does so for the lesson plans.

**Comment by jrastaban** [comment]
Thanks @coreymckrill for catching that what I thought was a fix wouldn't have changed anything.

~~I did some more digging. The changing order only happens on the taxonomy archive page (https://learn.wordpress.org/lesson-plans/builder/) not on the post type page (https://learn.wordpress.org/lesson-plans/)~~

It looks like this happens on the post type page too but it was harder to replicate (more aggressively cached?)

I have had no luck in finding anything that would be causing this conflict in the base files. Maybe there is a pre_get_posts in a plugin that could be conflicting?

**Comment by jrastaban** [comment]
Looks like the issue is even more wide spread. Is there a way to escalate this issue? 

https://meta.trac.wordpress.org/ticket/5544

There is a taxonomy called `lesson-plans` and then the post type `lesson-plan` which has set its archive page to `lesson-plans`   Could that be causing a conflict? I'm not familiar enough with the rewrite rules system to know if that conflicts with has_archive but it seemed like a red flag to have 2 things competing for the same url.
