### ISSUE TITLE
Migrating your website Part 1: Changing to a different host and domain

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1187]

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/207766234-dc33a88e-be8f-4496-a614-74ea890a7567.mp4

**Comment by westnz** [comment]
Unsure if I should leave 3:47 - 4:00 in and if it sounds like I am 'marketing' the plugin. I just thought it would be good to know there is another option apart from redirecting links one by one.

**Comment by digitalchild** [comment]
It would be good if there was an intro as to why you might want to migrate your site.

**Comment by westnz** [comment]
Good idea @digitalchild

**Comment by abhansnuk** [comment]
Hi @westnz . A general question, are we suggesting plugins in tutorials or commenting on how good they are? I may have missed the update on this as it was a while back. Thanks.

**Comment by abhansnuk** [comment]
Do we want to be reminding users to take a backup of the site earlier in the video before they start the migration, and to save it on a device and not within the CMS?

**Comment by wparasae** [comment]
**Feedback**
I love your graphics. I _so_ want to figure out how to include moving graphics in my workshops! This may be your prettiest workshop yet, Wes!

Suggestion: Omit the section from 3:47-4:00. We probably want to stick to free versions rather than mentioning paid features to avoid appearing like we recommend one plugin over another--you have good instincts! It might be okay to change it to say something like, "Some plugins may offer additional and faster ways to set up redirects through their paid features, but it is also possible to change the redirects/etc using many free versions of plugins one by one."

Second suggestion: Retitle this to "Migrating your WordPress website to a different host and domain"

There are a LOT of (complicated!) ways to migrate your WordPress website:
-Move from one host to a different host, but with no domain change
-Keep your same host, but change your domain name (not actually a migration, but beginners would get confused)
-Migrating from your local installation to a live host? (I *believe* there are some image considerations here, but I could be wrong about this)

Getting more specific would help clarify this.

**Comment by westnz** [comment]
Thank you, @abhansnuk and @wparasae for your helpful feedback.

**Comment by westnz** [comment]
Updates made.

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/migrating-your-wordpress-website-to-a-different-host-and-domain/

**Comment by courtneyr-dev** [comment]
@westnz can you open new issues using the Tutorials issue template to preserve the consistent info at the start of issues?

**Comment by westnz** [comment]
Yes @courtneyr-dev. I have started doing it :-) I always just clicked on the plus (Add item) at the bottom of GitHub to create a new Issue.

**Comment by westnz** [comment]
Updating for the Intermediate learning pathway.

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/8529e13e-a5f1-4ed2-8cbb-23927fb94025

**Comment by westnz** [comment]
Hey @SierraTR 
I have made small tweaks/updates for the Intermediate learning pathway. Could you please review and let me know if you are happy for this to be published alongside your video?

**Comment by SierraTR** [comment]
Wes, it looks like it covers all the steps needed and adds in the SEO redirect that should certainly be considered.
Well done.

**Comment by westnz** [comment]
Thank you very much @SierraTR

**Comment by westnz** [comment]
//published
