### ISSUE TITLE
Tutorial - Adding and customizing a category template

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1278]
# Topic Description
Creating a category template

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/215929183-812e4212-7b51-49c5-91a7-2dbadbc0d0c3.mp4

**Comment by digitalchild** [comment]
I think there needs to be something in here that outlines that this is related to the Site Editor and not a classic theme. Otherwise, rest is great.

**Comment by wparasae** [comment]
Looks great, Wes. I second the idea that we should talk about block themes -- you could consider changing the title to "Exploring Category Templates With Block Themes" as a quick fix!

**Comment by westnz** [comment]
Thank you @digitalchild and @wparasae 👍

**Comment by askdesign** [comment]
Great information! I want to implement this on my own site LOL! I agree with the other reviewers about making sure users know this is a Block Theme feature.

**Comment by westnz** [comment]
Thank you @askdesign I am glad it was helpful to you!

**Comment by westnz** [comment]
I still need to update for 6.2 release.

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/224837286-37afc43a-8439-464e-bd12-c9fc405674ee.mp4

**Comment by courtneyr-dev** [comment]
It looks like this was recorded without using 6.2 (I saw the beta label).  For videos moving forward, let's use https://app.instawp.io/launch?t=betarc to be sure that we're running the most current version of the release. The only catch is to hold on publishing the final until release day. For that, we use the Revisions Extended plugin to schedule the draft override. 

New patterns were added for the query loop block as well.

**Comment by westnz** [comment]
Thank you for the feedback Courtney. I will take a look at where you can see the beta label and Query Loop block.  I rerecorded sections after RC1 was released to reflect the new site editor. I have my own Local website with the correct version.

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/exploring-category-templates-with-block-themes/

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/aa245ed5-bf52-40b8-b3c2-1a04e27988a5

**Comment by quitevisible** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

### Feedback: 

@westnz Good pace and clearly explained. I imagine this will inspire learners towards deeper customization questions for this type of lesson. 

I'm wondering if using Playground for these tutorials might be beneficial so that viewers can easily follow along in the same WP environment? 

Great job and looks good to go!

**Comment by westnz** [comment]
Thank you very much for the review @quitevisible

**Comment by westnz** [comment]
Published as part of the Intermediate user learning pathway in Sensei.
