### ISSUE TITLE
Course - Converting a Shortcode to a Block

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1284]
## Needs Assessment Statement

A course to teach plugin developers how to convert their existing PHP shortcodes into blocks.

## Target Audience

Ben is a plugin developer who uses shortcodes to create custom functionality for his clients who use WordPress. He would like to convert the shortcode into a block so that users can add a block in the block editor instead of needing to use the shortcode block. However, he has never worked with Node.js/npm, so doesn't know where to start. 

## Course Objective

Intermediate and advanced plugin developers will learn how to set up the required development tools in order to build blocks, as well as the basics of creating their first block from an existing shortcode.

## Additional note

This course will be based on four existing tutorials (listed below)

## Outline <a href="#outline" id="outline">#</a>

- [ ] https://learn.wordpress.org/tutorial/using-the-create-block-tool/
- [ ] https://learn.wordpress.org/tutorial/converting-a-shortcode-into-a-block/
- [ ] https://learn.wordpress.org/tutorial/styling-your-wordpress-block/
- [ ] https://learn.wordpress.org/tutorial/using-block-attributes-to-enable-user-editing/

**Comment by jonathanbossenger** [comment]
This course is now ready to be reviewed.

https://learn.wordpress.org/course/converting-a-shortcode-to-a-block/

**Comment by nomad-skateboarding-dev** [comment]
Awesome job, Jonathan! I'm working my way through the course now and just completed module 1. The fact that I got a 100 on the first quiz without knowing most of the terminology before starting shows I picked up what you're teaching.

*I'll be finishing up the course within a day or two and add feedback on remaining 3  modules. At least from a comprehension and proofreading aspect. :)

**Course completed

## Specific Feedback

### Module 1 - Using the create-block tool
- The jump links to operating systems in the [Installation info section](https://learn.wordpress.org/lesson/using-the-create-block-tool/#mac-linux) scroll slightly past the beginning of the MacOS and Windows sections.
- Typo under the Windows section. Current sentence is "First, open Powershell with administrator permissions. by right-clicking on the Powershell menu item and selecting Run as administrator."

### Module 2 - Converting a Shortcode into a Block
- When I took the quiz it failed me on all three questions, even though they are correct I believe?
![1677522306661_module-2-quiz-screenshot.png](https://user-images.githubusercontent.com/78917704/221650925-6c309dc8-8e80-4b90-baf2-ea32e3b51ddf.png)

### Module 4 - Using Block Attributes to Enable User Editing
- Typo on quiz question: "What is the format to used to access a specific attributes value?"

#### Overall thoughts
Really well done, Jonathan! Again for someone who this is pretty much all new to, I learned a lot, was able to follow along, and retained the info for the quizzes. On two of the quizzes I went back to the text to double-check, but my initial answers were correct. So that felt pretty awesome! 😀

**Comment by westnz** [comment]
Review

**Intro**
- Solid intro and learning outcomes clearly stated 

**Using the create block tool**
-  It is excellent how you cater for all three major operating systems
- If you have used call-outs effectively
- You cater for the visual and text-based learner
- Unsure if there should be a full stop after permissions?
<img width="829" alt="image" src="https://user-images.githubusercontent.com/89751452/222163976-df2d4d68-99e8-4b00-b8a8-bb897e0d5910.png">

- Add a full stop at the end in stead of a comma
<img width="829" alt="image" src="https://user-images.githubusercontent.com/89751452/222164358-79420252-d270-4e8f-ba38-253ea3ed6f3a.png">

- I couldn't reset the quiz after taking it?  It would be good if learners could reset the quiz even if they only made one mistake.

**Converting a shortcode into a block**
- Clear step-by-step instructions
- It is cool how folks can just copy the code as they follow along throughout the course
- I couldn't reset this quiz

**Styling your WordPress blocks**
- I suggest adding the sentence in purple to the top part. Something feels missing when your only read "For example, let’s say you want to add a border to the block in the editor" : 
<img width="829" alt="image" src="https://user-images.githubusercontent.com/89751452/222171207-3b63ebd4-5470-4e02-9c96-b99213082b09.png">

- I couldn't reset this quiz either

**Using Block Attributes to Enable User Editing**
- Quiz. I could reset this quiz, but I couldn't see the correct answer when I made a mistake:
<img width="829" alt="image" src="https://user-images.githubusercontent.com/89751452/222172486-b310f694-9ba4-4eb6-af05-c0904a484baf.png">

- Should there be a next button at the bottom of the lesson?
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/89751452/222175896-81817fef-d9b9-401d-b915-30be9d9b6472.png">

I think it might be because I got one question wrong. Did you want folks to get a 100% to pass the lesson?
<img width="409" alt="image" src="https://user-images.githubusercontent.com/89751452/222176440-f893db7c-26c6-429a-bd70-f732aea267a0.png">

Great work, Jonathan! I appreciate the systematic way you teach learners and also how you always clarify anything that can confuse them.

**Comment by jonathanbossenger** [comment]
@nomad-skateboarding-dev thank you for your review and feedback. 

> The jump links to operating systems in the [Installation info section](https://learn.wordpress.org/lesson/using-the-create-block-tool/#mac-linux) scroll slightly past the beginning of the MacOS and Windows sections.

Unfortunately, this is something outside of my control, but I will see if I can raise this as a Learn WordPress bug, and get it fixed. 

> When I took the quiz it failed me on all three questions, even though they are correct I believe?
I had some issues with the quizzes when I created this course, so I will test them one more time today before I make this public.

**Comment by jonathanbossenger** [comment]
@westnz thanks for your feedback

> Did you want folks to get a 100% to pass the lesson?

Yes, my feeling is there are only three questions per quiz, so 100% should be possible.

The rest of the items are fixed.

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/course/converting-a-shortcode-to-a-block/

**Comment by westnz** [comment]
Awesome to see this published 🎆 

100% sounds good 👍

**Comment by cliffordp** [comment]
RE: https://learn.wordpress.org/course/converting-a-shortcode-to-a-block/

> You’ve read the **block developer handbook**

Should link it to https://developer.wordpress.org/block-editor/

**Comment by cliffordp** [comment]
> use the create-block tool

Suggested to be `<code>`:

> use the `create-block` tool

here and elsewhere on the page and throughout the course

**Comment by cliffordp** [comment]
RE: https://learn.wordpress.org/lesson/using-the-create-block-tool/

Consider npm 18 instead of 14, since https://developer.wordpress.org/block-editor/getting-started/devenv/ will soon be updated to 18

**Comment by cliffordp** [comment]
RE: https://learn.wordpress.org/lesson/using-the-create-block-tool/

Consider npm 18 instead of 14, since https://developer.wordpress.org/block-editor/getting-started/devenv/ will soon be updated to 18

**Comment by cliffordp** [comment]
Mention to allow / say `y` to any such prompts:

<img width="421" alt="image" src="https://github.com/WordPress/Learn/assets/1812179/e7d96967-1e76-4409-bf9a-0478e44e17f4">

**Comment by cliffordp** [comment]
Mention the `npx @wordpress/create-block` command is passing the `slug` parameter in this example. Point out that NOT passing the plugin folder slug will instead use _interactive mode_, which I'd guess would be most usable in real world scenarios.

Some may consider it applicable only for advanced users, but if I'm already a plugin dev (know how to write a shortcode as in this course) and am moving to blocks, then I'd like to know this option exists.

**Comment by cliffordp** [comment]
> visiting the [Block Editor handbook](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/) page

change anchor text to be more specific:

> visiting the [Block Editor handbook > Reference Guides > Package Reference > @wordpress/create-block](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/) page

This is helpful to indicate it's not the top-level handbook link, plus this deep link does not auto-expand the left nav to indicate where in the nav tree I landed at

**Comment by cliffordp** [comment]
> Nodejs

should be

> Node.js

**Comment by cliffordp** [comment]
suggested to mention `nvm current` to confirm the version of Node being used, possibly helpful for people who close Terminal and return later to complete the steps, or reload Terminal, or already have Node installed but aren't sure which version is active

**Comment by cliffordp** [comment]
RE: https://learn.wordpress.org/quiz/using-the-create-block-tool/

> True or false, it is possible to specify that the create-block command creates the plugin directory?

Maybe should be:

> Is it possible to specify that the `create-block` command creates the plugin directory?
> Yes/No

**Comment by cliffordp** [comment]
RE: https://learn.wordpress.org/lesson/converting-a-shortcode-into-a-block/

The change to the `wp-learn-subscribe` slug instead of `wp-learn-todo` was jarring. I heard in the video that you're doing this on an existing shortcode plugin, but why?

I'd recommend just using the scaffold from Lesson 1 and just add the `add_shortcode()` to the main plugin file, as opposed to making me scaffold a new plugin to even begin following along Lesson 2. It would also remove the 'copy from scaffold' steps around `8:30` since those JS files would already exist.

**Comment by cliffordp** [comment]
`3:40` the `git repository` prompt gets skipped on my terminal but the video mentions the defaults might be affected by whether or not VCS is in use. However, why would your test be using git if you didn't tell me when in the process I should have implemented git?

**Comment by cliffordp** [comment]
`5:38` your starting `scripts` looked like this:
<img width="836" alt="image" src="https://github.com/WordPress/Learn/assets/1812179/a418aff4-7f4c-4948-8593-bfd1d1e4dcde">

But my initial looked like this:

```json
  "scripts": {
    "build": "wp-scripts build",
    "format": "wp-scripts format",
    "lint:css": "wp-scripts lint-style",
    "lint:js": "wp-scripts lint-js",
    "packages-update": "wp-scripts packages-update",
    "plugin-zip": "wp-scripts plugin-zip",
    "start": "wp-scripts start"
  },
```

**Comment by cliffordp** [comment]
Best practice to have only underscores not hyphens in shortcode tags. From `add_shortcode( 'wp-subscribe'` to `add_shortcode( 'wp_subscribe'`

Also, the copy/paste code snippet should just `return` instead of use output buffering, due to not best practices and some servers may not support it. I wouldn't think it necessary to re-record the video, just update the code snippet.

Suggested code replacement below. Also suggest to use i18n to allow translatable and add docblock to the function.

```php
function wps_subscribe_shortcode() {
	return '
	<div class="wp-subscribe-subscribe">
		<h2>Subscribe!</h2>
		<p>Visit our <a href="/subscribe">subscribe page</a> and sign up to get notified</p>
	</div>
	';
}
```

The video also changed the JS files' boilerplate output code from using i18n functions to _not_ doing so, which is not recommended.

**Comment by cliffordp** [comment]
> Step 2: Set up the Block Registration in PHP

This code is already present from the build process, not needing to be part of copy/paste.

This also adds confusion to Step 1 because that copy/paste should NOT also remove the existing `register_block_type()`

**Comment by cliffordp** [comment]
Wrap with <code>:

> Note the use of the curly braces around …useBlockProps(). This is similar to the PHP opening and closing tags <?php and ?>, and indicates a JavaScript expression that needs to be processed.
…useBlockProps is a special React hook...

> Note the use of the curly braces around `…useBlockProps()`. This is similar to the PHP opening and closing tags `<?php` and `?>`, and indicates a JavaScript expression that needs to be processed.
`…useBlockProps` is a special React hook...

And elsewhere on the page such as `…useBlockProps.save()`

**Comment by cliffordp** [comment]
I think it's worthwhile to point out the subtle but critical difference going from Edit's `...useBlockProps()` (with `()`) to Save's `...useBlockProps.save()` (without `()`)

**Comment by cliffordp** [comment]
RE: https://learn.wordpress.org/quiz/converting-a-shortcode-into-a-block/

First 2 questions should end with `?`

**Comment by cliffordp** [comment]
> What is the npm command you need to run to start a new block project

I recommend changing the word `start` to either `initialize` or `setup`, since `npm start` would be the correct answer if the question meant to ask `...need to run to build the output for a new block after you make JS changes`

**Comment by cliffordp** [comment]
RE: https://learn.wordpress.org/lesson/styling-your-wordpress-blocks/

> In the Adding Block Support to an Existing Plugin lesson, you started with a PHP shortcode plugin.

Name of the lesson seems mislabeled and should be linked.

**Comment by cliffordp** [comment]
Output buffering is also on this page of the lesson so if you [update it there](https://github.com/WordPress/Learn/issues/1284#issuecomment-1582515408) you should update it here as well.
