### ISSUE TITLE
Arabic translation for Lesson Plan "Dashboard Overview"

### ISSUE THREAD

**Issue by NadaElSharkawy** [WordPress/Learn#1351]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/dashboard-overview/  
- Link to original content GitHub issue: https://github.com/WordPress/Learn/issues/423
- Language you'll be translating to: Arabic
- Have you arranged for someone to review this translation?:  **No**
- Reviewer's GitHub username: 
- Other info (link to the google doc with translation): https://docs.google.com/document/d/1oCrhgQL7Pqxb2ig7AwoVdrZj531jD0LBwArHaMVTiZ4/edit?usp=sharing   

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Aymenboch** [comment]
I reviewed the google dox document and put some comments.

**Comment by NadaElSharkawy** [comment]
Thanks @Aymenboch , comments reviewed and accepted.

cc; @bsanevans

**Comment by kaitohm** [comment]
Thanks for reviewing, @Aymenboch . I've added you as an assignee on this issue, so that we can track your contribution.

**Comment by kaitohm** [comment]
@NadaElSharkawy I've created a draft post on the Learn WordPress website. Could you transfer your translation to the post below? Because this is a copy of the English, you can delete the English text when you replace it with Arabic.
https://learn.wordpress.org/wp-admin/post.php?post=33160&action=edit

Once done, let me know. I'll make a final check on the settings and then publish this.

**Comment by kaitohm** [comment]
Hurray! This has now been published: https://learn.wordpress.org/lesson-plan/ar-dashboard-overview/

Thank you for your contribution, @NadaElSharkawy and @Aymenboch 🎉
