### ISSUE TITLE
iPhone 11 user cannot play workshop video

### ISSUE THREAD

**Issue by CdrMarks** [WordPress/Learn#136]
A Meetup.com user sent the following message to the organizers of the [Learn WordPress Discussions](https://www.meetup.com/learn-wordpress-discussions) meetup group.  
> I have tried many times to watch the video before tomorrow’s call, but it just doesn’t want to play on my iPhone 11 for some reason. I can’t keep trying to get it to play...sorry.

I checked the schedule of discussions groups and see this is she is trying to prepare of the [Discussion Group: WordPress Troubleshooting Basics: Part 1](https://www.meetup.com/learn-wordpress-discussions/events/273993927/) on Friday, Oct 23 by watching its [workshop video](url).

Can anyone test this on an iPhone 11?

Are there questions we can ask the user?

I have the user's email address and can relay messages if needed.

The .org account, Jill Binder, Timi Wahalahti (@sippis), and I are organizers on this meetup group.  I'm notifying them via Slack since I don't see them on this repository.

**Comment by CdrMarks** [comment]
Help Scout link: https://secure.helpscout.net/conversation/1317393827/101267

**Comment by coreymckrill** [comment]
I can't recreate this on my iPhone 6s, or on an emulated iPhone 11 (running via XCode). The video plays fine in Safari both times.

@CdrMarks you could ask them which app they were using to try and watch the video (maybe some other browser besides Safari?) You could also ask them what their internet source was while they were trying to watch. If they were using cellular data or otherwise had low bandwidth, maybe the video just wouldn't load properly.

**Comment by CdrMarks** [comment]
The user responded.
> I was using my Cox cable wifi at home and just clicked the link you sent the other day, so it was in Wordpress.com.
Suddenly it's working....I saw 9 minutes of it the other day....will see if it finishes today.

Closing this issue.
