### ISSUE TITLE
Topic Idea: Block theme capabilities in a child theme

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1556]
# Details

- Topic title: Block theme capabilities in a child theme
- Topic description: This was an idea originally surfaced in https://github.com/WordPress/Learn/issues/1113#issuecomment-1324839997
- Objective: 
- Content type: Lesson Plan
- WordPress version: 
- Will you be creating this content?: No

# Related Resources
These were [the suggested topics](https://github.com/WordPress/Learn/issues/1113#issuecomment-1324839997) to cover in this resource:
- Child theme basics (already covered by https://learn.wordpress.org/lesson-plan/create-a-basic-child-theme-for-block-themes/)
- Theme.json in child themes
- Templates and template parts in child themes
- Patterns in child themes
- Styles in child themes

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

**Comment by annezazu** [comment]
# Vetting Checklist for SMEs
- Priority: low.
- Feedback regarding the topic description: I'd recommend approaching it more as "When and how to build a child block theme". The current description and title doesn't feel like it reflects the meat of the subject, including when it makes since to use a child theme in a block theme world. 
- Feedback regarding the learning objectives: N/A
- Any other feedback: N/A

# Related Resources

I'd recommend heavily leaning on Create Block Theme plugin in this case and encouraging folks to use that to make the entire process easier. Per usual, Carolina has an excellent resource on the topic: https://fullsiteediting.com/lessons/child-themes/

**Comment by cynthianorman** [comment]
I'm working on this How to Create a Block Child Theme for a Block Theme
https://github.com/WordPress/Learn/issues/2000

**Comment by annezazu** [comment]
Awesome! Let's close this one out in that case and defer to yours: https://github.com/WordPress/Learn/issues/2000 Thanks for working on that.
