### ISSUE TITLE
Lesson - Using caching to improve website performance - W3 Cache Total plugin

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1579]
# Topic Description
Intro to caching and helpful tips.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/86ad8ae6-4e1f-4bf9-abff-9bbd6ddab664

**Comment by quitevisible** [comment]
Nice one as always @westnz . Just a couple of items I noticed...  

- In my mind, the stock video clips of the individuals used towards the beginning while explaining caching were interesting, but didn't directly relate to the narrative. I found myself momentarily tuning out from what was being said while subconsciously trying to connect it with the visual.  
- One suggestion might be to use clips of screen records off https://pagespeed.web.dev/ or even people getting frustrated on their phones (presumably due to slow site loads). I'm thinking something that might directly relate to the narration could work better.  
- More than half the tutorial involves the W3 Total Cache plugin. Consider adding the plugin name into the tutorial title? I know that starts to get pretty long 

Caching and performance often get overshadowed by design. Great tutorial to (re)introduce the topic!

**Comment by westnz** [comment]
I appreciate your helpful feedback! @quitevisible

**Comment by digitalchild** [comment]
A good overview of the different caching types. I agree with @quitevisible in regard to half the tutorial being about W3 Total Cache plugin. If not in the title, definitely in the description. For the stock videos, maybe have comparison of page speed with various caching enabled. 

You mention 4 kinds of caching Page, Browser, Server and CDN, but then in the plugin overview you have Database and Object caching. You should probably outline what these are also. 

I would also suggest that you only enable caching after you have finished building your site, to stop unnecessary issues during the build due to caching.

**Comment by westnz** [comment]
Thank you for the suggestions @digitalchild 💪

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/improving-website-performance-with-caching/

**Comment by westnz** [comment]
Note:
([W3 Total Cache](https://wordpress.org/plugins/w3-total-cache/) changed the UI a bit)

**Comment by westnz** [comment]
Updated and sharing for review again.

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/2e615325-f810-4c07-9b92-fede2e1b2bf0

**Comment by digitalchild** [comment]
A good overview, I have some feedback. 

- For page caching, it might be worth mentioned what it is. Creates a static version of a page so that it is no longer querying the database. 
- I think it would be good to mention the different levels of caching as per - https://developer.wordpress.org/advanced-administration/performance/cache/ or reference it. 
- For minify mode, I would mention that if you experience unexpected behavior or there are issues with your site rendering properly, it can be because of minification. 
- Is there an outro that goes over what was covered in the video? 

## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [ ] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by westnz** [comment]
Thank you for the good feedback @digitalchild

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/185595d2-6c2a-40ea-9ce7-bf616c810f43

**Comment by westnz** [comment]
Hey @digitalchild 
Thank you for helping with updating the script. Here is the updated video. Can you watch the video one more time and let me know if we are ready to publish it?

**Comment by digitalchild** [comment]
Great, this is ready to go from my feedback perspective.

**Comment by westnz** [comment]
Thank you, Jamie 🥇

**Comment by westnz** [comment]
//published
