### ISSUE TITLE
Learn WordPress Content Feedback - finding training content as a brand new user

### ISSUE THREAD

**Issue by emma794** [WordPress/Learn#1619]
# Feedback Details
- Content title: No specific item (I am searching for training tutorials to help me take my very first steps in WP)
- Content URL: https://learn.wordpress.org/tutorials/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: No

Write a description of your feedback here:
1. As a complete beginner (& native English speaker who knows no other languages), I am searching in Tutorials for an introduction to the basics of WP so I can start using it. These are the steps I have followed to find relevant content (in order):
a) In the 'Apply Filters' section, I filtered by 'WP Basics' first (as it seemed directed at new users). Three tutorials came up but none are in English.
b) I checked all the other series in the filter menu but none seem relevant to me as a beginner.
c) I then entered 'Getting Started' into the Search Tutorials box and this found the content I was looking for (e.g. an Introduction to WP Tutorial).

Overall feedback:
1) A new user has to search for the training tutorial content they need.
2) Adding a signpost to the Tutorials page directing new users straight to relevant content (without needing to search for it) would help initial engagement with the platform. 
3) I spent a good 30 minutes searching for useful training (and I'm still not sure I've found exactly what I need). Potentially, if I was trying to onboard onto WP to use it as a tool for my small business (for example), I might think about trying a different platform with easier to access training materials.
4) As a user who likes to read the instruction manual for anything before getting started on something new (!), it is not clear to me what pathway I should be following through the tutorials (or even if there is a pathway - there is lots of content, but is there a logical sequence I should be working through it in order to progress my learning?).

---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by jonathanbossenger** [comment]
Hello @emma794 

Thank you for your valuable feedback. 

As I mentioned to you when we met at WCEU, this is something the team is very keen to get right, and since then we've launched the Learning Pathways project, to solve exactly some of the problems you've described.

You can read more about the project, it's goals, and the timelines in the [project thread](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/) on our team site.

I'm going to close this feedback now, but I encourage you to visit learn.wordpress.org again around July, once the new redesign and learning pathways have launched.
