### ISSUE TITLE
Tutorial - How to add tables to your site

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1631]
# Topic Description
Creating a table using the Table block, using Google docs, Excel or a plugin.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- https://wordpress.org/documentation/article/table-block/

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/8b754891-0cdb-484f-936e-b3d101aaa9b4

**Comment by SierraTR** [comment]
Nice job Wes. 
## Tutorial Review Checklist
Please tick all items you've confirmed:
- [ X] Learning outcomes/objectives are clear.
- [X ] Technical concepts introduced in the content are accurate.
- [ X] The speed of demonstrations are easy to follow.
- [ X] The narration audio matches what is shown visually.
- [X ] Spelling and grammar are correct.
- [X ] Sound quality is consistent throughout the video.
- [X ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ X] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

The presentation covers almost everything at a tempo that is easy to follow. No technical or grammatical errors that I caught and the sound quality is consistent throughout the presentation. Nice quick coverage of a table plugin option.

One thing that kept me from using the native table block and pushed me toward a table plugin was the ability or inability to style the content in individual cells rather than the table as a whole. That is now possible (or maybe always has been and I didn't know how to do it), so you might consider adding a short segment on that capability.

**Comment by ghost** [comment]
## Tutorial Review Checklist
Please tick all items you've confirmed:
- [x ] Learning outcomes/objectives are clear.
- [x ] Technical concepts introduced in the content are accurate.
- [x ] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x ] Spelling and grammar are correct.
- [x ] Sound quality is consistent throughout the video.
- [x ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

Great job Wes! Haven't had a need for table but good to know this is available. I like that you added some plugin suggestions to help with creating table people want to see and not just a generic one.

**Comment by westnz** [comment]
Thank you for the feedback @lada7042 and @SierraTR. 

The checklist is great.

**Comment by digitalchild** [comment]
Great tutorial @westnz, as mentioned by @SierraTR the reason I use a plugin is for style purposes only. I can't find anything that needs changing.

**Comment by westnz** [comment]
Thank you! @digitalchild 😃

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/how-to-add-tables-to-your-site/
