### ISSUE TITLE
Learn WordPress Content Feedback - Error in "First Steps" quiz

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1654]
# Feedback Details
- Content title: First Steps Quiz
- Content URL: https://learn.wordpress.org/quiz/first-steps-2-3/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: error

**Write a description of your feedback here:**

First Steps quiz gives the wrong answer as correct. I selected "The team has made no progress in finding a venue after 3 months after approval for pre-planning " but that was marked as incorrect. I took the quiz a second time and marked "The team failed to update/interact with the community for more than two months during the planning period despite WordCamp Central's involvement, The team has made no progress in finding a venue after 3 months after approval for pre-planning" but it still came up as incorrect AND gave the Right Answer as marked below.

This is wrong >> Right Answer: The team failed to update/interact with the community for more than two months during the planning period despite WordCamp Central's involvement, The team has made no progress in finding a venue after 3 months after approval for pre-planning

Correct answer is found here >> https://make.wordpress.org/community/handbook/wordcamp-organizer/first-steps/

_This feedback was submitted in ticket 160392._

---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by kaitohm** [comment]
Asked for a review by the Community Team in Slack: https://wordpress.slack.com/archives/C037W5S7X/p1687841466111349

**Comment by nukaga** [comment]
Hello! I have confirmed this mistake.
You are correct. I would like to correct this, what should I do to do so?

**Comment by kaitohm** [comment]
I can make the change for you. This is how the first questions is currently set. Could you let me know what changes should be made?
<img width="914" alt="Screenshot 2023-07-08 at 9 22 20" src="https://github.com/WordPress/Learn/assets/49054298/d28d9f16-1517-481d-a5f2-7738bf787bea">

**Comment by SierraTR** [comment]
If you look closely at the quiz question you will notice that the possible answers are indicated by check boxes rather than radio buttons. That is the indication that there are multiple answers that must be selected - as shown in the graphic above. If both answers are selected, the quiz question is marked correct.

This situation is confusing for learners - having to notice the boxes rather than radio buttons. An indication such a [MA] should be given after the question mark of the quiz question to indicate multiple answers must be selected.

The condition described indicates that a single right answer was selected each time when two were needed to answer the question correctly.
