### ISSUE TITLE
Content Feedback - broken quiz link in "Saving Your Work: Create Block Theme"

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1701]
## Overview
- Content title: Saving Your Work: Create Block Theme
- Content URL: https://learn.wordpress.org/lesson/saving-your-work-create-block-theme/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: error

## Feedback Details

On the page under "Develop Your First Low-Code Block Theme > Get Design: Using the Site Editor to Build Your Custom Theme > Saving Your Work: Create Block Theme" the quiz link is broken.

https://learn.wordpress.org/?post_type=quiz&p=26850

Following the link goes to a 404 page of Page not Found.

_This feedback was provided in ticket 162114._

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by SierraTR** [comment]
Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No): No
 
I have already taken the course and do not see a link to the quiz within the course content for this lesson. The link to the quiz in the sidebar course menu operates correctly.

The problem is probably due to the user being logged out of WordPress.org when trying to access the quiz - in that case the quiz link returns a 404 as described.

- What should happen next to apply the feedback?: Issue closed with comment
