### ISSUE TITLE
Gujrati translation for Tutorial "How to start using WordPress Playground"

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Learn#1722]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/how-to-start-using-wordpress-playground/
- Link to original content GitHub issue: 
- Description: Subtitles in Gujarati Language 
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes or No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by harshgajipara** [comment]
I uploaded translated file to attached repository as unable to upload here. Please find attached. Thanks.

https://github.com/harshgajipara/Translation

**Comment by harshgajipara** [comment]
Video URL: https://wordpress.tv/2023/06/26/how-to-start-using-wordpress-playground/

**Comment by vanpariyar** [comment]
Hello @webtechpooja @harshgajipara 

I reviewed the translated caption, and it looks good to me.

Thanks.

**Comment by kaitohm** [comment]
Thank you for reviewing, @vanpariyar .

@harshgajipara In order to publish this translation, please complete these steps:
* Translate the English in the following post:
https://learn.wordpress.org/wp-admin/post.php?post=42098&action=edit
* [Upload the translated subtitle file to WordPress.tv](https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-subtitles/#4-upload-the-translated-subtitle-file-to-wordpress-tv)

Once done, let us know here. We'll be able to approve the subtitles and publish the post ✨

**Comment by harshgajipara** [comment]
Hi @bsanevans,
Thanks for the information. I completed translating the draft post and also uploaded the translated subtitle file to wordpress.tv. 
Thanks.

**Comment by kaitohm** [comment]
Wonderful! The subtitles have been approved, and the Tutorial has now been published: https://learn.wordpress.org/tutorial/gu-how-to-start-using-wordpress-playground/

Thank you for your contribution, @harshgajipara 🎉
