### ISSUE TITLE
Bug report - "Let us know" button in lessons for "Found a typo, grammar error or outdated screenshot?" not working.

### ISSUE THREAD

**Issue by subashcpoudel** [WordPress/Learn#1749]
## Description
The "Let us know" button for "Found a typo, grammar error or outdated screenshot?" in the left sidebar in lessons is not working. It is not linking to any page or URL.

## Step-by-step reproduction instructions

- Go to any course on learn.wordpress.org
- Select/click any lesson and you will see the text "Found a typo, grammar error or outdated screenshot?" in the left sidebar below which is the "Let us know" button as shown in the screenshot.
- It is currently not linking anywhere. 

## Expected behaviour
It should link to https://learn.wordpress.org/report-content-feedback/

## Actual behaviour
The button is not linked anywhere currently.

## Screenshots or screen recording (optional)
https://monosnap.com/file/bBftxgmUeF1jbhNxQByspQa9lMyUYj

## Environment information
Tested from Chrome, Firefox, Opera
- Browser(s) are you seeing the problem on.
- Device you are using and operating system (e.g. "Desktop with Windows 10", "iPhone with iOS 14", etc.).

**Comment by SierraTR** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No):  Yes
- What should happen next to apply the feedback?: 
- It appears that the button was placed in the course template so that it would appear within all courses at the bottom of the left column course outline. However, the button was not linked to the correct destination shown above in the Expected Behavior.
- Moved issue to Awaiting Fix

**Comment by jonathanbossenger** [comment]
This was my mistake, sorry folks. I was trying to replicate the "Let us know" button we have for tutorials and lesson plans, but it wasn't as quick a fix as I thought it would be, and I thought I had reverted the change. I've removed it for now.
