### ISSUE TITLE
Content Feedback - Update Course to 6.3 "A Developer's Guide to Block Themes - Part 1"

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#1794]
## Overview
- Content title: A Developers Guide to Block Themes – Part 1
- Content URL: https://learn.wordpress.org/course/a-developers-guide-to-block-themes-part-1/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: outdated content as this course needs to reflect 6.3 updates

## Feedback Details
I will be going through the entire course and making suggestions for updating text, screenshots and adding new 6.3 related content.
I have already been in touch with the course creator Jonathan Bossenger @jonathanbossenger in the #training channel to arrange collaboration on this course update work.

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by jonathanbossenger** [comment]
Hi @cynthianorman, thank you so much for your interest in updating this course. Course updates are a time-consuming task, and so as course creators, we greatly appreciate it when training team contributors are available to update course contents as WordPress is updated.

As I discussed with you in the #training-team Slack channel, I usually manage raw course content in markdown files in a GitHub repository. The Developer's guide to block themes course modules are all located here: https://github.com/jonathanbossenger/block-theme-course

To help keep things contained in one place, my suggestion would be that you work on that repository, creating pull requests for the relevant changes there, but we continue our communications here so that folks can see progress. That way I can review the changes in a pull request, and merge them into the GitHub repository, before applying the changes to the live course.

I've run through the first 4 modules, which make up the 1st course, and as far as I can see they are in sync with the live course, so you are welcome to start creating pull requests. 

Please let me know if you have any questions, if anything doesn't make sense, or if I can assist with anything. And again, thank you for your contribution!

**Comment by cynthianorman** [comment]
Hi @jonathanbossenger I've completed Module 1 and thought I should create a pull request for the first lesson as a trial. This will give us the opportunity to work out the workflow together and ensure I'm on the right track for the remainder of the course.

**Comment by jonathanbossenger** [comment]
Hi @cynthianorman that sounds like a great idea. I have sent you an invite to collaborate on the https://github.com/jonathanbossenger/block-theme-course repository. Once you accept, I should be able to elevate your permissions so that you can just clone that repo, and create the pull request directly, instead of having to fork it first.

I would also like to add that I really appreciate your help here, and I would reiterate that whatever pace you can manage these updates is perfect. I don't want you to feel pressure to complete them in any specific time frame. Open source contribution can be time consuming, and I don't want you to burn out early.

**Comment by cynthianorman** [comment]
@jonathanbossenger I appreciate the warning and completely agree!

I've created my pull request for Module 1 Lesson 1. The trickiest part is the screenshots. I uploaded the 2 new screenshots and noted within the PR description what replacements were needed. Obviously the links would need to be updated after the screenshots are added to Learn.WP.org but not sure when or how that would happen.

https://github.com/jonathanbossenger/block-theme-course/tree/1794-module-1-lesson-1-updates

**Comment by jonathanbossenger** [comment]
@cynthianorman thank you for this PR! 

I agree, the images are the trickiest. Uploading them and making a note in the PR is a perfectly acceptable solution.

I will review the PR this week, and let you know if I have any feedback.

**Comment by cynthianorman** [comment]
@jonathanbossenger thank you for your response. Shall I carry on with the workflow I've started for the remaining lessons? Or would it be best to wait for that feedback from you?

So I'm thinking of one pull request per lesson so we can stay as organized as possible. 

The format being
1794-module-#-lesson-#-updates

**Comment by jonathanbossenger** [comment]
Hey @cynthianorman 

So I noticed that what [you had created](https://github.com/jonathanbossenger/block-theme-course/tree/1794-module-1-lesson-1-updates) was a branch and that you still needed to create the pull request from the branch. 

No problems though, because GitHub makes it easy to create a new pull request from a branch, so I've done that here:

https://github.com/jonathanbossenger/block-theme-course/pull/4

> Shall I carry on with the workflow I've started for the remaining lessons?

Yes, please go ahead, I've taken a quick look at what you created in the branch, and it looks great! Thank you.

> The format being 1794-module-#-lesson-#-updates

This is an excellent idea, thank you. That way it makes it easier to review and merge each set of changes.

**Comment by cynthianorman** [comment]
@jonathanbossenger just a quick note to summarize the new work I just completed for Module 1 Lesson 2:

- I added new images to the project
- I created a new branch "module-01" in which I'm planning to generate all related Pull Requests
- I created a new PR for Module 1 Updates using the new branch

This module definitely had the most needed updates that I've seen so far.

**Comment by cynthianorman** [comment]
@jonathanbossenger just another quick update to summarize the new work I just completed for Module 1 Lesson 3:

- I added new images to the project and continued to append "-v2" to the file name
- I have a branch "module-01", a PR for module-01 branch and I've named the commits to the PR using the lesson number
- For both Lesson 2 and Lesson 3, I had to make changes to the md files that were found on the production site

**Comment by cynthianorman** [comment]
@jonathanbossenger Although I still don't want to rush my work on helping you update this course, I did want to point out that the course will get some views from this page:
https://make.wordpress.org/core/2023/08/24/introducing-twenty-twenty-four/

I would like to have all 4 modules reviewed by no later than Nov 2023

**Comment by jonathanbossenger** [comment]
Thanks @cynthianorman I have this work as my top priority to review this week.

**Comment by jonathanbossenger** [comment]
Hi @cynthianorman 

I've reviewed the work for modules 1 and 2. Great work here and thank you for your contributions.

I did note this in the first review, but it's perfectly okay to overwrite the images with the same path and filenames, the old images will still be kept in the commit history if we need them. 

I've not physically verified the actual instructions on a test site, we can do that once the new content is updated on Learn WordPress. 

I look forward to reviewing your next pull request.

**Comment by cynthianorman** [comment]
@jonathanbossenger I've just uploaded Module 4 content changes along with images and gifs. I have not reviewed the quizzes of all 4 modules yet so that will be done next. 

I want to draw your attention to a significant change recommendation within Module 4. Within the Creating Custom Templates and Template Parts lesson, you had instructions for creating an alternative post template which wouldn't include a featured image. I recommend this be removed, however, we could add new content here instead by pointing out the option to create a custom template for posts using the **Single item: Post** option.

That said, I'm in the middle of working through the workflows for creating custom templates for posts. I don't have a clear understanding of the **Single item: Post** option at this point.

I'm thinking the list of templates available to choose from for posts can be managed better by creating the custom post template on the "code" side of things rather than via the Site Editor. I'll provide a complete update on this topic once I've reviewed things more thoroughly. If you have any insights on this, please advise. Thanks!

**Comment by jonathanbossenger** [comment]
@cynthianorman thank you so much for all the work you've done so far.

I am planning on testing out the updates to this course once 6.4 is released today, which I will do tomorrow.

Once I have done this, I'll be able to suggest a way forward for module 4.

**Comment by cynthianorman** [comment]
Cycling back to Module 4 of this course update. @jonathanbossenger here you'll find the workflow I propose we use.
https://github.com/WordPress/Learn/issues/2192

**Comment by jonathanbossenger** [comment]
@cynthianorman I am closing this for now as the theme developer learning pathway is now public.
