### ISSUE TITLE
Content Feedback - Polyglots Contributor Training outdated links

### ISSUE THREAD

**Issue by nurianadal** [WordPress/Learn#1796]
Hello!
I have been following the Polyglots Contributor Training course.
In two lessons, I have seen that the embed to the link does not work correctly. In both cases, they are cases that refer to examples of style guides from the WordPress localization teams.

The units where it doesn't work correctly are

- https://learn.wordpress.org/lesson/intro-to-glossary-creation/
- https://learn.wordpress.org/lesson/understanding-wordpress-translation-style-guide/

## Overview
- Content title: examples of style guides from the WordPress localization teams
- Content URL: https://learn.wordpress.org/lesson/intro-to-glossary-creation/
- Content URL: https://learn.wordpress.org/lesson/understanding-wordpress-translation-style-guide/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: Link out of date, should point to the localization team's example style guides

## Feedback Details
On the above pages there is an outdated link, it should point to the localization teams' sample style guides. Thank you very much for your time. (Maybe with this link https://make.wordpress.org/polyglots/handbook/translating/glossaries-and-style-guides-per-locale/ ) Can it be updated with the current information?

Thank you very much for your time !

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by ironnysh** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? Yes and No: 
- What should happen next to apply the feedback?: 

1. The issue has been fixed in [Understanding WordPress Translation Style Guide](https://learn.wordpress.org/lesson/understanding-wordpress-translation-style-guide/).

2. At the very bottom of [Understanding WordPress Locale Glossary](https://learn.wordpress.org/lesson/intro-to-glossary-creation/), there is a plain URL instead of a link. The URL is invalid.

To fix the issue, add a standard (handbook?) embed linking to: https://make.wordpress.org/polyglots/handbook/translating/glossaries-and-style-guides-per-locale/.

**Comment by kaitohm** [comment]
I've updated the link 👍
