### ISSUE TITLE
Training Team Handbook: Creating a Tutorial language updates

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1806]
Recently I updated the [Creating a Tutorial](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial/) page on the Training Team handbook.

- I separated step 7 into the content before the review
- I added step 8, about the review process
- I added step 9 about publishing your tutorial, using the content that was split from step 7

Subsequently, I noticed that this handbook page has been translated into Gujarati (via Google Doc), Italian, and Tamil (via Google Doc).

So I am creating this issue to suggest updating those translations with the changes, either by the original translation authors, or by other contributors who have the time.

**Comment by kaitohm** [comment]
@margheweb @piermario Could you update the Italian handbook page please?

@SagarLadani (Gujarati) and @karthick-murugan (Tamil) Could you do one of the following?
1. Update the Google Doc content
2. Change the access settings on the document so that anyone can update the content
3. Transfer ownership of the Google Doc to me so that I can move the Google Doc to the Training Team's shared Google Drive

I think option 3 would be the best. Once moved to the Training Team's Google Drive, any team rep will be able to add additional editors/translators to the document to make revisions as needed. If you are happy to proceed with option 3, please send me a message in Slack and I will share my email address with you there.

**Comment by karthick-murugan** [comment]
@bsanevans - I have updated the google docs such that anyone can update the content. Will check how to transfer the ownership and will also update that. Thank You.
