### ISSUE TITLE
Feature request - add Subscribe block to footer

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1837]
Currently, there's no way for folks to easily sign up to the Learn.WordPress.org newsletter - get notices about posts published on the site. (Recent newsletter: https://learn.wordpress.org/learn-wordpress-august-newsletter/) Could we add the Jetpack Subscribe block to the footer, please?

**Comment by Piyopiyo-Kitsune** [comment]
I looked into enabling Jetpack Newsletter on the Learn website and it looks like we don't have the option to. This may be because we need to upgrade our Jetpack license. I'm checking in with the faculty to see if they have any thoughts on whether or not to upgrade here: https://wordpress.slack.com/archives/C03B11FA16D/p1695365685269519

**Comment by Piyopiyo-Kitsune** [comment]
![Screenshot 2024-07-30 at 9 45 42 AM](https://github.com/user-attachments/assets/9c0b972d-fcc1-4952-a6fd-dcc601e0d7c1)

Seeing that this has been included in the new design.

**Comment by kathrynwp** [comment]
Closing this out, as the subscription box was added in #2468
