### ISSUE TITLE
Bangla translation for Tutorial "Posts vs. Pages: What’s the Difference?"

### ISSUE THREAD

**Issue by devmuhib009** [WordPress/Learn#1856]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/posts-vs-pages-whats-the-difference/
- Link to original content GitHub issue (optional): 
- Language you'll be translating to: Bangla
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: @huzaifaalmesbah
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by devmuhib009** [comment]
I just completed the translation. Here is the[ doc file](https://docs.google.com/document/d/1--dwkuUqjZaPLj4lKcRfdDiMkd7gGlKkp1UuN06SCV4/edit?usp=sharing).

**Comment by huzaifaalmesbah** [comment]
Thanks For the Bangla translation @devmuhib009 I check your full document file. I have some suggestions. I have tried to make it beautiful, so that is easier to understand.

> সিদ্ধান্ত নিন, আপনার নিজের ওয়েবসাইটে কখন পোস্ট ব্যবহার করবেন এবং কখন পেইজ ব্যবহার করবেন।

সিদ্ধান্ত নিতে পারবেন, আপনার নিজের ওয়েবসাইটে কখন পোস্ট ব্যবহার করবেন এবং কখন পেইজ ব্যবহার করবেন।

> প্রথমে আপনি যখন ওয়ার্ডপ্রেস শুরু করেন, পোস্ট এবং পেইজের মধ্যে পার্থক্য খুবই সামান্য বলে মনে হতে পারে। আপনি যখন এডিটরে ক্লিক করেন, তখন পোস্ট এবং পেজ ব্লক এডিটর প্রায় একই রকম দেখায়। 

আপনি যখন প্রথম ওয়ার্ডপ্রেস দিয়ে শুরু করবেন, পোস্ট এবং পেইজের মধ্যে পার্থক্য খুবই সামান্য বলে মনে হতে পারে। আপনি যখন এডিটরে ক্লিক করেন, তখন পোস্ট এবং পেইজ ব্লক এডিটর প্রায় একই রকম দেখায়। 

> ওয়েবসাইটের ফ্রন্টেন্ডে তারা দেখতে একই রকম। 

ওয়েবসাইটের ফ্রন্টেন্ডে পোস্ট বনাম পেইজ দেখতে একই রকম। 

> দুটি একসাথে তুলনা করার সাথে সাথে আপনি ভাবতে পারেন, পোস্টগুলি কেন একটি তারিখ অন্তর্ভুক্ত করে যেটা তাদের URL এর সাথে সংযুক্ত?

এই দুটি একসাথে তুলনা করার সাথে সাথে আপনি ভাবতে পারেন, পোস্টগুলি কেন তাদের URL এর সাথে একটি তারিখ সংযুক্ত করে?

> অনেক ক্ষেত্রে, আপনাকে আগেই একটি পেইজে এটির একটি লিঙ্ক তৈরি করতে হবে আপনার ওয়েবসাইটে দেখাতে হলে।

অনেক ক্ষেত্রে, আপনাকে আগেই একটি পেইজে এটির একটি লিঙ্ক তৈরি করতে হবে আপনার ওয়েবসাইটে দেখানোর পূর্বে  ।

> এখন, আপনি যদি একটি পেইজ তৈরি করেন, আপনি এটিকে সরিয়ে না নেয়া পর্যন্ত এটি যেখানে রাখবেন সেটি সেখানেই থাকবে।

এখন, আপনি যদি একটি পেইজ তৈরি করেন, আপনি এটিকে সরিয়ে না নেয়া পর্যন্ত এটি যেখানে রাখবেন সেখানেই থাকবে।

> তাই এটি একটু বেশি স্থায়ী হয়৷

তাই পেইজ একটু বেশি স্থায়ী হয়৷

> আপনি অবিলম্বে একটি পোস্ট প্রকাশ করতে পারেন

আপনি তাৎক্ষণিকভাবে একটি পোস্ট প্রকাশ করতে পারেন

> তাহলে আপনি আপনার পোস্ট এডিটিং করার সময় "মোর" ট্যাগটি ব্যবহার করতে পারেন।

তাহলে আপনি আপনার পোস্ট এডিটিং করার সময় "More/আরও" ট্যাগটি ব্যবহার করতে পারেন।

> পোস্টগুলি ক্যাটাগরি বা ট্যাগ পেইজ হিসাবে পরিচিত কিছুতেও দেখানো হতে পারে। পেইজগুলোর ছাড়াও, পোস্টগুলিতে ক্যাটাগরি এবং ট্যাগ অন্তর্ভুক্ত থাকে, যা আপনাকে বিভিন্ন উপায়ে আপনার পোস্টগুলিকে গোষ্ঠীবদ্ধ করতে সাহায্য করে৷

পোস্টগুলি ক্যাটাগরি বা ট্যাগ পেইজ হিসাবে দেখানো যেতে পারে। পেইজগুলো ব্যাতীত, পোস্টগুলিতে ক্যাটাগরিসমূহ এবং ট্যাগসমূহ অন্তর্ভুক্ত থাকে, যা আপনাকে বিভিন্ন উপায়ে আপনার পোস্টগুলিকে গ্রুপ করতে সাহায্য করে৷

> উদাহরণস্বরূপ, একটি ভ্রমণ ব্লগে, বিভিন্ন মহাদেশের জন্য একটি ক্যাটাগরি থাকতে পারে। 
প্রতি পোস্টের জন্য একটি বা দুটি ক্যাটাগরি ব্যবহার করতে উপদেশ দেয়া হয়ে থাকে, সেগুলির সাধারণত ধারণাকে আলাদা করে বোঝানোর জন্য। এদিকে, ট্যাগগুলি এমন ছোট ধারণাগুলির জন্য যা পোস্টগুলির মধ্যে মিল থাকতে পারে, যেমন পাহাড় সহ স্থান, নদী সহ স্থান বা মালভূমি সহ স্থান। এগুলো ট্যাগের ভাল উদাহরণ হতে পারে। 

উদাহরণস্বরূপ, একটি ভ্রমণ বিষয়ক ব্লগে, বিভিন্ন মহাদেশের জন্য একটি ক্যাটাগরি থাকতে পারে। সাধারণত উপদেশ দেয়া হয়ে থাকে যে, প্রতি পোস্টের জন্য একটি বা দুটি ক্যাটাগরি ব্যবহার করতে, সেগুলির সাধারণত আইডিয়াকে আলাদা করে বোঝানোর জন্য। এদিকে, ট্যাগসমূহ পোস্টগুলির মধ্যে মিল থাকতে পারে এমন ছোট ধারণাগুলির জন্য, যেমন পাহাড়সহ স্থানসমূহ, নদীসহ স্থানসমূহ বা মালভূমিসহ স্থানসমূহ। এগুলো ট্যাগের উত্তম উদাহরণ হতে পারে। 

> কখনও সম্পূর্ণ আর্টিকেল, কখনও বা শুধুমাত্র একটি শিরোনাম বা একটি অংশ। এটি আপনার থিমের উপর নির্ভর করে।

এটি আপনার থিমের উপর নির্ভর করে কখনও সম্পূর্ণ আর্টিকেল, কখনও বা শুধুমাত্র একটি শিরোনাম বা  কিছু অংশ প্রদর্শিত হয়।

> পোস্টের তারিখের উপর ভিত্তি করে পোস্টগুলির জন্য একটি ইউনিক URL নির্ধারিত হয়৷

পোস্টের তারিখের উপর ভিত্তি করে আপনার পোস্টগুলির জন্য একটি ইউনিক URL নির্ধারিত হবে ৷

> এই পেইজের শিরোনাম এবং একটি পোস্টের শিরোনাম তুলনা। আপনি কি কোন পার্থক্য দেখতে পান?

এই পেইজের শিরোনাম এবং একটি পোস্টের শিরোনাম এর সাথে তুলনা করলে, আপনি কি কোন পার্থক্য দেখতে পান? 

> যা আপনি পোস্ট করা শুরু করার আগে সেটআপ করে নিতে পারেন৷

যা আপনি পোস্ট শুরু করার আগে সেটআপ করে নিতে পারেন৷

> তাহলে আপনি একটি পেইজ নয় একটি পোস্ট ব্যবহার করতে চাইবেন৷ আর এখানেই একটি ডায়নামিক পোস্ট এবং স্ট্যাটিক পেইজের মধ্যে পার্থক্য রয়েছে।

তাহলে আপনি একটি পেইজ নয় বরং একটি পোস্ট ব্যবহার করতে চাইবেন৷ আর এখানেই একটি ডায়নামিক পোস্ট এবং স্ট্যাটিক পেইজের মধ্যে পার্থক্য রয়েছে।

**Comment by huzaifaalmesbah** [comment]
> ট্রান্সক্রিপ্ট

প্রতিলিপি

I think this usage is better. what do you think

**Comment by devmuhib009** [comment]
Thanks for your suggestions, I will edit the doc soon and update here. @huzaifaalmesbah

**Comment by devmuhib009** [comment]
@huzaifaalmesbah I just modified all the content that you suggested. Can you please review the updated [document here](https://docs.google.com/document/d/1--dwkuUqjZaPLj4lKcRfdDiMkd7gGlKkp1UuN06SCV4/edit?usp=sharing)?

**Comment by huzaifaalmesbah** [comment]
I've reviewed the revised document, I believe everything appears good.

**Comment by devmuhib009** [comment]
Thanks a lot for reviewing the content.

**Comment by kafleg** [comment]
Added the content to the learn site, https://learn.wordpress.org/?p=42370&post_type=lesson-plan&preview=true 

CC: @webtechpooja

**Comment by webtechpooja** [comment]
@kafleg, you have created a lesson plan, and the Tutorial Transcript falls under the Tutorial menu. I have drafted a Tutorial with the transcript. here is the draft link: https://learn.wordpress.org/?p=42762&post_type=wporg_workshop&preview=1&_ppp=06675d7c6d 
@devmuhib009, please have a look at the draft and confirm if everything is OK. Then I'll hit publish it. Thank you all for your contribution.

**Comment by devmuhib009** [comment]
Hello @webtechpooja and @kafleg 

Everything looks, fine. But bullet point is not required in this section. Because I already marked the numbers in Bangla. So, please remove the bullet points and rest of the things are looking good. Thanks a lot.

![bullet](https://github.com/WordPress/Learn/assets/142894870/281c02dd-10ca-4889-8028-ea5b1871067b)

**Comment by devmuhib009** [comment]
Hello @webtechpooja and @kafleg 

In Comprehension questions section there were three questions. I noticed in the draft there are only two. Also, numbering was in english, so I modified and provided here. Please update this one and rest of the things are fine.

সম্পূরক প্রশ্ন

১। কেন পোস্ট এবং পেইজ একে অন্যের থেকে আলাদা?
২। কেন পোস্টগুলিকে ‘ডায়নামিক’ হিসাবে বিবেচনা করা হয়?
৩। কেন একটি পেইজকে “স্ট্যাটিক” বিবেচনা করা হয়?

**Comment by webtechpooja** [comment]
Updated, Please check now

**Comment by devmuhib009** [comment]
Awesome. Everything is ok. You can publish. Thanks

**Comment by webtechpooja** [comment]
Tutorial published - https://learn.wordpress.org/tutorial/bn-posts-vs-pages-whats-the-difference/
