### ISSUE TITLE
Add transcript section to workshop pages

### ISSUE THREAD

**Issue by varlese** [WordPress/Learn#186]
On individual workshop pages ([for example](https://learn.wordpress.org/workshop/user-management/)), it would be helpful to be able to display the video transcript in its own section for viewers to follow along or print for reference.

Would it be possible to add a section (either in the sidebar or a toggle) to display the transcript in full when activated?

In thinking through how to handle transcripts, it will be helpful to also consider cases in which the video is captioned or subtitled in multiple languages.

Just in case a visual is helpful, this is a very rough idea of where we could consider placement: 

<img width="1003" alt="transcript UI" src="https://user-images.githubusercontent.com/1361760/105399197-4eaae280-5bf1-11eb-89fa-9869b3d2ce7b.png">

**Comment by gwwar** [comment]
Maybe add the transcript below the fold (on the same page), and add an anchor link to jump to the start of the content?

**Comment by andreamiddleton** [comment]
Or maybe a Transcription Block? Or a Summary block we use for Transcriptions? Available to a relatively low user permissions level?

**Comment by courtneyr-dev** [comment]
I really like the idea of tucking it behind post content but making it available.  I have a student that actually prints the transcripts from our course videos as that helps her then highlight things and make notes on it herself, feeling some ownership in her learning vs passive consumption.  Thus, I also would like to see the transcript have quick access to print the transcripts.

**Comment by iandunn** [comment]
It seems like we could automatically generate the transcript based on the caption files that are stored on WPTV. The formatting probably wouldn't be perfect, but it'd save some manual work.

The drawback would probably be most apparent around paragraphs, since we wouldn't be able to programmatically detect when they should be<sup>1</sup>. Without any formatting, it'd look like this:

<pre>
Hello, and welcome to this Learn WordPress workshop on user

management. Today, we will learn how to add, remove and update

user accounts within your WordPress website. User

Management is important and useful for a few different

reasons. For instance, you may want to add another user to your

website without allowing public registration for new accounts.
</pre>

We could possibly do some basic changes, though, like making it so that there are line breaks between sentences (assuming the captioner added them, and the written language has some kind of full stop at the end of sentences):

<blockquote>
Hello, and welcome to this Learn WordPress workshop on user management.<br/><br/>
Today, we will learn how to add, remove and update user accounts within your WordPress website. <br/><br/>
User Management is important and useful for a few different reasons.<br/><br/>
For instance, you may want to add another user to your website without allowing public registration for new accounts.
</blockquote>

That'd still be difficult to read on a long page, but having the extra whitespace between the lines might help. Here's an example of how YouTube displays auto-generated transcripts:

![Screen Shot 2021-03-01 at 2 12 16 PM](https://user-images.githubusercontent.com/484068/109566073-3653a080-7a98-11eb-9308-473704f26337.png)

It'd be good to get input from a designed on how the page elements should be laid out.

<br>

_[1] - We could use the timestamps in the TTML file to make a rough guess. But that seems overly complex, at least for v1._

**Comment by iandunn** [comment]
> quick access to print the transcripts

From a dev perspective, that should be easy. There are [many ways to print a selection of the page](https://stackoverflow.com/questions/468881/print-div-id-printarea-div-only). An `iframe` might be simplest in this context.

**Comment by iandunn** [comment]
Er, if we're [already using otter.ai to generate the captions](https://wordpress.slack.com/archives/C02RW657Q/p1608022835162800), then their transcription export might be better than the TTML file.

**Comment by coreymckrill** [comment]
@iandunn Is there a way to access the caption files on wp.tv when the only thing linking a workshop post to a video is the wp.tv URL? (i.e. https://wordpress.tv/2021/01/14/anne-mccarthy-how-to-do-triage-on-github/)

**Comment by iandunn** [comment]
Probably not but default (although I haven't looked), but it should be easyish to do via the REST API and a small bit of code.

**Comment by iandunn** [comment]
I'm guessing we're going to want the transcript to be editable, regardless of whether the initial version comes from TTML or Otter. 

So either way we'll need a block(s) in the template, maybe a custom one. That could maybe be as simple as extending the Group block so that it has a `.workshop-transcription` class hardcoded on the container.

[Related discussion about the layout of the template](https://wordpress.slack.com/archives/C01KC5VDQBC/p1614641586017200).

**Comment by iandunn** [comment]
This is deployed now. Existing workshops are unaffected, but can be manually converted to the latest template to get the transcript.

New workshops will have a placeholder for it automatically.
