### ISSUE TITLE
Tutorial - Common APIs - Internationalisation

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1898]
# Topic Description
Internationalization is the process of developing your application in a way that can easily be translated into other languages, which is known as localization. In this tutorial, you will learn why Internationalization is important, and how to implement it in your WordPress plugin or theme.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [Online Workshop](https://wordpress.tv/2023/08/04/common-wordpress-apis-internationalization/)
- [Documentation](https://developer.wordpress.org/apis/internationalization/)

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [ ] Vetted by instructional designers for content idea
- [ ] Provide feedback of the idea
- [ ] Gather links to Support and Developer Docs
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [ ] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [ ] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [ ] Tutorial published on WPTV
- [ ] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [ ] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [ ] Tutorial post reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by jonathanbossenger** [comment]
WIP Script: https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/common-apis-internationalisation.md

**Comment by jonathanbossenger** [comment]
Video for review: 

https://github.com/WordPress/Learn/assets/180629/e185a9c4-31c1-4b53-8c74-220ae3b6659a

**Comment by justintadlock** [comment]
Hi, @jonathanbossenger. I just had a few notes:

00:34 - "118n" should be spelled "i18n" in the slide.

Not sure if it's worth changing, but the official theme directory would require that you use `twenty-twenty-three-child` for your text domain. The default Twenty* themes are the only exceptions to this rule for legacy reasons.

5:30 - `esc_html_e()` would be required for the DotOrg theme directory for this in particular, but I understand that you're walking through the basic functions and not diving into the escaping functions.

**Comment by jonathanbossenger** [comment]
Thanks for the feedback @justintadlock, I especially appreciate the notes from the point of view of the .org theme directory. I'll incorporate them into my tutorial.

**Comment by peiraisotta** [comment]
## Tutorial Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [ ] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

- At min 0:33 instead of i18n it's written 118n
- "A disclaimer must be added to the content that any brand/product/service mentioned is considered a suggestion and not an endorsement." In this tutorial, 3 translation plugins were used as examples, but there wasn't a clear disclaimer.
- " Technical concepts introduced in the content are accurate." I don't have the technical knowledge to judge this point.
- "Media assets are all in the public domain " I don't understand this point.
- One more thought: I've noticed that in this [other tutorial](https://github.com/WordPress/Learn/issues/1726) the video ends with a last slide inviting to visit Learn WordPress and here there is not. In my opinion, it would be nice and consistent if all tutorials end in the same/similar way with the same slide.

**Comment by jonathanbossenger** [comment]
Thanks for the feedback @peiraisotta 

> In this tutorial, 3 translation plugins were used as examples, but there wasn't a clear disclaimer.
In the past whenever we mention free products in the WordPress plugin or theme repository, this typically isn't required. This guideline is aimed more at folks who might benefit from endorsing a specific product. 

> Media assets are all in the public domain
This just means that if I'm using any images or videos in the tutorial, they must not be copyright material. As I'm not using any images or videos, this doesn't apply. 😃 

> it would be nice and consistent if all tutorials end in the same/similar way with the same slide.
That's an interesting point, because generally these videos are hosted/viewed on Learn.WordPress.org, so it always seems weird to me to tell folks to visit a site they are already on 😁 But I will raise it with the team at the next meeting for discussion.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/10/27/common-apis-internationalization/
