### ISSUE TITLE
Content Feedback - Confusing Application Process for Contributor & Team Badge

### ISSUE THREAD

**Issue by gudrunfrank** [WordPress/Learn#1951]
## Overview
- Content title: Team Profile Badges 
- Content URL: https://make.wordpress.org/training/handbook/about/team-profile-badges/#requesting-a-profile-badge
- Are you reporting an error (such as outdated information), or providing improvement ideas?: 

## Feedback Details
When clicking on the links to request a badge, you are being directed to a page that tells you that you are not a member. It does not look welcoming at all. When you then click on "Request Membership", the text on that page is very small and it does not look inviting. 
Suggestion: insert a form for applying for the badge and make applicant a member of the group automatically after approval. 

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by kaitohm** [comment]
Unfortunately, the application system is used for all WordPress teams, and it isn’t something Training can modify. The reason we need folks to apply for a badge with that form is because team reps can’t provide badges like you would invite someone as a user to a site. We can only accept or reject, and only after the contributor has submitted an application first.

I've provided more context to this issue in Slack: https://wordpress.slack.com/archives/C02RW657Q/p1704783957409749?thread_ts=1704738892.952309&cid=C02RW657Q

I'm closing this from our end. But feel free to raise your feedback in the #meta Slack channel, as they would be the best folks to handle this.
