### ISSUE TITLE
Permalinks, rewriting urls on Apache and Nginx

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1988]
# Learning Objective

Describe how permalinks work. Identify where Permalinks can be set for a WordPress installation.

# Relevant Links

- https://wordpress.org/documentation/article/customize-permalinks/

# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for Q/A review
- [x] Lesson submitted and published to WPTV
- [x] Lesson transferred to YouTube
- [x] Lesson reviewed and ready to publish
- [x] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/how-wordpress-works/permalinks.md

**Comment by jonathanbossenger** [comment]
Video for review: 

https://github.com/WordPress/Learn/assets/180629/fe2aabab-1466-4faa-9e7c-435fb9e7d72d

**Comment by cynthianorman** [comment]
## Tutorial Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [ ] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.

Starting at 1:37 to 1:46 replace the visual to what you have at 1:46 because the skipping around is confusing 

At 3:45 you have a transition to an unwanted visual, continue what you have as a visual at 3:44 through instead of changing it

**Comment by nftushar** [comment]
# Learning Objective Review Checklist
Please tick all items you've confirmed:
> * [ ] **Learning objective is clear:** Describe how permalinks work. Identify where Permalinks can be set for a WordPress installation.
> * [ ] **Relevant links are provided:**
   - [ ] [WordPress Permalinks Documentation](https://wordpress.org/documentation/article/customize-permalinks/)
> * [ ] **Lesson creation checklist is complete:**
   - [ ] Gather any relevant links to Support, Docs, or related material
   - [ ] Description and Objectives finalized
   - [ ] Lesson created and announced to the team for Q/A review
   - [ ] Lesson submitted and published to WPTV
   - [ ] Lesson transferred to YouTube
   - [ ] Lesson reviewed and ready to publish
   - [ ] Lesson published to Learn.WordPress.org

# Feedback:
The learning objective is clear, focusing on describing how permalinks work and identifying where they can be set for a WordPress installation. The provided link to the WordPress Permalinks Documentation is relevant and adds value to the objective.

Once the comment has been published, go through and check off items as you review the comment. Leave an additional comment on the GitHub issue with any additional feedback you have.

And you’re done! Thank you for contributing to the Training Team. If you have any more thoughts or questions, feel free to share!

**Comment by jonathanbossenger** [comment]
> Starting at 1:37 to 1:46 replace the visual to what you have at 1:46 because the skipping around is confusing
> At 3:45 you have a transition to an unwanted visual, continue what you have as a visual at 3:44 through instead of changing it

Same issue as the [web servers video](https://github.com/WordPress/Learn/issues/1985#issuecomment-1884962769), waiting on feedback from my support ticket

**Comment by jonathanbossenger** [comment]
Updated video


https://github.com/WordPress/Learn/assets/180629/5e88a5e9-d0ff-46ba-b798-6ab0b25bb030

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/permalinks-rewriting-urls-on-apache-and-nginx/

**Comment by jonathanbossenger** [comment]
## YouTube chapters

(0:00) Introduction
(0:39) Query String Variables
(2:18) WordPress and Permalinks
