### ISSUE TITLE
Tutorial: Using the Media Library

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2071]
# Details

- Topic description: Using the Media library 
- Audience (User, Developer, Designer, Contributor, etc.): User
- Learning objectives (What will the learner be able to do as a result of this content?): Feel confident navigating the media library and inserting images into posts and pages
- Content type (Tutorial, Online Workshop, Course or Lesson Plan): Lesson
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): Yes

### Automation Code
//tutorial

**Comment by westnz** [comment]
## Tutorial

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/6ef20380-682f-48da-addd-c9f016ff0901

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

**Comment by ironnysh** [comment]
Hi @westnz, 
Thanks for this excellent overview of the Media Library. I liked the focus on image optimization!

I wrote down a few notes that came up while I watched the tutorial:

**At 0:07:** Minor copy suggestion: 
- Use “Learn” and “navigate” instead of learning and navigating
- Use “Understand” instead of “Identifying”

Referring to image optimization _before_ uploading (which comes up again **at 4:52**) might confuse people who decide to use a plugin, as most handle the optimization either during or after the upload.

I’d recommend adding a third list item to the _Learning outcomes_ that covers the importance of adding alternative text (ALT) to images. Right now, ALT is mentioned as a nice-to-have (using the word “encouraged” at 3:43) while in practice, providing a text alternative to non-text content that isn’t decorative is a legal requirement in many countries (see [this page for international a11y guidelines](https://www.lflegal.com/global-law-and-policy)).

**At 0:50:** I couldn’t tell if all the media assets displayed throughout the tutorial are CC0.

**At 1:28:** It could be nice to briefly cover the two additional items in the drop down—_Archives_ and _Mine_.

**At 1:59:** It’s worth mentioning that it’s the uploading date. Some people might assume it’s the date the photo was created.

**At 2:18:** It’s possible to search for images even if you haven’t added a _Description_. The search field supports various parameters, including file names, etc.

**At 2:45:** It’s worth mentioning a handy feature of the _List view_: The option to [sort the files](https://wordpress.org/documentation/article/media-library-screen/#sortable-columns) by clicking on the column headers.

**At 3:35:** The phrase “you’ll be able to add metadata” could be confusing in this context because it relates to information embedded in the file itself while it’s being created. An alternative to _metadata_ can be _attributes_.

**At 5:41:** Consider highlighting the (very good 🙂) [Performance Lab plugin by the WordPress Performance Team](https://wordpress.org/plugins/performance-lab/), which automatically converts JPEG images to WebP files.

**Additional resources:** It’s worth referencing the [Media library screen Support guide](https://wordpress.org/documentation/article/media-library-screen/) in the video (or adding a link somewhere).

[**Promotional Guidelines**](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/#actively-promote-learn-wordpress-and-other-official-wordpress-content): The call-out to Learn WordPress is missing.

**Comment by lada7042** [comment]
# Tutorial Development Checklist
- [ ] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [ ] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [ ] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [ ] Tutorial published on WPTV
- [ ] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [ ] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [ ] Tutorial post reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by ghost** [comment]
#Review 2


## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [ ] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.
Great job! Since this tutorial is part of the beginner user pathway, I feel it is a good introduction without overwhelming the user.

**Comment by westnz** [comment]
Thank you for the feedback @ironnysh and @lada7042.! I appreciate it!

We will not be adding a call-out to Learn WordPress in the learning pathway lessons.  All the media assets are in the public domain or from my Canva account.

**Comment by markmemayank** [comment]
Hi @westnz 

It is a great overview of WordPress Media Library, I watch out the video and it look perfect and some points are already highlighted by Reviewer 1 & 2. 

So now it's good to go.

Great Job!

**Comment by westnz** [comment]
Thank you @markmemayank

**Comment by westnz** [comment]
Updated and ready to publish this week.

**Comment by westnz** [comment]
Updated and published in Sensei as part of the draft Beginner User learning pathway.
