### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2074]
# Learning Objectives

A brief introduction to HTML, what HTML looks like, and how it's rendered in the browser. Also, include a brief introduction on writing accessible HTML markup. Wrap up with additional links for further reading. 

# Relevant Links

- [HTML on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML)
  - [Accessible HTML on MDN](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML)
- [HTML on Web.dev](https://web.dev/learn/html)
  - [Accessible HTML on Web.dev](https://web.dev/learn/accessibility)
 - [freeCodeCamp Responsive Web Design Course](https://www.freecodecamp.org/learn/2022/responsive-web-design/)

# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for Q/A review
- [ ] Lesson submitted and published to WPTV
- [ ] Lesson transferred to YouTube
- [ ] Lesson reviewed and ready to publish
- [ ] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/the-programming-languages-of-wordpress/01-html.md

Video for review:

https://github.com/WordPress/Learn/assets/180629/2dc40f71-bb49-4c5f-a8e4-7f5d1f53ad46

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

**Comment by cynthianorman** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

@jonathanbossenger your overview content and recommended resources are wonderful!

I'm wondering since it seems you won't be covering [Tools and Setup (namely the content of this page) ](https://developer.wordpress.org/themes/getting-started/tools-and-setup/)for developers wanting to move onto the next module, perhaps we could add it either at the end of Module 2 The programming languages of WordPress or the beginning of Module 3 An introduction to developing WordPress themes. Thoughts?

**Comment by jonathanbossenger** [comment]
> I'm wondering since it seems you won't be covering [Tools and Setup (namely the content of this page) ](https://developer.wordpress.org/themes/getting-started/tools-and-setup/)for developers wanting to move onto the next module

@cynthianorman it's funny you mention that when I was working on the programming languages lessons I realized that's the one module we don't have early on, so I was planning to look into it when I get back from my leave. 

I think your suggestion makes perfect sense. What do you think about having this as its own stand alone module?

**Comment by cynthianorman** [comment]
Hi @jonathanbossenger, I think a stand alone Tools and Setup module could definitely be warranted here.

I'm also thinking that since learners could choose to skip theme development and go straight to plugin development modules, their needs in the new Tools and Setup module should be taken into consideration too.

**Comment by jonathanbossenger** [comment]
@cynthianorman that's a valid point. I'll look at adding a new module when I'm back at my desk on Monday.

**Comment by SierraTR** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x ] Learning outcomes/objectives are clear.
- [ x] Technical concepts introduced in the content are accurate.
- [x ] The speed of demonstrations are easy to follow.
- [ x] The narration audio matches what is shown visually.
- [x ] Spelling and grammar are correct.
- [x ] Sound quality is consistent throughout the video.
- [x ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Very well done. Also, I agree with Cynthia in that there needs to be a consideration given to what happens if basic information is missed because a learner skips ahead to a module if interest without stepping through the pathway. Perhaps a sort of prerequisite list at the beginning of a module that builds upon previously presented material.

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/html/
