### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2078]
# Learning Objectives

A brief introduction to MySQL, and some examples of MySQL queries, using the phpMyAdmin interface. Include an example of a create, read, update, and delete query. Wrap up with links to the MySQL Documentation for further reading.

# Relevant Links

- https://dev.mysql.com/doc/refman/8.2/en/tutorial.html

# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for Q/A review
- [ ] Lesson submitted and published to WPTV
- [ ] Lesson transferred to YouTube
- [ ] Lesson reviewed and ready to publish
- [ ] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/the-programming-languages-of-wordpress/05-mysql.md

Video for review


https://github.com/WordPress/Learn/assets/180629/b8f522f0-4d54-4a62-9acc-f0ed08d10bb0

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [ ] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Hi @jonathanbossenger, thanks for another valuable tutorial! :-)

- The overall speed is easy to follow, but the bits showing the query's result (after you hit the "Go" button) could benefit from a few more seconds of screen time.
- Is it possible to highlight or zoom in on the specific SQL statements as they appear inside the phpMyAdmin UI? This is especially relevant when you discuss the `SELECT` option: `*` at 2:03 vs. `value` at 2:12.

**Comment by jonathanbossenger** [comment]
Hey @ironnysh 

As always, thanks for the great feedback, I'll work on updating the video to incorporate both changes.

**Comment by ironnysh** [comment]
Thanks! Happy to help :-)

**Comment by SierraTR** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [ x] Learning outcomes/objectives are clear.
- [ x] Technical concepts introduced in the content are accurate.
- [ ] The speed of demonstrations are easy to follow.
- [x ] The narration audio matches what is shown visually.
- [ x] Spelling and grammar are correct.
- [ x] Sound quality is consistent throughout the video.
- [x ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

I agree with @ironnysh in that the query results screens need to be displayed a bit longer. I knew what I was looking for and still had a hard time finding the displayed results in the short time they were on the screen.

I also agree that it would be very helpful to highlight or circle with an obvious color what the displayed results of the query so that it can be picked out of the page text more easily.

Nice job and good use of referring back to previous pathways lessons to answer possible questions if the learner jumped to this lesson.

**Comment by jonathanbossenger** [comment]
Updated with more detailed views of the queries run, and their results. 


https://github.com/WordPress/Learn/assets/180629/b1b13b7a-f5b3-4815-bad0-ae9d6fe0f459

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/mysql/
