### ISSUE TITLE
WordPress Action Hooks

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2080]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Lesson
- Content title: WordPress Action Hooks
- Topic description: Explain the concept of action hooks, how they work, and how to use them.
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Any

# Learning Objectives

- Identify what action hooks are
- Describe how action hooks work
- Explain how to use action hooks with an example

# Related Resources and Other Notes
- https://developer.wordpress.org/plugins/hooks/actions/
- https://developer.wordpress.org/apis/hooks/action-reference/
- https://learn.wordpress.org/tutorial/wordpress-action-hooks/

**Comment by jonathanbossenger** [comment]
Original tutorial content: https://learn.wordpress.org/tutorial/wordpress-action-hooks/

**Comment by jonathanbossenger** [comment]
# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for Q/A review
- [x] Lesson submitted and published to WPTV
- [x] Lesson transferred to YouTube
- [x] Lesson reviewed and ready to publish
- [x] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script: 

https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/wordpress-hooks/02-action-hooks.md

**Comment by jonathanbossenger** [comment]
Video for review:


https://github.com/WordPress/Learn/assets/180629/2e721a66-36f1-44c3-8824-0cafe7716bc5

**Comment by TinaCollier** [comment]
Hi @jonathanbossenger ,

Same issue here. Is there a link I can follow to watch the video?

<img width="513" alt="Screenshot 2024-02-27 at 7 24 03 AM" src="https://github.com/WordPress/Learn/assets/102442293/5c233067-9530-4baf-a507-0392b6cc3b66">

**Comment by jonathanbossenger** [comment]
https://github.com/WordPress/Learn/issues/2079#issuecomment-1972571188

**Comment by backpocketACE** [comment]
Video play was fine. 

- [ x] Learning outcomes/objectives are clear.
- [ x] Technical concepts introduced in the content are accurate.

- - [ x] The speed of demonstrations is easy to follow. (Speed was fine; I had to rewatch a second time to understand the concept more fully - most likely due to my inexperience.)

- - [ x] The narration audio matches what is shown visually. (At :20 sec - you spoke "Actions allow you to perform **some** action at a specific point during the execution..." Your screen states, "Actions...allow you to perform **specific** action at a specific point during the execution..." Slight difference: does it change things? Probably not. )

- - [ x] Spelling and grammar are correct.
- [ x] Sound quality is consistent throughout the video.
- [ x] [Brand Usage Guidelines] and [Promotional Guidelines] are being followed.
- [ x] Media assets are all in the public domain [CC0].

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Agree with @JunebackpocketACE’s comment about the **some** vs. **specific**.
Otherwise, all good :-)

**Comment by jonathanbossenger** [comment]
Thank you @JunebackpocketACE and @ironnysh for the reviews.

That was probably an error in my slides, I will get this updated before publishing.

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/action-hooks/
