### ISSUE TITLE
Introduction to themes for developers

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2082]
# Learning Objectives

In this lesson, you will get an overview of what a WordPress theme is.

The learning outcomes are to:

1. Discover the possibilities of a WordPress theme.
2. Explore the fundamental structure of a classic, block and hybrid theme.
3. Differentiate between a theme and a plugin.

# Relevant Links
https://developer.wordpress.org/themes/getting-started/what-is-a-theme/
https://developer.wordpress.org/themes/getting-started/quick-start-guide/ 
https://learn.wordpress.org/tutorial/choosing-and-installing-theme/ 

# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for review
- [x] Lesson reviewed
- [x] Lesson video submitted and published to WPTV
- [x] Lesson created on Learn.WordPress.org 
- [x] Lesson video published to YouTube
- [x] Lesson on Learn.WordPress.org updated with YouTube video
- [x] Lesson published to Learn.WordPress.org

**Comment by cynthianorman** [comment]
Uploading What Is A Theme _C.mp4…

**Comment by cynthianorman** [comment]
This Beginner Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

https://youtu.be/adnOwLDyUDU (unlisted video)

**Comment by askdesign** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x ] Learning outcomes/objectives are clear.
- [** ] Technical concepts introduced in the content are accurate.
- [** ] The speed of demonstrations are easy to follow.
- [x ] The narration audio matches what is shown visually.
- [x ] Spelling and grammar are correct.
- [x ] Sound quality is consistent throughout the video.
- [x ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

** Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.
Cynthia, nice job! This is a really good overview of "What is a theme?". You stick with the essentials, and don't get too detailed.
:25 - Suggest that you show the nav area and how to find the Themes on WordPress.org: Extend > Themes
:25 - Maybe slow down the scroll so that users can see a few of themes listed
1:12 - Nice how you show the layouts and features that new developers can include in a theme
1:45 - So important that you mention accessibility and contrast as one of the key attributes
3:41 - Suggest being more specific: Plugins control specific behaviors of your site.
3:48 - You tell the user about getting started with theme development, which, for me, is a whole different topic. Maybe the phrasing could be adjusted to something like:
"If you are interested in getting started with theme development..."

**Comment by cynthianorman** [comment]
@askdesign Hi Anne, thanks so much for your feedback! 

> 3:48 - You tell the user about getting started with theme development, which, for me, is a whole different topic. Maybe the phrasing could be adjusted to something like:
> "If you are interested in getting started with theme development..."

Just to clarify, this video is the first of a series meant for the beginner theme developer.

**Comment by jonathanbossenger** [comment]
## Lessons Review Checklist

Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

@cynthianorman great introduction to WordPress themes, I'm looking forward to seeing the rest of the module.

I just have two pieces of feedback. 

1. Right at the start of the video, you can see the "Press escape to exit fullscreen" overlay that Chrome displays when you go full screen on Google Slides. I've been caught by that many a time 😁 
1. As this might be the first time the beginner developer is learning about themes, it might be beneficial for the learner to move the "Differentiate between a theme and a plugin" section to appear first, and then move into the possibilities, things to consider, and fundamental structure of a theme.

I realize this second suggestion means you'll have to re-record your "learning outcomes" slide, but I think that will help the flow of information for this lesson. 

I would also add that I should have picked this this earlier when you set up the learning outcomes, so I apologize for not seeing this sooner.

**Comment by jonathanbossenger** [comment]
Can I also just add that I ❤️ the extra design elements you've added to your slides, you're going to force me to up my slide game 😁

**Comment by cynthianorman** [comment]
Thanks so much for taking the time to provide feedback @jonathanbossenger

**Comment by ghost** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.
Great job.

**Comment by cynthianorman** [comment]
@jonathanbossenger I've uploaded this video to WordPress.tv and published it. We still need to add the transcript. Thank you!

**Comment by jonathanbossenger** [comment]
Video published to YouTube: https://youtu.be/OkKTFO8m8cQ

When you have a moment, please add the [Chapter Markers](https://make.wordpress.org/training/handbook/lessons/upload-your-video/#chapter-markers) for the video as a comment in this issue.

**Comment by cynthianorman** [comment]
@jonathanbossenger 
### YouTube Chapters
(0:04) Learning objectives
(0:25) Differentiate between a theme and a plugin
(0:43) Discover the possibilities of a WordPress theme
(1:47) How will your theme encourage engagement?
(2:01) What considerations will your theme have regarding accessibility?
(2:21) What functionality will your theme include?
(2:33) Explore the fundamental structure of a block, classic, and hybrid theme
(3:45) WordPress developer resources
