### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2087]
# Learning Objectives

Introduces how WordPress’ block templates system works and provides pathways for deeper learning.

The learning objectives are to:

1. Describe what theme templates are and how WordPress handles the final markup for you.
2. Understand how the templating system works.
3. List and describe the typical templates found within a theme.
4. Differentiate between templates and template parts.

# Relevant Links
https://developer.wordpress.org/themes/core-concepts/templates/
https://learn.wordpress.org/tutorial/wordpress-theme-template-tour/
https://learn.wordpress.org/tutorial/a-beginners-guide-to-the-wordpress-template-hierarchy/

# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for review
- [x] Lesson reviewed
- [x] Lesson video submitted and published to WPTV
- [x] Lesson created on Learn.WordPress.org 
- [x] Lesson video published to YouTube
- [x] Lesson on Learn.WordPress.org updated with YouTube video
- [x] Lesson published to Learn.WordPress.org

**Comment by cynthianorman** [comment]
This Beginner Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

https://youtu.be/PXI7KUJ5Q5A (unlisted)

**Comment by jonathanbossenger** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Thank you for showing the template in the code editor, what the block markup looks like, and how WordPress converts the block markup into rendered content. A very important and useful detail for new block theme developers. 

One question, from 2:30 - 2:40 you show the "Unavailable templates in the theme" annotation. Based on the spoken text during that time, I wasn't quite sure what this represented? From 2:40 onward, the voice and the visuals tied up and made sense.

**Comment by cynthianorman** [comment]
@jonathanbossenger thanks so much for your feedback!

I know what you mean with the annotation so I've removed it to hopefully reduce confusion.

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Another great overview and intro :-)
One suggestion/question: how about swapping the final slide to show the Template view of the Site Editor or even the theme directory structure in VS Code, instead of the template hierarchy chart?
I'm thinking that a "real-life" visualization of the theme structure could help people get a more concrete sense of the different parts.

**Comment by cynthianorman** [comment]
@ironnysh I really like your suggestion - thank you!

**Comment by cynthianorman** [comment]
@jonathanbossenger I've uploaded this video to WordPress.tv and published it. We still need to add the transcript. Thank you!

**Comment by jonathanbossenger** [comment]
Video published to YouTube: https://youtu.be/fLE6fhdttac

When you have a moment, please add the [Chapter Markers](https://make.wordpress.org/training/handbook/lessons/upload-your-video/#chapter-markers) for the video as a comment in this issue.

**Comment by cynthianorman** [comment]
@jonathanbossenger 

### Chapter Markers
(0:08) Learning objectives
(0:31) What are templates?
(1:57) How the templating system works
(2:58) Typical templates found within a theme 
(4:30) Differentiate between templates and template parts

**Comment by jonathanbossenger** [comment]
Thank you, added.
