### ISSUE TITLE
Custom Functionality

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2088]
# Details

- Content type: Lesson
- Content title: Custom functionality
- Topic description: This lesson dives into the theme’s functions file (functions.php) and how you can use it to add your own functionality to a theme.
- Audience: Developer
- Experience Level: Intermediate

# Learning Objectives

The learning objectives are to:

- Describe the purpose of a WordPress theme's functions.php file.
- Decide when to use a plugin instead of the functions.php file when developing a theme.
- List some common uses of the functions.php file for extending the functionality of WordPress.

# Relevant Links
https://developer.wordpress.org/themes/core-concepts/custom-functionality/
WordPress Hooks (https://github.com/WordPress/Learn/issues/2079)
Enqueuing CSS and JavaScript (https://github.com/WordPress/Learn/issues/2183)

**Comment by cynthianorman** [comment]
This Intermediate Theme Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under Guidelines for reviewing content. Thank you for your contribution! ✨

https://youtu.be/3woz5fovfkM

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

A helpful overview, @cynthianorman. I appreciate the highlight of _when_ to use a plugin instead of the functions.php.

At 2:28, the slide shows the soon-to-be-old design of the Theme Directory. It’s probably safe to replace it with the upcoming design that’s supposed to launch soon: https://wordpress.org/themes/?new-theme=1.

**Comment by cynthianorman** [comment]
@ironnysh ooooh I love your suggestion

**Comment by digitalchild** [comment]
Very clear overview. I agree that its great that you highlighted when to move your functionality into a plugin. 

## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

**Comment by cynthianorman** [comment]
Thanks so much for your input @digitalchild

**Comment by jonathanbossenger** [comment]
https://youtu.be/S6OVsyP4FYA

**Comment by cynthianorman** [comment]
@jonathanbossenger 

### YouTube chapters
(0:06) Learning objectives
(0:33) Describe the purpose of a WordPress theme's functions.php file
(2:25) Decide when to use a plugin instead of the functions.php file when developing a theme
(3:09) List some common uses of the functions.php file for extending the functionality of WordPress.
(4:21) Next steps

**Comment by cynthianorman** [comment]
//publish
