### ISSUE TITLE
Tutorial: Basic WordPress Settings 

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2099]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Tutorial 
- Content title: Basic WordPress Settings 
- Topic description: Introductory settings to get started.
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives
Settings in context 
    - Title / Tagline (and how they display in Google)
    - Setting your site’s timezone, and how this can affect your posts
    - Setting a home page vs. a posts page

### Automation Code
//tutorial

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/1ddaea48-f4d6-4f4b-a7cb-dd8e87cf3c14

**Comment by digitalchild** [comment]
A great overview @westnz however I think going a bit deep into how the home page settings work so quickly that it might be confusing for some new users. 

I would have liked to see discussion and permalinks touched on as these are important, especially permalinks which cause a lot of new users issues.

**Comment by devmuhib009** [comment]
Capitalize the thumbnail title will look good, I think. 
![image](https://github.com/WordPress/Learn/assets/142894870/378db5e4-d46e-4495-8664-4aa8b020f32d)

**Comment by westnz** [comment]
Thank you, @digitalchild and @devmuhib009!

Jamie, I think the home page display is important to address before someone starts building their templates and adding content. I do have a video specifically about Permalinks planned for a bit further down in the User learning pathway 🦾

**Comment by quitevisible** [comment]
@westnz great overview! I didn't catch any other errors or mistakes. Just a couple bits of feedback: 

Site Title and Tagline 

- you make a great point about the SEO value. Maybe include a slide of where the tagline shows up in the browser tab/URL address? A SERP visual might also work if it's a good one. 

- Is the tagline display dependent on theme support? If so, might be worth a mention.


Home Page - Static/Posts 

This one's always a tricky one for new users. 
- Consider making a point to creating the 'Home' and 'Blog' Pages first, prior to selecting them as static pages. Otherwise, they might be wondering how to select a page that doesn't exist.

That's it!

**Comment by SierraTR** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x ] Learning outcomes/objectives are clear.
- [x ] Technical concepts introduced in the content are accurate.
- [x ] The speed of demonstrations are easy to follow.
- [x ] The narration audio matches what is shown visually.
- [x ] Spelling and grammar are correct.
- [ x] Sound quality is consistent throughout the video.
- [x ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Wow, so many rabbit holes you could go down... With that in mind would it be an idea to, at the end of the video, point to follow-on lessons the continue the settings explanations?

I agree that it would be a good idea to mention creating the home and blog blank pages before choosing to set a static home page. Since this is a very basic tutorial for new users, that might not be implied and only a sample page is included with the clean install. You may also want to mention that if you select a static home page and do not select a blog page, then published posts will not appear anywhere on the website - unless the website menu includes links directly to category archive pages.  See...rabbit hole...

nice job, as usual.

**Comment by westnz** [comment]
Thank you for the helpful feedback @SierraTR and @quitevisible

**Comment by westnz** [comment]
Updated and published as part of the Beginner User learning pathway.
