### ISSUE TITLE
Feedback - Promotion of non-WP project commercial entity

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/Learn#2158]
_Psst, the `https://github.com/WordPress/gutenberg/issues` link in the leading, hidden comment in this Issue Template should probably be updated to `https://github.com/WordPress/Learn/issues`_

## Type of feedback

//dev

## Description

Following on from #1469, it appears that the Learn site is promoting a non-WordPress.org commercial entity.  Namely, InstaWP.com.  I have nothing against someone recommending or using InstaWP.com, but given that InstaWP.com is a commercial entity (that has competitors that aren't referenced alongside InstaWP.com as alternate options, eg. TasteWP.com) it feels improper to link out specifically to only InstaWP.com here.

I'll also note that the [WordPress.org Etiquette](https://wordpress.org/about/etiquette/) specifically states:
> Contributions to the WordPress open source project are for the benefit of the WordPress community as a whole, not specific businesses or individuals. All actions taken as a contributor should be made with the best interests of the community in mind.

Ironically, the [Open Source Basics and WordPress course](https://learn.wordpress.org/course/open-source-basics-and-wordpress/) actually references the above item as part of its lessons and quizzes.

There is a second option for `*Practice With WordPress Playground` but that asterisk references "Note that [WordPress Playground](https://developer.wordpress.org/playground/) is currently undergoing accessibility testing".  I'm not sure if there was criteria to list InstaWP.com, but without any additional context on that page it appears to promote InstaWP.com in place of other options.

I would suggest, without any additional context, that we consider removing the InstaWP.com button and leave the Playground one active.  If there was some sort of criteria to get InstaWP.com listed, then it would be helpful to link to that as another footnote so other services could consider submitting themselves and passing the criteria to be listed as `Practice` options as well?

## Step-by-step reproduction instructions (optional)

1. Go to a course like https://learn.wordpress.org/course/open-source-basics-and-wordpress/
2. Click on the `Practice on a private demo site` button
3. See that it opens https://app.instawp.io/

## Screenshots or screen recording (optional)

n/a

## Other information (optional)

n/a

**Comment by jonathanbossenger** [comment]
Hi @jeffpaul thanks for raising this concern.

The decision to include InstaWP was something that the training team decided on back in 2022, so I'm going to add this as a note for discussion in our next training team meeting. I will ask the team reps to report back here after the discussion.

**Comment by jeffpaul** [comment]
@jonathanbossenger thanks, will be good to understand what that context was in 2022 and how other services could get added in so that the project is not even appearing to favor one commercial service over others

**Comment by ghost** [comment]
Thank you. I will add it to the  Jan. 25, 2024 agenda. I am adding images of the specific areas under discussion from this course.  https://learn.wordpress.org/course/open-source-basics-and-wordpress/  The button that says "practice on a private demo site" goes to second image InstaWP login. 
![Screenshot 2024-01-24 100600](https://github.com/WordPress/Learn/assets/24979729/272c20d0-16fa-4272-9307-3f0370e7e978) 
![Screenshot 2024-01-24 100633](https://github.com/WordPress/Learn/assets/24979729/35e97b95-604b-4632-adc8-28fb791750e9)

**Comment by kaitohm** [comment]
This conversation was raised in today's team meeting: https://wordpress.slack.com/archives/C02RW657Q/p1706143415274789

**Comment by jonathanbossenger** [comment]
I did some digging, and it seems that at the time that we added InstaWP as an option, this was done because InstaWP was the only entity that reached out to us, and offered their services as an option. WP Playground was yet not an option, and it enhanced our offering to learners.

My suggestion is that we do one of two things:

1. Remove InstaWP and only offer free and open source options for testing/demo sites (in this case WP Playground is the only option I'm aware of)
2. Keep InstaWP, but include a way for other offerings (like TasteWP.com) to also be included. This could be similar to how the [hosting](https://wordpress.org/hosting/) page works. It would be up to the training team to decide on guidelines for reviewing/accepting services for inclusion and following that process during requests for inclusion.

**Comment by kaitohm** [comment]
I like @jonathanbossenger 's suggestions above. Because no platform is perfect, if we could link a few options, that would probably cater to the most needs learners may have.

Whether we take options 1 or 2 suggested by Jonathan, I believe we should make WordPress Playground the predominant option, as that is provided in-house. So, the sidebar should look like this:
![Screenshot 2024-01-25 at 10 18 28](https://github.com/WordPress/Learn/assets/49054298/29607f73-8693-4a5d-969b-ec6801e4a0e3)

**Comment by jonathanbossenger** [comment]
Noting that PhpStorm isn't a good example, but I know you just used that for some additional text 😁

**Comment by ghost** [comment]
I agree with removing InstaWP from the button link. I do like Ben's suggestion in the image if that adheres to our guidelines.

**Comment by jonathanbossenger** [comment]
I just checked out the link we're using for playground, and it turns out that link has also changed, and the playground has moved to https://wordpress.org/playground/, so this will be a good idea to update that link at the same time.

**Comment by jonathanbossenger** [comment]
Circling back to close this loop

- InstaWP has been removed as a current option on all Learn.WordPress.org content. We are not opposed to including InstaWP, TasteWP and others as options, but we need a process of vetting these applications.
- All sidebar buttons have been updated to point to WordPress Playground, with the text "Practice with WordPress Playground"
