### ISSUE TITLE
Tutorial: How to backup your site

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2175]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan):
- Content title: How to backup your site
- Topic description: Ways to backup your site
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner-Intermediate

# Learning Objectives

Backup your site using a plugin or with your host

# Related Resources and Other Notes

### Automation Code

//tutorial

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/6fe967d7-8cf4-454e-b37d-d70d35c976c5

**Comment by askdesign** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [ x] Learning outcomes/objectives are clear.
- [ x] Technical concepts introduced in the content are accurate.
- [ x] The speed of demonstrations are easy to follow.
- [ x] The narration audio matches what is shown visually.
- [ x] Spelling and grammar are correct.
- [ x] Sound quality is consistent throughout the video.
- [ x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [  ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

Wes, this is succinct and clear. I like how you point out the restore option. As you mention, a manual restore is more complex and appropriate for another tutorial. Some highlights that I especially appreciate:
1:34 - Describing the differences between the Filesystem and Database backups
2:27 - On-demand backup option is really good for users to know; great how you refer to it later in the plugin section.

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great tutorial, @westnz! Love the slides (especially the poor soul in the intro segment 😂), the flow, and the fact that you mention ALL available options.

**Comment by westnz** [comment]
Thank you for the reviews @ironnysh and @askdesign  😃

**Comment by ghost** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [ ] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

1:44 the word website in the last line of text is misspelled
Great job. I wish you would have clarified that the Updraft plugin you need to pick a remote storage for your backups and that those settings of daily and 2 backups are connected to the remote storage setup. Even the on-demand backup too.

**Comment by SierraTR** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [ x] Learning outcomes/objectives are clear.
- [x ] Technical concepts introduced in the content are accurate.
- [x ] The speed of demonstrations are easy to follow.
- [ x] The narration audio matches what is shown visually.
- [ ] Spelling and grammar are correct.
- [x ] Sound quality is consistent throughout the video.
- [x ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Another nice job, Wes.
I agree with Laura's comments above - spelling error on the slide at 1:44. I also agree that you should mention that backup best practices includes storing your backups somewhere other than the hosting account, such as Dropbox, Google Drive, etc. so that hosting account problems don't result in losing both your website and all your backups.

Moved to Preparing to Publish

**Comment by westnz** [comment]
Many thanks, @SierraTR and @lada7042

**Comment by westnz** [comment]
Updated and published as part of the Beginner user learning pathway in Sensei.
