### ISSUE TITLE
Lesson: Creating custom post types

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2215]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Tutorial
- Content title: Creating custom post types 
- Topic description: Using custom Post Types
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate 

# Learning Objectives

Using a plugin to create a custom post type
Understanding why you would use a custom post type

# Related Resources and Other Notes

### Automation Code

//tutorial

**Comment by westnz** [comment]
@SierraTR will write the script, and @westnz will complete the recording.

**Comment by westnz** [comment]
Hi @SierraTR 👋 
Have you started with the script for this tutorial?

**Comment by westnz** [comment]
Hey @SierraTR 
Just checking in to see when you will be able to start working on the script for this lesson?

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/70b9b3fa-7891-4ce9-a5e0-c0ae4fca687b

**Comment by hazeldrio** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.
1. Consider renaming the video to "Lesson: Creating custom post types and taxonomies"
2. Has the concept "What is: Taxonomy" been covered in the beginner or intermediate track? If so, then I think this video is perfect. If it hasn't been covered then I think there should be a separate video that gives a little more information about what is a taxonomy and what’s the difference between categories and tags.

**Comment by westnz** [comment]
Thank you for the helpful feedback @hazeldrio

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great work, @westnz and @SierraTR! Very thorough and easy to follow.

I was missing one thing: a brief explanation as to _why_ you would “go to all this trouble” instead of just creating a custom template. Something like this callout in the [Plugin Handbook](https://developer.wordpress.org/plugins/post-types/registering-custom-post-types/) can do the job:

![Image](https://github.com/WordPress/Learn/assets/63248335/f81eae09-33e6-436f-91b4-0d195a16431b)

**Comment by westnz** [comment]
Thank you for the feedback, @hazeldrio and @ironnysh

**Comment by westnz** [comment]
//published
