### ISSUE TITLE
Add `Review Notes` panel to workshop post type

### ISSUE THREAD

**Issue by iandunn** [WordPress/Learn#223]
> Workshop Reviewers: When reviewing Meetup and WordCamp applications, Community Deputies have a custom meta box to share vetting notes. Sometimes this information is confidential, especially when a proposed application/applicant may not meet the program guidelines. The current workflow for evaluating workshop submissions is very similar to this process, and the Learn site would benefit from a role for workshop reviewers to have access to a confidential meta box for communicating review notes with one another.
>
> https://make.wordpress.org/training/2021/05/27/proposal-adding-custom-user-roles-to-learn-wordpress/

#220 is tracking the user role functionality, which can be done independent of adding notes. It will need to be done first, though.

**Comment by coreymckrill** [comment]
I'm working on a dotorg plugin for adding "internal notes" to posts that should be able to address this issue and the [moderation needs](https://github.com/WordPress/pattern-directory/issues/105) of the pattern directory.

**Comment by coreymckrill** [comment]
Update: the [Internal Notes plugin](https://github.com/WordPress/wporg-internal-notes) is now active on the Learn site, and should be enabled for workshops. Since #220 isn't done yet, anyone who is an editor or higher can read the notes. Here's a bit about how it works:

There's a new sidebar in the block editor where the notes are displayed and managed. The sidebar can be accessed by clicking the Note icon in the upper right:

![sidebar-button](https://user-images.githubusercontent.com/916023/133507020-81379820-f8fc-4e02-ad6c-2e1289b2d7ff.jpg)

The number badge next to the Note icon displays how many internal notes there are.

Adding new notes should be fairly self-explanatory. Click the Add Note button and fill out the form:

![note-form](https://user-images.githubusercontent.com/916023/133507253-da706f4f-9c9c-4be9-9262-aaeef3c70668.jpg)

Notes are displayed with the newest ones at the top. Notes can also be deleted by clicking the Trash icon that appears when a note is hovered over or focused. There isn't currently a way to edit an existing note.

**Comment by hlashbrooke** [comment]
This looks great! I'm very happy with how this works.

This looks complete to me, but let me know if there's more work that needs to be done before we can close the issue.

**Comment by coreymckrill** [comment]
This will get closed when #244 merges.
