### ISSUE TITLE
Feedback - A Logged in user viewing a Course Lesson triggers the Welcome to Course email

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2261]
## Type of feedback

//dev

## Description

It has [been reported in Slack](https://wordpress.slack.com/archives/C02RW657Q/p1708811314854269) that a WordPress.org user who viewed a course lesson was automatically sent the "Welcome to Course" email

**Comment by jonathanbossenger** [comment]
@adamwoodnz @pkevan is there a way that we can either review logs or test this somehow? This is not something testable via the local development environment, as far as I can tell.

**Comment by pkevan** [comment]
i'm not sure what logs you are expecting to view, but I doubt there will be anything of use since logs are usually errors/warnings etc.

I was however able to reproduce the bug, by visiting https://learn.wordpress.org/quiz/open-source-principle-3-egoless-participation-2-3/ I got an email, I suspect it's probably something to do with being half way through a lesson, but that's a guess.

**Comment by jonathanbossenger** [comment]
> i'm not sure what logs you are expecting to view, but I doubt there will be anything of use since logs are usually errors/warnings etc.

I don't know what I don't know, so was mostly curious if there was anything. All good if not.

> I was however able to reproduce the bug, by visiting https://learn.wordpress.org/quiz/open-source-principle-3-egoless-participation-2-3/ I got an email, I suspect it's probably something to do with being half way through a lesson, but that's a guess.

Interesting. I have not been able to replicate the issue myself. I will see if I can ping someone from Sensei to help us debug.

**Comment by adamwoodnz** [comment]
This issue has been dormant for a while, can we close?

**Comment by jonathanbossenger** [comment]
Yup, happy to close.
