### ISSUE TITLE
Block Functionality

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2263]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):
- Content title: 
- Topic description: 
- Audience (User, Developer, Designer, Contributor, etc.):
- Experience Level (Beginner, Intermediate, Advanced, Any):

# Learning Objectives

- Describe how the Edit component and save function are at the core of the block functionality
- Implement the block's functionality in the editor by updating the Edit component
- Use the block's save function to render the output to be saved

# Related Resources and Other Notes

**Comment by jonathanbossenger** [comment]
//lesson

**Comment by jonathanbossenger** [comment]
https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/introduction-to-wordpress-blocks/04-block-functionality.md

**Comment by jonathanbossenger** [comment]
https://github.com/WordPress/Learn/assets/180629/e4273786-080b-45b0-b45d-378cfbcde2e5

Video for review

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [ ] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great tutorial, @jonathanbossenger--informative and easy to understand.

I had difficulty watching the video (I tried multiple broswers). Since this happened to other people with a few other videos, it might be helpful to add an alternative link.

Other than that, there were a bunch of audio problems:
- At 3:10 and 3:14 there are repetitions ["For now, update the component to return..."](https://github.com/jonathanbossenger/wp-content/blob/deecad1fb9d07a18f5616eb27e603e21f3b906f0/developer-learning-pathway/07-introduction-to-wordpress-blocks/04-block-functionality.md?plain=1#L65).
- This happens again at 4:01, with ["you probably don't want to hardcode..."](https://github.com/jonathanbossenger/wp-content/blob/deecad1fb9d07a18f5616eb27e603e21f3b906f0/developer-learning-pathway/07-introduction-to-wordpress-blocks/04-block-functionality.md?plain=1#L83).
- There's a sound issue at 4:09 and again at 5:30.
- There's a silence in 6:22-6:31, and then you start with a variation of the same sentence. This happens again a bit later and only starts "clean" at 6:55.
- There are a few "false starts" again at 7:35 until 7:46, and a few seconds later it happens again with another sentence.
- and again at 8:29 and at 9:18-9:19 :-)
- It seems like there's an outro missing

**Comment by jonathanbossenger** [comment]
https://github.com/WordPress/Learn/assets/180629/d54fa14e-2c97-43d5-881a-7b83c580d0ce

Thanks for the review @ironnysh. It seems that some of my edits either didn't save, or exported incorrectly. So I've reexported the video, and the bugs should now be fixed. 

```
I had difficulty watching the video (I tried multiple broswers). Since this happened to other people with a few other videos, it might be helpful to add an alternative link.
```

It was reported to me that some of the other videos were running at a very low framerate. This seems to also have been fixed, but let me know if you see it with newer videos.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/03/28/block-functionality/

**Comment by jonathanbossenger** [comment]
https://youtu.be/P3pMxCCIxeg

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/block-functionality/
