### ISSUE TITLE
Tutorial : How to Test WordPress Beta Release?

### ISSUE THREAD

**Issue by devmuhib009** [WordPress/Learn#2269]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): **Tutorial**
- Content title: **How to Test WordPress Beta Release?**
- Topic description: Before any major WordPress version we get lots of beta version that needs testing. But most of the new contributors don't know how to test beta. It's an easy and powerful way to contribute in WordPress community. I always get questions from new contributors that what to test? where to test? and why should I test? That's why I decided to create this tutorial.
- Audience (User, Developer, Designer, Contributor, etc.): **Contributor**
- Experience Level (Beginner, Intermediate, Advanced, Any): **Beginner**

# Learning Objectives

This demonstration video will help to learn WordPress beta testing step by step.
# Related Resources and Other Notes
Here is the draft video I created. Please review the video and share your feedback.
https://youtu.be/yRzEZ9q9CeU

**Comment by devmuhib009** [comment]
//tutorial

**Comment by cynthianorman** [comment]
This tutorial is wonderful! I've gone through the process before and I feel you've done a very comprehensive job here. Well done!

**Comment by devmuhib009** [comment]
Thanks @cynthianorman for your kind feedback. As new content creator your feedback means a lot to me and obviously it will inspire me. ❤️

**Comment by backpocketACE** [comment]
Thanks for putting the tutorial together. 

- [x ] Learning outcomes/objectives are clear.
- [x ] Technical concepts introduced in the content are accurate.
- [x ] The speed of demonstrations is easy to follow.
- [x ] The narration audio matches what is shown visually.
- [x ] Spelling and grammar are correct.
- [x ] Sound quality is consistent throughout the video.
- [x ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by devmuhib009** [comment]
Thanks @JunebackpocketACE for your valuable feedback.

**Comment by westnz** [comment]
Hey @devmuhib009 
This type of lesson could possibly form part of a future contributor learning pathway. 😃

**Comment by devmuhib009** [comment]
As a novice content creator, I wanted to create the video first and then create the topic issue. Surprisingly, it  was already in the learning pathway which was a lesson for me. Next time I will check the vetted topics first and then I will start making videos. 😊

**Comment by kaitohm** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

---
This is a great Tutorial, and something I feel we're missing on Learn. So, thank you for creating it! 👏  Your audio quality was great, speed wasn't too fast, and it was easy to follow.

I have just a few suggestions to improve the video further.

When recommending plugins for people to use, if it isn't a plugin maintained by the general WordPress community, then [we should be mentioning some alternatives](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/#guidelines) so that it doesn't seem like we're endorsing a single plugin. At 3:00, you mention "Core Rollback". We should improve this further by saying something like; "There are a few plugins you can use to roll back the WordPress version of a site - such as Core Rollback and WP Downgrade. In this video, we'll demonstrate by using Core Rollback."

At 6:10, you mention "I think it's really easy." I would personally avoid saying something is easy, as we really don't know whether that is going to be easy for all users. If a user tries, but fails, they might feel bad that they couldn't complete an "easy" task. A better phrase to use might be something like "Anyone can participate in core release testing" or "Now you can try testing a core release, too!"

My final comment is about 6:15 where you say "If you find any difficulties, feel free to ask me." The person watching this video doesn't know who "me" is, or how they can reach out. A better approach might be to say, "If you have any difficulties, feel free to ask for help in the core Slack channel, or in the WordPress support forums."

**Comment by devmuhib009** [comment]
@bsanevans Thanks for nice suggestions. I'll follow your suggestions to improve the video quality. 😊

**Comment by devmuhib009** [comment]
@bsanevans I just modified the video with your suggestions. Please take a look again and share your feedback.

https://youtu.be/UMjhK2-knf0

**Comment by kaitohm** [comment]
Thanks for making those changes 🙌 I think this video is ready to publish now.

**Comment by devmuhib009** [comment]
Tutorial published here: https://wordpress.tv/2024/03/08/how-to-test-wordpress-beta-release/
Working on subtitle and Learn WordPress Post.

**Comment by devmuhib009** [comment]
Thanks everyone for helping me in various ways. I just published the tutorial here. ❤️😍❤️
https://learn.wordpress.org/tutorial/how-to-test-wordpress-beta-release/
