### ISSUE TITLE
Advanced WordPress block layouts

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2288]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):
- Content title:  Use advanced layouts (columns, rows, groups, etc.) in the post editor and Site Editor.
- Topic description: 
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate

# Learning Objectives

# Related Resources and Other Notes

### Automation Code

//lesson

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/9b5ca15c-8623-4211-be7e-c30ef56e167b

**Comment by quitevisible** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)). 

-----  

### Feedback. 

@westnz well put together. Some thoughts...  

- Using 'shift+enter' to drop to the next line in the same paragraph/heading was a nice trick! 
- In the 2nd Cover example, you may want to consider actually clicking on the View menu icon to preview the page in desktop, tablet, or mobile. 
- Only minor issue I noticed was the top padding or margin seemed to be just a wee off, for your Cover/Columns example. You can see it in the last frame of the lesson. 

Otherwise, good stuff!

**Comment by westnz** [comment]
Thanks for the suggestions and for picking up those things! 🦾 @quitevisible

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great tutorial, @westnz. I love the use of designs from the Pattern directory as learning opportunities!

**Comment by westnz** [comment]
Thank you @ironnysh 🙏

**Comment by westnz** [comment]
//published
