### ISSUE TITLE
SEO strategies

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2291]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):
- Content title: SEO optimization
- Topic description:  
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate

# Learning Objectives

# Related Resources and Other Notes

**Comment by digitalchild** [comment]
//lesson

**Comment by westnz** [comment]
Script: https://docs.google.com/document/d/1VIukXllfE8cCc8IyettO4iuyj9j3IoKkKzwa45I4qTA/edit

**Comment by patelamitn** [comment]
Thanks @westnz 
I have added few suggestions and changes.

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/ad62817b-5a7c-4084-befd-857909b77a65

**Comment by showravhasan1** [comment]
Hi, I would like to review the content and help. Can you please let me know how can I start contributing on this?

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Suggestion: remove item number 6 (**Implement HTTPS for Security**, at 7:37):
1. Browsers have been blocking non-https sites for a few years. At this point, it's not “worth exploring” but rather a must :-)
2. As the title of this section states, it's not an _SEO recommendation_. Describing this as an SEO tip (something that “search engines prefer”) is overly simplistic.

**Comment by westnz** [comment]
Thank you very much for reviewing @ironnysh 

Here are the [guidelines](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) for reviewing @showravhasan1

**Comment by showravhasan1** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Solid content. 

Suggestions: 
- Guest Posting is the known term at 6:32 instead of Guest Blogging since everyone widely uses the term. 
- Search Engine does not penalize AI content if it is good, as mentioned at 8:32. Google Also mentioned this in their [major update](https://developers.google.com/search/blog/2023/02/google-search-and-ai-content). While it is always recommended to use Human writers, penalization is argumentative.

**Comment by patelamitn** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).


Overall it is explained very well and easy to understand.

**Comment by pricelessopoku** [comment]
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great content. If possible, could we include the importance of using H1 and H2 tags in the website content?

**Comment by westnz** [comment]
Thank you all for the helpful feedback!!  ⭐ 

@pricelessopoku, There is a whole lesson about using headings for SEO and accessibility in the beginner user learning pathway 👍

**Comment by westnz** [comment]
//published
