### ISSUE TITLE
Essential security plugin features and settings 

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2296]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):
- Content title:  Security plugins
- Topic description:  mention a variety of options and why they’re helpful. a)Ask a host for SSL Certificates (what it is, how it works, why they want one), b) Add your own SSL Certificate etc.
- Audience (User, Developer, Designer, Contributor, etc.): User 
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate

# Learning Objectives

# Related Resources and Other Notes

**Comment by digitalchild** [comment]
//lesson

**Comment by gmt-2** [comment]
Top Security Plugins:
-Wordfence
-Jetpack
-All-In-One Security
-Solid Security (Former iThemes Security)

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/7ee0d836-e2d8-4612-abc5-c3fbd748c0bc

**Comment by digitalchild** [comment]
This is a good overview, I would consider mentioning that good security should also be backed by good backup strategy in case of an incident, you can quickly recover from your backups. 

There maybe should be a mention that some hosting providers provide server level security such as malware scanning or PatchStack security included with your managed host.

**Comment by westnz** [comment]
Thank you very much @digitalchild 👍

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

That's a solid overview of the essentials.

1. At 1:31, there's something that looks like a little hovering icon over the slide. Not sure if it's intentional :-)
2. The topic description [above](https://github.com/WordPress/Learn/issues/2296#issue-2172878008) mentions SSL, which isn't covered in the lesson:
  > Topic description: a)Ask a host for SSL Certificates (what it is, how it works, why they want one), b) Add your own SSL Certificate etc.

Would this be presented in a separate lesson?

**Comment by westnz** [comment]
Good catch, @ironnysh 
Thank you for the review

**Comment by westnz** [comment]
//published
