### ISSUE TITLE
Creating a Child Theme - Understand their function

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2297]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):
- Content title: Creating a Child Theme - Understand their function
- Topic description: 
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate

# Learning Objectives

# Related Resources and Other Notes

**Comment by digitalchild** [comment]
//lesson

**Comment by westnz** [comment]
Not necessary for users:
[Do I still need a child theme](https://fullsiteediting.com/lessons/child-themes/#h-do-i-still-need-a-child-theme)?
Child themes are traditionally used to make minor customizations to a theme and protect those changes from being replaced by a theme update.
Block themes are highly customizable and essentially solve these problems. Themes that include global style variations can offer many designs in one theme.
You can also use the Site Editor to make structural changes to templates and add new templates without code. When you edit your site in the Site Editor, WordPress saves your changes to the database, so you don’t need to worry about theme updates removing your changes. For these reasons, the need to create a child theme is much lower than a few years ago.
– Whether you need a child theme depends on the changes you want to make.
If you change theme.json, HTML, CSS, PHP, or JavaScript files directly, you still need to create a child theme because these files are not protected when you install a theme update.
There are also settings and styles in theme.json that you can not remove through the WordPress interface. In this case, you also want to create a child theme and add your custom theme.json.
