### ISSUE TITLE
Understand where your files live

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2310]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Understand where your files live
- Topic description: 
Look at your server via an FTP app. 
Gain a basic understanding of the file structure (wp-content)
Explain how to download/upload files (relevant for troubleshooting and backup)
File vs database

- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Advanced

# Related Resources and Other Notes

**Comment by digitalchild** [comment]
//lessons

**Comment by westnz** [comment]
[Script](https://docs.google.com/document/d/1dXcCBGT3veoUIDZozYlWyn7S_5MlhBjquTUpU2ZdnGs/edit#heading=h.12oul4gn88go) by @ironnysh. ⭐

**Comment by agiljulio** [comment]
Hi team, I would like to be involved in editing this video 👍

**Comment by westnz** [comment]
Thank you @agiljulio 
I have sent through the voice recording via Slack, and you have access to the script + screenshots.

**Comment by agiljulio** [comment]
Hi @westnz , here's [the video](https://drive.google.com/file/d/1PqC8lR2PVztJ366Sud6LAejjZNushFxd/view?usp=sharing) I’ve edited, thank you 🙏

**Comment by rfluethi** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [ ] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

I like the video. It is clearly structured and covers the most important file operations. The short section on *wp-config.php* piques interest in exploring it further without being overwhelming.

However, what I couldn't fully grasp is the connection to the cloud. I understand the statements and the problem, but I'm not entirely sure how this relates to file storage.

I also appreciate that not every slide has a white background. The dot pattern on the blue slides is subtle and appealing.

Perhaps the video size could be reduced using a tool like HandBrake, as 220 MB is a bit large. However, I'm confident that this will be addressed in the final version.

**Slide "Learning Objectives" at 0:00:13**:
Although I don't usually find text slides to be optimal, the spoken text here is very well synchronized with the appearing text, giving the impression that one can easily follow along. Using graphics instead of text could have the advantage of not needing to read along, allowing full focus on the spoken content. Additionally, graphics could have nicely introduced the individual chapters, giving the video a clearer structure.

**Slide at 0:00:27**:
Wouldn't it be more fitting if the contrast color, besides black, was the blue from the previous slide? The animation of the icons is excellent—I'll definitely try to incorporate that as well.

**Text overlay at 0:00:43**:
Is this text really necessary? I find it a bit distracting. Shouldn't the text start with a capital letter?

**Screenshot at 0:01:25**:
It's well done that the window appears on the blue background, which creates a consistent impression.

**Text at 0:03:16**:
Original: "... selected and click the delete Button on the top menu"
Suggestion: "... select the ZIP file and click the delete Button on the top menu"
This ensures that no one mistakenly deletes the directory.

**Slide at 0:03:55**:
Shouldn't the directories "Plugins" or "Themes" be shown here, or mentioned in the text that the zipped files need to be uploaded to the appropriate directories?

**Slide at 0:04:24**:
I find the color combination of the blue "wp-config.php" icon not very fitting with the turquoise of the beautifully animated icons. Wouldn't it be nicer to either use the same color or a completely different one?

**Slide "Conclusion" at 0:06:33**:
This slide doesn't work optimally for me. While the message is good, there is a lot of text being read aloud. It gives me the feeling that someone thinks I can't read, and it also hinders reading, as the same text is being spoken simultaneously.

**Summary, Thanks**:
For me, a summary of the chapters and a thank you for the attention are missing. Without these, it feels somewhat unfinished and a bit impolite.

Overall, it is a very well-done video that, in my opinion, can be published as is.

**Comment by westnz** [comment]
Hey @rfluethi 
Thank you for the thorough feedback and suggestions! 

Great work @agiljulio! 

My review:
- I agree that we need to update the intro and remove the reference to the cloud meme. I will re-record "In this lesson we will explore the question..." We also need to add the thumbnail at the start of the lesson, which can replace the slide with the two questions.
- I suggest removing the text 'the standard way...' below File Transfer Protocol 
- 4:03 Let's show the wp-config.php icon from the start and remove the slide with the words 'WordPress configuration file.'
- I agree with comment above 'Slide at 0:04:24: I find the color combination of the blue "wp-config.php" icon not very fitting with the turquoise of the beautifully animated icons. Wouldn't it be nicer to either use the same color or a completely different one?'
- 4:44 - 4:50 Can you add an arrow to 'Settings'. I can't see the annotation/rectangle clearly.
- 6: 20 - 6:33 Agreed that the conclusion should not have words - can we add some graphics please.

**Comment by helenaartmann** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [X] Learning outcomes/objectives are clear.
- [X] Technical concepts introduced in the content are accurate.
- [X] The speed of demonstrations is easy to follow.
- [X] The narration audio matches what is shown visually.
- [X] Spelling and grammar are correct.
- [X] Sound quality is consistent throughout the video.
- [X] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [X] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

I liked this video; the graphics, and narration matched the video perfectly. It's fun to watch and informative. I agree with some of the comments above and have no new comments to add.

**Comment by westnz** [comment]
Thank you, @helenaartmann

**Comment by agiljulio** [comment]
Hi, thank you for the input 🙏 here's the updated [video](https://drive.google.com/file/d/1PqC8lR2PVztJ366Sud6LAejjZNushFxd/view?usp=sharing)

**Comment by westnz** [comment]
Hey @agiljulio 
Please remember to also cut out the words: "This may be too simplistic, but it’s the foundation of today’s lesson:"

**Comment by agiljulio** [comment]
@westnz apologies for missing that part and forgetting to cut it out 🙏 here’s the [updated version](https://drive.google.com/file/d/1PqC8lR2PVztJ366Sud6LAejjZNushFxd/view?usp=sharing), thank you

**Comment by westnz** [comment]
A few more tweaks:
- 00:27 Can you change the color of the graphics to the blue in the slides?
- 00:41 Remove the text below File Transfer Protocol: "the standard way to transfer files between computers, such as your device and your hosting company’s server."
- I will send the new voice clip for this Text at 0:03:16:
Original: "... selected and click the delete Button on the top menu"
Suggestion: "... select the ZIP file and click the delete Button on the top menu"
- 4:15 The transition and colors are off. Can we fix that? Maybe you could use a different transition type.
- 4:24 Can we change the colors to the blue in the slides? 
- Can you add 3 seconds at the end of the video to make sure it doesn't cut off so quickly? 

Thanks Agil, almost there.

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/50248059-def1-4428-8379-ad601d7d45a7

**Comment by westnz** [comment]
Great work @agiljulio! Thank you for the updates.

Thank you to all the reviewers.  I am going to go ahead and publish the lesson.

**Comment by westnz** [comment]
//published

**Comment by westnz** [comment]
//published
