### ISSUE TITLE
Meeting Agenda March 28, 2024

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#2350]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @bsanevans ._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- March 28 – [@pooja9712](https://profiles.wordpress.org/pooja9712/)
- April 4 – [@Sumit Singh](https://profiles.wordpress.org/sumitsingh/)
- April 11 – [@Tapan](https://profiles.wordpress.org/voboghure/)
- April 18 – [@Arun Sharma
](https://profiles.wordpress.org/dextorlobo/)
**2. Looking for feedback**

- item 1
- item 2

**3. Looking for volunteers**

- item 1
- item 2

**4. Other news**

- [The WordPress 6.5 release has been delayed by 1 week](https://make.wordpress.org/core/2024/03/25/wordpress-6-5-release-delayed-1-week/), and is now scheduled for April 2nd
- item 2

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.

## 3. Contribution Acknowledgement

- Badges awarded: none
- Props: Thanks to those testing translation plugins for Learn

## 4. Project updates

- [Translation plugins for Learn](https://github.com/WordPress/Learn/issues/2231)
  - @jonathanbossenger Could you prepare an update on where this is at? 🙇‍♂️ 
- Learning Pathways and site redesign
  - @bsanevans will leave an update here before the meeting

## 5. Faculty Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other Faculty or Training Team members help you in some way?

## 6. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by jonathanbossenger** [comment]
@bsanevans Update on translation plugin testing. 

The following plugins were tested by the following contributors

- [Polylang](https://wordpress.org/plugins/polylang/) - @cynthianorman
- [WPML](https://wpml.org/) - @unprintedch
- [TranslatePress](https://wordpress.org/plugins/translatepress-multilingual) - @sareiodata

Here is a breakdown of the requirements tested

| Requirement                                                                                         | Polylang | WPML                 | TranslatePress |
|-----------------------------------------------------------------------------------------------------|----------|----------------------|----------------|
| Language selector does not show as country flags.                                                   | x        | x                    | x              |
| Languages can be changed without needing to log in to one's WordPress.org account.                  | x        | x                    | x              |
| Once a language is selected, it is applied globally.                                                | x        | x                    | x              |
| Content of the selected language is shown above non-translated content.                             |          | x                    |                |
| English content is still shown where translations don't exist.                                      | x        | x                    | x              |
|                                                                                                     |          |                      |                |
| Translators do not have permission to create or publish new content.                                | x        | x                    | x              |
| Translators have permission to both translate any content, and review content translated by others. | x        | x                    | x              |
| A flow can be implemented where translations must be approved (reviewed) before published.          | x        | x                    |                |
| Sensei content types can be translated in the same way as native post types.                        | x        |                      | x              |
| Taxonomies can be translated.                                                                       | x        | x                    | x              |
| Translated content is indexed and searchable by Jetpack Search.                                     | x        | needs deeper testing | needs deeper testing               |

General note on Jetpack Search: If it's a external index like the Google search that's found on other parts of wordpress.org, it might work. If it relies on WordPress internally for querying content and sending it to Jetpack servers, it might not. We can only really test this on the live site. 

Additional notes from testers (see linked tickets for testing notes):

[Polylang](https://github.com/WordPress/Learn/issues/2284): 

- It's important to know that we essentially build a separate set of pages/posts/taxonomies and corresponding menu for each language.
- For this reason, we would need to create the copied English page/post and designate it as French (for example) otherwise I don't believe this will work out for us. In other words, the copied English page/post would act as a placeholder until a translator would contribute the translation.

[WPML](https://github.com/WordPress/Learn/issues/2338):

- There is no free version of WPML. 
- In short, the fact is that WPML is rather complete in terms of functionality.
- BUT! It adds much complexity and is sometime capricious, prompt to bugs and leads to frustration.
- There is no (in our experience) other real viable alternative except polylang which is not as complete in terms of features.

[TranslatePress](https://github.com/WordPress/Learn/issues/2339)

- The free version doesn't allow for more than 1 language
- The requirement "Translators do not have permission to create or publish new content" is available in the paid version.
- If you have questions or want a paid version to test out I would be happy to help. (we can create a perpetual license, so you get updates moving forward to the paid version). The paid version is just an addon.
