### ISSUE TITLE
Meeting Agenda April 4, 2024

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#2362]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @Piyopiyo-Kitsune._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- April 4 – [@Sumit Singh](https://profiles.wordpress.org/sumitsingh/)
- April 11 – [@Tapan](https://profiles.wordpress.org/voboghure/)
- April 18 – [@Arun Sharma](https://profiles.wordpress.org/dextorlobo/)
- April 25 -- need volunteer

**2. Looking for feedback**

- Is anyone going to speak about Learn WordPress or the Training Team this month? Or applying to speak?
- WordCamp Asia 2024 Contributor check-in

**3. Looking for volunteers**

- item 1
- item 2

**4. Updates from last week's dev-squad triage session**

Dev-squad meeting notes

- 1 PR draft and no new PRs.

New Issues

- 1 content issue was mislabelled as awaiting triage and added by the GitHub bot to the Learn WP Website Development Project board
- 1 new issue related to Gujarati Local Content Linked to Docs File instead of the Gujarati localized site.
- 1 Style updates for sensei to fix radio buttons and a PR was created ready for review for next session.
- Testing of wp-now PR has started

Muhibul Hague has accepted to host dev squad triage on the 11th of April.

**5. Other news**

- The [Learn WordPress Newsletter – April 2024](https://learn.wordpress.org/learn-wordpress-newsletter-april-2024/) is now published
- Our March team update is now available for review in the [Training Team Update – March 2024](https://make.wordpress.org/updates/2024/04/03/training-team-update-march-2024/) post
- A new handbook section on the interim co-rep process is now up!
- Ben and Destiny will be away at a meetup next week

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
  - We have 19 issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
  - We have 19 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.  
- We have 1 issue that requires vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
  - We have 15 issues that need a look

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
  - We have 16 issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: [@harishanker](https://profiles.wordpress.org/harishanker/)
- Props: 

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
  - [We've received some recent feedback and answers](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4202) about the latest design
  - @bsanevans anything else to share?
- https://github.com/WordPress/Learn/issues/2231
  - @jonathanbossenger Could you prepare an update on where this is at? 🙇‍♂️

## 5. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by jonathanbossenger** [comment]
#2231 High level update:

- The team would like to prioritize using GPL-compliant plugins, so at the moment we've highlighted [Polylang](https://github.com/WordPress/Learn/issues/2284) and [TranslatePress](https://github.com/WordPress/Learn/issues/2339) as two possible options
- TranslatePress seems to be the [better option](https://github.com/WordPress/Learn/issues/2231#issuecomment-2026468614) between the two.
- Ben raised this question with members of the meta team who are working on the Learn redesign, who indicated we would need to first have a more public community conversation around it, as it would mean installing the plugin on the .org infrastructure. 

Our next steps will be to hold that public discussion with Meta.

**Comment by jonathanbossenger** [comment]
@digitalchild would you be able to add a summary of last week's dev squad session?

**Comment by digitalchild** [comment]
@jonathanbossenger  

Dev-squad meeting notes

- 1 PR draft and no new PRs.

New Issues

- 1 content issue was mislabelled as awaiting triage and added by the GitHub bot to the Learn WP Website Development Project board
- 1 new issue related to Gujarati Local Content Linked to Docs File instead of the Gujarati localized site.
- 1 Style updates for sensei to fix radio buttons and a PR was created ready for review for next session.
- Testing of wp-now PR has started 

Muhibul Hague has accepted to host dev squad triage on the 11th of April.

**Comment by felixarntz** [comment]
@Piyopiyo-Kitsune I have a request for a topic to potentially discuss in this meeting.

Background is that members of the WordPress Performance Team (including myself) have been working on an introduction to gathering WordPress performance data in the field. This is provided in [this Colab](https://colab.research.google.com/drive/1TmbJhSBuM-gTHA_E_W96pSjraQkFYpyi), as the Colab format is a great fit for this kind of content, since it allows providing BigQuery queries that can be run directly inside of it, and the results can be presented alongside the queries.

I have a [Make Core post draft (public preview)](https://make.wordpress.org/core/?p=112332&preview=1&_ppp=5103a773bb) where I'm planning to share this Colab more broadly with the core developer audience, as gathering such data can be very valuable in assessing the success of a new core feature.

That said, the Colab covers both potential core use-cases as well as plugin or theme use-cases.

I have been wondering whether it could be included or embedded in another area more dedicated to this kind of resource, such as learn.wordpress.org. Because it's a Colab, there may be some extra hurdles in getting it in there. But I was curious to see if there's a path forward for it. Is that something we could discuss in the meeting later? Thank you!

**Comment by jonathanbossenger** [comment]
Props:

- I would like to give props to @davouid (@David Corradini in Slack) for his contributions to the Learn WordPress codebase, especially in helping to move some older tickets forward to a resolution.
- I would also like to give props to @ironnysh (@iRonnysh in Slack) for her consistent and helpful reviews of the Developer Learning Pathway lessons. Reviewing new content is a very important part of the content creation process, and it's great to have someone who is consistently reviewing and sharing great feedback
- Last but not least, to @devmuhib009  ([Muhibul Haque](https://profile.wordpress.org/devmuhib) in Slack) for his consistent support during dev squad triage.

**Comment by ghost** [comment]
Meeting recap - https://make.wordpress.org/training/2024/04/08/training-team-meeting-recap-04th-april-2024/
