### ISSUE TITLE
Setting up a WordPress multisite

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2365]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Setting up a WordPress multisite
- Topic description: Learn about WordPress multisite, why you would consider setting up a multisite network, and the steps to follow to create one.
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

- Describe what a WordPress multisite network is
- Describe why you might use a WordPress multisite network
- Manually configure a WordPress multisite network

# Related Resources and Other Notes
- https://learn.wordpress.org/tutorial/introduction-to-wordpress-multisite-networks/
- https://developer.wordpress.org/advanced-administration/multisite/

### Automation Code

//lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/11-introduction-to-wordpress-multisite/01-setting-up-a-wordpress-multisite-network.md

**Comment by jonathanbossenger** [comment]
Video for review:

https://github.com/WordPress/Learn/assets/180629/6effba74-709e-46be-a0b8-c5f8da5a23da

**Comment by quitevisible** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)). 

-----  

### Feedback. 

@jonathanbossenger Great intro, pretty clear and straightforward. It's been many, many moons since I last setup a multisite, so this will be a good refresher course for me! _(I was quietly hoping you were going to go the subdomains route.)_

**Comment by jonathanbossenger** [comment]
Thanks @quitevisible 

`I was quietly hoping you were going to go the subdomains route`

🙂

I would have liked to go that route, but it requires too much configuring on my local environment to set up and support wildcard local domains. Perhaps in a future iteration of this lesson I could spend a bit of time looking into that.🙂

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great intro that covers all important considerations.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/05/11/setting-up-a-wordpress-multisite-network/

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/setting-up-a-wordpress-multisite-network/

**Comment by jonathanbossenger** [comment]
//publish
