### ISSUE TITLE
Single Lesson Plan page

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/Learn#2448]
### [Design](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=3473-42814&m=dev)

<img src="https://github.com/WordPress/Learn/assets/1017872/40eaa74b-6fd9-42f1-9414-7f5eaad60bec" width="300">

**Comment by outdoor2kode** [comment]
Is this for the lesson plan or the lesson? I remember the lesson plan was supposed to be deprecated. @adamwoodnz

**Comment by adamwoodnz** [comment]
> Is this for the lesson plan or the lesson? I remember the lesson plan was supposed to be deprecated.

Lesson Plan. They aren't being deprecated yet as we don't have a solution for teacher's notes on Lessons.

[The Lesson template should be done, it was one of my first tasks](https://github.com/WordPress/Learn/pull/2431).

Have look at the current Lesson Plan template for the print button, etc.

**Comment by outdoor2kode** [comment]
But we're still not going to link its archive from anywhere, right?

**Comment by adamwoodnz** [comment]
> But we're still not going to link its archive from anywhere, right?

Correct, as far as I know. Could be worth revisiting though. I've just created a simple archive so that anyone landing there from an old link has an experience on par with the other archives, nothing like the complexity of the current one.

**Comment by outdoor2kode** [comment]
@fcoveram 
I see that the WordPress Version has been moved, is it intentional? 
Also there might be two buttons above "Print Lesson Plan" if slides are available: "View Slides" and "Download Slides, how should the design be changed accordingly?
| Production | Design |
|-|-|
| ![Screenshot 2024-06-18 at 08 15 50](https://github.com/WordPress/Learn/assets/18050944/6bd82dc7-3ba1-42d9-8960-d7c8c4a54669) | ![image](https://github.com/WordPress/Learn/assets/18050944/44720cad-09a4-4727-8148-ef968babe27f) |
| ![image](https://github.com/WordPress/Learn/assets/18050944/01be794e-caae-4b28-9638-a88398b50c36) | ![image](https://github.com/WordPress/Learn/assets/18050944/cb3afdb3-fee8-4ea2-9f83-4445f29667a4) |

**Comment by fcoveram** [comment]
I think it happened accidentally. I will update the mockups to make sure it's visible.

**Comment by fcoveram** [comment]
For the sidebar variants mentioned above, I think the following can work.

![Mockups of sidebar variants](https://github.com/WordPress/Learn/assets/895819/8ec390df-a10d-492d-a242-992dc952d75f)

When the "Download slides" action is available, it might be good to show the file format and its size. I'm unaware of the best practices or existing ways of displaying that info, but if the latter is real, we should follow that format. What do you think @renintw?

If the above sounds good, let me know to move the assets to the Design page in the Figma file.

On the other hand, I was thinking whether the "Print Lesson Plan" button needs to be the primary action instead of the "Practice on a private demo site" button. To me, the latter makes more sense for learning content related to a online tool. Users input is crucial in this decision, so pinging @bsanevans, @jonathanbossenger, and @kathrynwp to ask for their thoughts.

**Comment by kathrynwp** [comment]
Hey, all! For some context, the focus of the new site is shifting to content for learners (courses/lessons), as opposed to content for teachers (lesson plans). @bsanevans's [WCEU talk last week about the new Learn site](https://youtu.be/ofh6jLrXnpA?t=12400) really explains the shift well, and is really worth watching, if you haven't seen it already. So this is why lesson plans are being de-emphasized and are no longer in the navigation or search results. 

We eventually hope to convert lesson plans to "teacher's notes" that would be attached to the relevant lesson.

> But we're still not going to link its archive from anywhere, right?

> Correct, as far as I know. Could be worth revisiting though. I've just created a simple archive so that anyone landing there from an old link has an experience on par with the other archives, nothing like the complexity of the current one.

Thanks for creating a simple archive page for lesson plans. After discussion with Ben, we will link to this archive from the Training team handbook so it's still reachable from somewhere, even if it's not linked from Learn itself.

> I was thinking whether the "Print Lesson Plan" button needs to be the primary action instead of the "Practice on a private demo site" button. To me, the latter makes more sense for learning content related to a online tool. 

Since these pages are for teachers/instructors would agree with putting the print button first, but either way is really fine.

**Comment by fcoveram** [comment]
> > I was thinking whether the "Print Lesson Plan" button needs to be the primary action instead of the "Practice on a private demo site" button. To me, the latter makes more sense for learning content related to a online tool.
>
> Since these pages are for teachers/instructors would agree with putting the print button first, but either way is really fine.

Let's keep the print button then. Thanks for the quick response.

**Comment by outdoor2kode** [comment]
> When the "Download slides" action is available, it might be good to show the file format and its size. I'm unaware of the best practices or existing ways of displaying that info, but if the latter is real, we should follow that format. What do you think @renintw?

I think that looks good, but because the files are provided via URL and not necessarily uploaded to WordPress (maybe they are?), we need to use a HEAD request to obtain the file type and size. However, the target server may not always allow HEAD requests. Currently, I haven't found any lesson plans with downloadable slides, only those where you can view the slides. Not sure if @kathrynwp, @bsanevans, or @jonathanbossenger have any examples of that?

**Comment by outdoor2kode** [comment]
@adamwoodnz I think the filter for the lesson plans needs to be added, right? Currently, it appears to have only [three filters](https://github.com/WordPress/Learn/pull/2530/files#diff-7e5e168e4cd41b4571d5bebf3e3bb5763075cc90b36913741704e8530c3a704bR42-R44), which are fewer than the ones in [the old theme](https://learn.wordpress.org/lesson-plans/?_view=all).

![image](https://github.com/WordPress/Learn/assets/18050944/c5ecdf2e-315d-49b5-bf18-ff8ac8c2e9e9)

**Comment by kathrynwp** [comment]
> Currently, I haven't found any lesson plans with downloadable slides, only those where you can view the slides. 

@renintw I scanned through all 201 lesson plans in [WP Admin](https://learn.wordpress.org/wp-admin/edit.php?post_type=lesson-plan) but only found **one** lesson plan with "Yes" in the "Has downloadable slides" column:

https://learn.wordpress.org/lesson-plan/what-is-open-source/

I'm not seeing any specific download link anywhere in this lesson plan though, and given that we're only talking about a single lesson plan, I'm thinking we probably don't need even have a "Download slides" button – just keep the "view slides" link and keep things simple. What do you think, Ren & @adamwoodnz ?

**Comment by outdoor2kode** [comment]
> I'm not seeing any specific download link anywhere in this lesson plan though

@kathrynwp  Upon entering its edit page, it appears that the URL is not provided, but the "downloadable slides" option is checked off. So, it's possible that there are lesson plans with a downloadable slides URL, but the "has downloadable slides" is not checked.

That being said, I agree to keep things simple and just keep the "view slides" link. However, it might be better if the slides in the "view slides" link can be downloaded. For example, in the lesson plan you provided, I couldn't find a download option easily after clicking "view slides."

![image](https://github.com/WordPress/Learn/assets/18050944/22c9eaae-9144-44a2-a0d0-7598936fd992)

**Comment by kathrynwp** [comment]
@renintw 

> Upon entering its edit page, it appears that the URL is not provided, but the "downloadable slides" option is checked off. So, it's possible that there are lesson plans with a downloadable slides URL, but the "has downloadable slides" is not checked.

Ah I see, that makes sense. I'm not sure how we would find any lesson plans with downloadable slides, then.

> That being said, I agree to keep things simple and just keep the "view slides" link. However, it might be better if the slides in the "view slides" link can be downloaded. For example, in the lesson plan you provided, I couldn't find a download option easily after clicking "view slides."

That would be ideal, but given that:
- the lesson plan content type is the lowest priority of all types on the site, given the shift in focus from instructors to learners
- the lesson plans archives won't be linked from anywhere on the new site (only from the Training team handbook page)
- lesson plans won't be displayed anywhere in search results
- it's been this way for years

... I'm not sure it makes sense to spend development time at the moment to create a way to have downloadable slides.

Perhaps instead this could be discussed as an enhancement in the future, once lesson plans become "teacher notes" and are linked off their respective lessons? (see #2392)

**Comment by adamwoodnz** [comment]
> @adamwoodnz I think the filter for the lesson plans needs to be added, right? Currently, it appears to have only [three filters](https://github.com/WordPress/Learn/pull/2530/files#diff-7e5e168e4cd41b4571d5bebf3e3bb5763075cc90b36913741704e8530c3a704bR42-R44), which are fewer than the ones in [the old theme](https://learn.wordpress.org/lesson-plans/?_view=all).

I'm not planning for parity with the current page. As this post type is being deprecated I think we should just keep the archive basic.

**Comment by outdoor2kode** [comment]
Fair enough. I'll keep the "Download slides" action and not going to show the file format and its size. Also, not going to add filters. cc @fcoveram

**Comment by adamwoodnz** [comment]
> ... I'm not sure it makes sense to spend development time at the moment to create a way to have downloadable slides.

I second this, let's do the bare minimum for all features of this template for launch. We can always revisit later if need be.

**Comment by outdoor2kode** [comment]
To clarify, I just meant that in the future, could consider uploading slides to a location where they can be downloaded, since I've seen some lesson plan slide viewing pages where the slides can be downloaded. No additional development is needed.

**Comment by fcoveram** [comment]
Since the downloading the slides is an input field and has less chances of being attached, I added it as a single link below the "View slides" button with the external icon, if needed.

Here is the mockup now available on the [Design page](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=1705-79).

<img alt="Sidebar with slides in Lesson page" src="https://github.com/WordPress/Learn/assets/895819/55bdcf42-c246-48ed-bd10-5e2e231e3080" width=220>

**Comment by outdoor2kode** [comment]
@fcoveram "View slides" is also from an input field and will link to an external site, for example: https://learn.wordpress.org/lesson-plan/wordpress-action-hooks/. So I think "view slides" should also be changed to the "download slides" style, right?

<img width="288" alt="image" src="https://github.com/WordPress/Learn/assets/18050944/4e8c1c2c-f5f3-40f7-8cb5-fa269fbed840">

Feel that the idea doesn't' make much sense though:

<img width="1049" alt="image" src="https://github.com/WordPress/Learn/assets/18050944/2ca4be17-3725-43f5-b1ee-f6ff8b2f7d83">

Styles:

<img width="751" alt="image" src="https://github.com/WordPress/Learn/assets/18050944/29380e37-54e0-4a60-9a09-3d99157d55e2">


Animation:

![Screen Capture on 2024-06-24 at 00-54-02](https://github.com/WordPress/Learn/assets/18050944/6e1432b3-6d8e-4538-b0bb-08f091981d5d)

**Comment by fcoveram** [comment]
The transparent button for "Download slides ↗" works well, but I would keep the "View slides ↗" in blue with the external icon to emphasis the action, and "Print Lesson Plan" just with blue border. Like [the mockup](https://private-user-images.githubusercontent.com/895819/341717119-55bdcf42-c246-48ed-bd10-5e2e231e3080.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMjI5MjksIm5iZiI6MTcxOTIyMjYyOSwicGF0aCI6Ii84OTU4MTkvMzQxNzE3MTE5LTU1YmRjZjQyLWMyNDYtNDhlZC1iZDEwLTVlMmUyMzFlMzA4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwOTUwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGJlMzIxMzNjNTcxNzI1MGZmNTlmOWNlOTQ1MmI5ODNkMGJhY2VkOGI2ZDM1Njc5NWIxZDFhZmY5N2YxY2YwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TL4ZHtUce7O7PJ8JKCsTE_BYVEpscTiWp3_YEbMOYj4) shared in the previous comment.
