### ISSUE TITLE
How to Change the WordPress Admin Email Without Verification

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/Learn#2453]
### How to Change the WordPress Admin Email Without Verification

By default, WordPress uses the first email address you provide as your website’s admin email. This address is used for critical notifications and as the email for the first admin account. However, there are times when you need to change this admin email without going through email verification.

#### Why and When You Need to Change the WordPress Admin Email

When initially setting up a WordPress site, beginners often use their personal email address. Additionally, many WordPress hosting providers use auto-installers that automatically set the hosting account’s email address as the admin email during installation. 

There are several scenarios where you might need to update the admin email:

1. **Development to Live Transition**:
   - During the development phase, developers might use their own email addresses. When the site goes live, it’s important to update the admin email to the client’s email address. This ensures that the client receives all important notifications directly.

2. **Changing Ownership**:
   - If the ownership of the website changes, the admin email should be updated to reflect the new owner’s email address.

3. **Security Reasons**:
   - If the current admin email is compromised, changing it promptly can help secure the website.

#### Steps to Change the WordPress Admin Email Without Email Verification

In this video, we will guide you through the process of changing the WordPress admin email address without requiring email verification. This method is efficient and ensures you can update the email address quickly, especially when immediate action is necessary.

By following our step-by-step instructions, you can easily update the admin email address, ensuring that the correct person receives all important notifications related to your WordPress site.

Stay tuned and make sure to subscribe for more helpful WordPress tips and tutorials!

https://github.com/WordPress/Learn/assets/23701579/77c950db-9991-47a4-a888-f20322d063a5

**Comment by sumitsinghwp** [comment]
@devmuhib009 Can you check this now, please?

**Comment by devmuhib009** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

I compared the email addresses used on the video with your original email address and found they are different. What I understood, you used dummy email address for this tutorial purpose only. I think using dummy email will help you preventing spam email on your original email, otherwise, I would suggest you blurring the email address. 

However, everything is looking good to me.

**Comment by sumitsinghwp** [comment]
Here is the new Video with the dummy email @devmuhib009 .



https://github.com/WordPress/Learn/assets/23701579/2965e461-7d48-4bf2-b58d-f581d6834030

**Comment by devmuhib009** [comment]
Awesome, thanks for removing sensitive information like email. Here is the published video: https://wordpress.tv/2024/05/20/how-to-change-the-wordpress-admin-email-without-verification/
//publish
