### ISSUE TITLE
Local Dev: WordPress database error: [Table 'wordpress.locales' doesn't exist]

### ISSUE THREAD

**Issue by CdrMarks** [WordPress/Learn#25]
I setup my local environment on Docker v19.03.12 with Node v.12.18.3 and Composer v1.10.10.  When browsing to http://localhost:8888/ I see the following error across the top of page.  This error does not prevent the rest of the page to render.  The error shows up in the browser's source just before the `</head>` tag.
> WordPress database error: [Table 'wordpress.locales' doesn't exist]
> SELECT locale, subdomain FROM locales

The output of the `npm run create` is attached:  [learn-npm-run-create.log](https://github.com/WordPress/learn/files/5044629/learn-npm-run-create.log)

**Comment by coreymckrill** [comment]
Hi @CdrMarks the quick fix here is to go into **themes/wporg/functions.php** and comment out line 333:

`add_action( 'wp_head', __NAMESPACE__ . '\hreflang_link_attributes' );`

This error won't happen on production, and since we're trying to move fast, we didn't bother setting up a system for local-only code changes.

It looks like I also commented out line 164 in the same file:

`add_filter( 'style_loader_src', __NAMESPACE__ . '\style_src', 10, 2 );`

**Comment by CdrMarks** [comment]
That fixed the error.  Can you suggest a label or milestone that can applied to let others know this is low priority?

**Comment by coreymckrill** [comment]
Just created some `[Priority]` labels we can use.

**Comment by dd32** [comment]
The DB query / hreflang tags were removed via d79ab694f52792468de3891bf2d57d07b07f661b

The `wporg` theme shouldn't rewrite it to s.w.org urls as per https://meta.trac.wordpress.org/changeset/10163 now too.
