### ISSUE TITLE
Submitting your theme to WordPress.org

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2508]
# Details
 
 - Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
 - Content title: Submitting your theme to WordPress.org
 - Topic description: An overview of the process of creating a theme archive and uploading it to WordPress.org.
 - Audience (User, Developer, Designer, Contributor, etc.): Developer
 - Experience Level (Beginner, Intermediate, Advanced, Any): 
 
 # Learning Objectives
 
- Describe the process required to submit a theme to the WordPress.org theme directory
 
 # Related Resources and Other Notes
 
 ### Automation Code
 
 //lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/theme-developer-learning-pathway/08-publishing-themes/04-submitting-your-theme.md

**Comment by jonathanbossenger** [comment]
Video for review: https://drive.google.com/file/d/1g2gxG85m3mZrm-bXxHBbhaGkS0HLF9Gq/view?usp=sharing

**Comment by ironnysh** [comment]
Hi @jonathanbossenger, the linked video is for #2509 (updating your theme).

**Comment by jonathanbossenger** [comment]
Ah, sorry about that @ironnysh, correct video is uploaded (new link added above).

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Love the hands-on walkthrough of the process—very helpful, @jonathanbossenger.

Maybe it's just me, but in the section titled **A note on the theme name**, there's a slightly confusing reference to two “theme directories”: one is the local folder and the other is the official WordPress **T**heme **D**irectory :-)
How about calling the local “folder” instead of “directory”?

At 1:47, the slide shows the soon-to-be-old design of the submission page. It’s probably safe to replace it with the upcoming design that’s supposed to launch soon: https://wordpress.org/themes/upload/?new-theme=1.

**Comment by jonathanbossenger** [comment]
> Maybe it's just me, but in the section titled A note on the theme name, there's a slightly confusing reference to two “theme directories”: one is the local folder, and the other is the official WordPress Theme Directory :-)
How about calling the local “folder” instead of “directory”?

Soooooooo...

On any operating system [a directory and a folder are two different things](https://www.baeldung.com/cs/directories-vs-folders). However, because graphical user interfaces have historically used a folder icon to represent directories visually, we've become used to calling them folders. However, they are all actually directories, something I am reminded of every time I use the `cd` (change directory) command in the terminal. I tend to be strict about calling them that, even though I sometimes revert to calling them folders out of habit. 

(Yes, I know, I'm being overly pedantic about this; [insert appropriate meme here](https://www.youtube.com/watch?v=IRsPheErBj8).)

I get your point, however, and will try to think of a better way to relay this information.

**Comment by ironnysh** [comment]
> On any operating system [a directory and a folder are two different things](https://www.baeldung.com/cs/directories-vs-folders).

Ooh, TIL!

> I'm being overly pedantic about this

Not at all. [I am](https://giphy.com/gifs/BlownAway-jhg7yWeX5rVcg5FuA0) ;-)

**Comment by jonathanbossenger** [comment]
I've decided to revert to calling it a Folder for this lesson, just because it gets too confusing. Also, both VS Code and all operating systems I currently use use the word "Folder" in the window manager UI.

**Comment by jonathanbossenger** [comment]
Updated video


https://github.com/user-attachments/assets/962bae13-f51a-47c0-94df-6c85aaa2c383

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/07/17/submitting-your-theme-to-wordpress-org/

**Comment by jonathanbossenger** [comment]
https://youtu.be/vSNFU1usCOw

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/submitting-your-theme-to-wordpress-org/

**Comment by jonathanbossenger** [comment]
//publish
