### ISSUE TITLE
Lesson: WordPress taxonomies 

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2541]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Taxonomy: What’s the difference between categories and tags?
- Topic description: Something more "architectural" (in the sense of information architecture). See tutorial + comments: [https://github.com/WordPress/Learn/issues/1332](https://www.google.com/url?q=https://github.com/WordPress/Learn/issues/1332&sa=D&source=docs&ust=1718679954017839&usg=AOvVaw3L-Nj8nFiOMp5UEnkf55lY).
Adding it as Lesson 2 in the  Custom post types module
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Advanced 

# Related Resources and Other Notes

### Automation Code

//lesson

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/78ace2e7-4251-4596-bad0-8317d5601022

**Comment by jagirbahesh** [comment]
Great Lesson @westnz ,

- In the video, I noticed mentions of Members ( time 1:24 ) and WPForms ( time 4.14 ) in the admin side. This feels like an advertisement for the Members and WPForms plugins.

### Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Only One points which I have feel the issue apart from that all looks good to me.

Thanks!

**Comment by westnz** [comment]
Thank you @jagirbahesh 👍

**Comment by askdesign** [comment]
Excellent tutorial!

## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

The clarity and word choice of your explanations are excellent. Here are 2 that I really like:
2:01 - "It's good practice to rename this to something more relevant to your content."
2:52 - Tags: "... allowing for more precise content categorization."

Might be confusing, since categories and posts can only be used for posts (and not pages):
3:18 - "Creating custom post types is an excellent way to create content types beyond posts or pages."

**Comment by westnz** [comment]
Thank you for the feedback @askdesign

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x]  Learning outcomes/objectives are clear.
- [x]  Technical concepts introduced in the content are accurate.
- [x]  The speed of demonstrations are easy to follow.
- [x]  The narration audio matches what is shown visually.
- [x]  Spelling and grammar are correct.
- [x]  Sound quality is consistent throughout the video.
- [ ]  [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ]  Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great deep dive, @westnz! 

The only thing I'd add is a mention/explanation of the _Description_ field, which can be displayed in archive page templates using the [Term Description block](https://wordpress.org/documentation/article/term-description-block/). It feels a bit awkward to ignore it :-)

**Comment by westnz** [comment]
Thank you so much @ironnysh 
I will add that 😉

**Comment by westnz** [comment]
//published
