### ISSUE TITLE
Bug: Module headings not visible on some courses

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/Learn#2556]
## Issue
On Learn.WordPress.org with the current (old) theme, module headings on some courses are white, so they are not visible.

Example: https://learn.wordpress.org/course/beginner-wordpress-user/?new-theme=0

## Step-by-step reproduction instructions (optional)

- Visit a course page
- Make sure you're using the old theme (exit the new-theme preview if applicable)
- Look at module headings

## Screenshots or screen recording (optional)

<img width="700" alt="Beginner_WordPress_User___Learn_WordPress" src="https://github.com/WordPress/Learn/assets/7662449/199881db-c1aa-475f-be10-639238a50544">

## Other information (optional)

Tested in Firefox, Chrome & Safari on Mac OS 14.5 (Sonoma).

cc @adamwoodnz :)

**Comment by kathrynwp** [comment]
Apparently this is not affecting all courses. For example, the [Beginner Developer course](https://learn.wordpress.org/course/beginner-wordpress-developer/?new-theme=0) module headings have a black background, which makes the white headings visible:

<img width="646" alt="Beginner_WordPress_Developer___Learn_WordPress" src="https://github.com/WordPress/Learn/assets/7662449/3b129fa4-a170-45c8-b799-64a43b2a0aa1">

**Comment by adamwoodnz** [comment]
This was caused by a Blueberry border being set on the Course Module, which is a color not available in the old theme. I'm not sure how it was set, but I fixed it by toggling the border setting off and on again

![Screenshot 2024-06-21 at 9 32 35 AM](https://github.com/WordPress/Learn/assets/1017872/12425a6d-7f39-475f-a9a8-456abcdbb24e)
