### ISSUE TITLE
Course completion success message

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/Learn#2564]
Add a new field on Course post types in the Learn plugin, for entering a custom completion message. This will be displayed on the course completed page instead of the [default](https://github.com/WordPress/Learn/blob/7538817e9bc7351c2282f668c8c07d9cc1310bd4/wp-content/themes/pub/wporg-learn-2024/patterns/page-course-complete-content.php#L18-L19).

This needs to support being able to add a link. Or it could be 2 separate fields; a completion message field, and link field for linking to a survey.

**Comment by kathrynwp** [comment]
Just noting that the purpose of this would be to display a specific message for each course, once it's completed. This could also allow us to link to a different survey for different courses – for example, the Community team courses might want a different survey than other courses.

**Comment by outdoor2kode** [comment]
@kathrynwp @jonathanbossenger @bsanevans @westnz 

Just noted, with the PR for this ticket shipped, we can now edit the success message and survey link in the course editor sidebar. If left blank, the default values will be applied.

![image](https://github.com/user-attachments/assets/905dd612-1e09-441f-b196-48e32f8f602f)

**Comment by kathrynwp** [comment]
That's fantastic, thanks so much, @renintw !

@jonathanbossenger @westnz This means you can feel free to add custom "course completed" messages for each of the four Learning Pathways courses. 

Flagging for @peiraisotta that it is now possible to have a separate survey for Community courses instead of the single survey we now have, in case you want to split that out.
