### ISSUE TITLE
Browser titles incomplete

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/Learn#2603]
### Summary

Browser titles on some parts of the site are incomplete.

### Issue

On some parts of the site, the `<title>` tag - which appears in browser tabs, among other places, is incomplete.

Example:

https://learn.wordpress.org/level/beginner/page/7/?wporg_lesson_level=all&post_type=lesson

In this view the title tag is just `| Learn WordPress` 

`<title> | Learn WordPress </title>` 

### Expected

There should be some text before the pipe and site title, for example:

`Lessons | Learn WordPress` or `Lessons | Page 7 | Learn WordPress`

### Discovery 

Discovered while navigating the Lessons archives and testing filters.

**Comment by kathrynwp** [comment]
Hi @renintw - just checking to see if this was deployed yet, since I'm still seeing partial browser titles. Thanks!

**Comment by outdoor2kode** [comment]
Hi @kathrynwp 👋  This is because the new theme on the production site is currently being accessed through preview (theme switcher). If you visit https://learn.wordpress.org/test/ or https://learn.wordpress.org/test/lesson/mysql-2/, you will see the titles displayed correctly, which means once we officially activate the new theme, it will correctly display the right titles.

@adamwoodnz Do you think this is a site switcher issue worth fixing?

**Comment by adamwoodnz** [comment]
> @adamwoodnz Do you think this is a site switcher issue worth fixing?

No, if we're confident it will work after launch, then I think we have higher priority things to work on. I will add it as something to check on the launch issue though.

**Comment by kathrynwp** [comment]
Hi @renintw - 

> This is because the new theme on the production site is currently being accessed through preview (theme switcher)

Yep, I'm aware of that. :) 

I'm still seeing the same issue on the site that I reported above, when previewing the new theme. 

Please visit the link I shared earlier – or any similar paginated links:

https://learn.wordpress.org/level/beginner/page/7/?wporg_lesson_level=all&post_type=lesson

I still see this in the title bar:

<img width="220" alt="Notification_Center" src="https://github.com/user-attachments/assets/e2cc69c6-4363-4ca0-af71-9f347be4fc39">

Are you seeing something different?

**Comment by adamwoodnz** [comment]
> Hi @renintw -
> 
> > This is because the new theme on the production site is currently being accessed through preview (theme switcher)
> 
> Yep, I'm aware of that. :)
> 
> I'm still seeing the same issue on the site that I reported above, when previewing the new theme.
> 
> Please visit the link I shared earlier – or any similar paginated links:
> 
> https://learn.wordpress.org/level/beginner/page/7/?wporg_lesson_level=all&post_type=lesson
> 
> I still see this in the title bar:

> Are you seeing something different?

I think what Ren is saying is that this won't work until we have actually activated the new theme, rather than using the theme switcher.

When I test locally I see 'Lessons | Page 2 of 2 | Learn.WordPress.org'

**Comment by outdoor2kode** [comment]
> I will add it as something to check on the launch issue though.

Thanks for this. I traced the code, and head.php does run, but the filter is not being applied. I also don't think it's worth spending extra effort to fix it in the theme switcher right now. Since it works on a site where the new theme is actually activated, I believe it will work during the actual switch.

> I think what Ren is saying is that this won't work until we have actually activated the new theme, rather than using the theme switcher.
>
> When I test locally I see 'Lessons | Page 2 of 2 | Learn.WordPress.org'

Yes, correct. Like @adamwoodnz said, it works locally and also on the test site (which we didn't really use due to the incomplete data there). Both of them have had the new theme activated. While on the production site, the one that you shared, one that can view the new theme through the theme switcher, it doesn't really activate the new theme technically. And that's why you still see the incomplete title.

**Comment by kathrynwp** [comment]
> I think what Ren is saying is that this won't work until we have actually activated the new theme, rather than using the theme switcher.

Ahhhh – thanks for clarifying! As long as it works when we go live, all good.

**Comment by outdoor2kode** [comment]
Looks good after activating the new theme.
