### ISSUE TITLE
New Theme - Search doesn't always return relevant results.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#2675]
## Description
When I search for "Block theme" my first result is for the WordPress REST API. I would not expect this to be my first result.

For the most part, the search appears to work and provide relevant results, but for some reason, this query is not working that well.

## Step-by-step reproduction instructions (optional)
1. Go to https://learn.wordpress.org/courses/
2. Search for "block theme"
3. Notice [Introduction to developing with the WordPress REST API](https://learn.wordpress.org/course/developing-with-the-wordpress-rest-api/) is your first result.

## Screenshots or screen recording (optional)

<img width="1200" alt="Screenshot 2024-07-15 at 10 09 55 AM" src="https://github.com/user-attachments/assets/699186c7-9304-4995-ae78-337fd51227d1">

**Comment by adamwoodnz** [comment]
The words 'block' and 'theme' both appear in the first two paragraphs, so I imagine this is expected?

Changing the search to `'block theme'` only matches the full string and returns the results you're looking for I think

![Image](https://github.com/user-attachments/assets/17f6c53d-31af-4170-95d6-28142fe653b6)

**Comment by adamwoodnz** [comment]
Tried this again and the results are better due to newer content being added, as no code change has been made specifically to address this. Results for https://learn.wordpress.org/?s=block+theme&post_type=course:

![Image](https://github.com/user-attachments/assets/29456190-ef5a-45fa-9d4d-7e5bb8bd3331)

Closing as I believe the search is working as expected, but please reopen if you think it needs attention.
