### ISSUE TITLE
Modern JavaScript

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2703]
# Details
 
 - Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
 - Content title: Modern JavaScript practices
 - Topic description: Introduce more modern JavaScript practices in WordPress like ESNext, JSX, webpack, wp-scripts, let, const, destructuring assignment, and arrow functions.
 - Audience (User, Developer, Designer, Contributor, etc.): Developer
 - Experience Level (Beginner, Intermediate, Advanced, Any): 
  # Prerequisites
 
 
 It is assumed that the learner has already completed the following lessons:
  - [Beginner WordPress developer](https://learn.wordpress.org/course/beginner-wordpress-developer/)
   - Modules 1 - 4
   - Module 5: WordPress Hooks
   - Module 6: An introduction to developing WordPress plugins
   - Module 7: An introduction to developing WordPress blocks
 # Learning Objectives
 
 - Identify the difference between JavaScript, ESNext, and JSX
 - Explain the use of tools like webpack and Babel
 - Explain the use of wp-scripts to implement a build process
 - Summarise modern JavaScript practices for defining variables, object and functions
 # Related Resources and Other Notes
 - https://developer.wordpress.org/block-editor/getting-started/fundamentals/javascript-in-the-block-editor/
 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/JavaScript_technologies_overview#standardization_process
 ### Automation Code
 
 //lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/plugin-developer-learning-pathway/03-Advanced-Blocks/01-Modern-JavaScript.md

**Comment by jonathanbossenger** [comment]
Video for review: https://drive.google.com/file/d/1srQNFgPckj--Vdz2jzp2o7zQNQq90UBz/view?usp=sharing

[Guidelines for Reviewing Content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/).

**Comment by RoelofWobben** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [X] Learning outcomes/objectives are clear.
- [X] Technical concepts introduced in the content are accurate.
- [X] The speed of demonstrations are easy to follow.
- [X] The narration audio matches what is shown visually.
- [X] Spelling and grammar are correct.
- [X] Sound quality is consistent throughout the video.
- [X] Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [X] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

Nice to see that more modern js is explained and shown in the video and script.

**Comment by MichelleBlanchette** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [ ] The speed of demonstrations are easy to follow. (see feedback)
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

This is a fantastic synopsis of common terms a developer encounters in modern JS conversations/documentation, followed by concise demonstrations of the most common features of modern JS. I really enjoyed this! It was also really great to see some suggested resources at the end of the video for continued learning. 🙂 

Here's a few suggestions I have:

02:15 - There is a thump noise (maybe throat clear or mic was bumped?). Could that be muted in the audio track?
06:32 - Can the difference in the function signature be specifically highlighted or pointed out visually? I found myself having to rewind to see what was being called out since the code snippets are only slightly different, visually.
06:40 - Calling out the parameters and doing some relevant highlighting for the arrow functions' differences would help visually clarify what's being pointed out. It was quite fast-paced for me, visually.

**Comment by jonathanbossenger** [comment]
Thanks for the review and feedback @MichelleBlanchette I'll work on implementing some tweaks around your suggested changes.

**Comment by jonathanbossenger** [comment]
WordPress.tv: https://wordpress.tv/2024/10/11/modern-javascript/

**Comment by jonathanbossenger** [comment]
Youtube: https://youtu.be/mFUM7Ejby7c

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/modern-javascript/

**Comment by MichelleBlanchette** [comment]
@jonathanbossenger I noticed a typo in the script. Is there a way we can submit feedback for content that's already been published to WordPress Learn?

`it’s syntax` should be `its syntax`.
![Image](https://github.com/user-attachments/assets/6eb54fd0-5c5a-40e1-b9b3-6a441161d684)

**Comment by MichelleBlanchette** [comment]
I found this form linked at the very bottom of the lesson https://learn.wordpress.org/report-content-feedback/ but I'm wondering if there's a more efficient way we can submit a pull request, for example, to more quickly and effectively report feedback.

**Comment by jonathanbossenger** [comment]
@MichelleBlanchette, you can ping me about the issue as you've done here (and thanks; I've fixed it!).

For a published lesson, it's a post on the Learn Site, so the author or an editor needs to fix it. 

For any other content, especially if you don't know the content issue, you can just open a blank GitHub issue with the details, and someone will triage and tag the content author.
