### ISSUE TITLE
Feedback - "Clear All Filter" button should be visible only when the filter(s) is applied.

### ISSUE THREAD

**Issue by kjnanda** [WordPress/Learn#2793]
## Type of feedback

UX feedback

## Description

So while the user browse through the tutorial, they have different options to filter to choose based on their requirement. Now, before the filter is applied we should not show "Clear All Filter" as it leads to confusion! 

At first, I was confused as I had not applied any filter and why it is present! But later I found that it is the default behaviour! 

## Expectation

For the best UX, we should show it only when one or more filters are applied.

## Step-by-step reproduction instructions (optional)

Please list the steps needed to reproduce or verify the feedback. For example:
1. Go to https://learn.wordpress.org/tutorials/ page
2. Scroll down a bit 
3. Observe the set of drop downs present right below the search box
4. Now, observe the presence of the "Clear All Filters" button even before you apply any filter(s).

## Screenshots or screen recording (optional)

https://github.com/user-attachments/assets/a3ce3191-b2bd-4c39-9500-5499d93fed54

## Other information (optional)

Few more pages where I observed the similar problem. 

- https://learn.wordpress.org/lesson-plans/?_view=all

**Comment by kathrynwp** [comment]
Hi @kjnanda - as mentioned in your other report, what you're looking at is an old version of the site that is about to be replaced with a completely new one in just a few days. If you'd like to test the new site, please see the instructions here and feel free to submit any issues:

https://make.wordpress.org/training/2024/07/09/lets-start-testing-learn-wordpress-org/

I'm closing this issue since the old theme is not being updated any longer.

**Comment by kjnanda** [comment]
@kathrynwp Sorry for the wrong report! 🙇🏻‍♀️
