### ISSUE TITLE
React without JSX

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2882]
# Details
 
 - Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
 - Content title: Using React without JSX
 - Topic description: Describe how it's possible to develop WordPress blocks in React without using JSX or a build step.
 - Audience (User, Developer, Designer, Contributor, etc.): Developer
 - Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate
 
 # Prerequisites
 
 
 It is assumed that the learner has already completed the following lessons:
  - [Beginner WordPress developer](https://learn.wordpress.org/course/beginner-wordpress-developer/)
   - Modules 1 - 4
   - Module 5: WordPress Hooks
   - Module 6: An introduction to developing WordPress plugins
   - Module 7: An introduction to developing WordPress blocks
 # Learning Objectives
 
 - Identify the differences between using JSX and a build step or not when developing blocks
 - Describe the pros and cons of both approaches

 # Related Resources and Other Notes
 
 ### Automation Code
 
 //lesson

**Comment by jonathanbossenger** [comment]
Video for review: https://drive.google.com/file/d/1Mdat9txhXXrEp_hJAQLwDlZXC-z3fM1o/view?usp=sharing

[Guidelines for Reviewing Content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/).

**Comment by RoelofWobben** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [X] Learning outcomes/objectives are clear.
- [X] Technical concepts introduced in the content are accurate.
- [X] The speed of demonstrations are easy to follow.
- [X] The narration audio matches what is shown visually.
- [X] Spelling and grammar are correct.
- [X] Sound quality is consistent throughout the video.
- [X] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [X] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

Nice that the difference is shown with a example and that is pointed out why you should use JSX for plugins

**Comment by lela-bones** [comment]
## Tutorial/Lessons Review Checklist

Hey @jonathanbossenger, I'm new to Wordpress, and am currently at contributor day at word camp. Please move the status of this issue project to first review, given I don't seem to have the access. Let me know if you have any questions about my review. Thanks for setting this training up. 

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Comments:
- The pacing is very good and clear!
- At 00:52 the overlay of the GitHub url is very hard to see (maybe a gray background?).
- I think that the use of the previous training with JSX to create a clear comparison without JSX was really good! Having a starting place makes this easier to understand. 
- The goal of the video was clear. I think something like a quick Outline screen where you discuss the overall themes [unless you just do this in the article blow]. I also think that the motivation (pros/cons) of using and not using JSX should be earlier in the video. I spent most of the video wondering why I would want JSX-less blocks, but didn't get the answer until the very end. (my brain doesn't always retain information I don't know why it is necessary). 
  - introduction/goals
  - motivation/pros/cons
  - differences between JSX and non JSX
  - working example of the block working the same
  - conclusion (elaborate on use cases of pros and cons)

**Comment by MichelleBlanchette** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Really great pace and example code! The visuals helped clarify what is being discussed, and this was a really great comparison of the two different ways to code React. Usually I'd agree with @lela-bones comment about arranging the "why" at the end of the video. However, I actually found it much easier to understand after seeing how they differ in the first place. It was also very helpful to ease my curiosity during the presentation since it's clearly stated at the beginning that I will learn the "why" later in the video. It was nice this way because I could make my own judgment and spot the differences myself then better empathize with the pros and cons at the end. But that's just my two cents. 🙂 

Here's some suggestions:

00:52 - I agree with @lela-bones the the URL was difficult to catch/read. Maybe invert it to be on the blue background with white text like the slides are since it's more of a visual cue and wouldn't blend in as much with the rest of the screenshare.
02:45 - The `index.asset.php` file is shown with incorrect indentation settings. VS Code is showing double indentation guides for each level of indentation, where the files previously shown had the proper formatting.
04:10 - A blue arrow is flashed in the left, seemingly to point at nothing relevant, and is too quick to understand. (seems like a missed cut)

**Comment by jonathanbossenger** [comment]
Thanks for all the feedback folks, I plan to review it all this week and make any relevant updates. 

With regards to the structure of the video lesson, this is obviously down to the personal preference of each instructor and learner. 

I tend to follow a "show" then "tell" approach. So first I'll show something, grabbing the users attention, and then explain why. In my personal experience, it's a more effective approach to learning technical concepts, especially in short-form online video content. 

That being said, I encourage any contributors to follow their own approach when creating their lesson content.

**Comment by jonathanbossenger** [comment]
WordPress.tv: https://wordpress.tv/2024/10/11/developing-wordpress-blocks-without-jsx-or-a-build-process/

**Comment by jonathanbossenger** [comment]
YouTube: https://youtu.be/mdpZwjv-KuA

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/developing-wordpress-blocks-without-jsx-or-a-build-process/

**Comment by kaitohm** [comment]
//publish
