### ISSUE TITLE
WordPress showcase for designers

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2890]
//lesson

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/0356fcf5-fd8c-47a6-ba17-7b15838a4eb6

**Comment by askdesign** [comment]
Engaging intro. to the potential of designing with blocks. I really noticed the lovely transitions in this one. Makes me think I should use a few of them!
2:20 - A transition would be good here at the very end.

**Comment by westnz** [comment]
[Review: Imran Siddiq](https://wordpress.slack.com/archives/C02RW657Q/p1727515057610299?thread_ts=1727388595.147899&cid=C02RW657Q)

> Well explained video. It could be improved with less static screens. In some scenes we’re just seeing finished sections/covers etc. If a 5 second action scene of blocks being dragged, or images being selected to fill the cover, would help alongside the vocals.
> The finished sections could still be seen for 3 seconds, but when we state that it’s easy, then a little more actions succeeds in ‘Show Not Tell’.

**Comment by BSICTVince** [comment]
The video highlights WordPress's strength, showcasing how it powers 40% of the web, and its message is clear. However, it only includes brief screen captures. It would be more effective if it extended the demonstration of its capabilities, showing a more comprehensive overview rather than just a small excerpt. But in over all, this is a very good introduction for the course

**Comment by westnz** [comment]
//published
