### ISSUE TITLE
Use the Style Book for a simple style guide

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2891]
Use the Style Book for a simple style guide—how to apply your design knowledge on WordPress:

- Text
- Media
- Design
- Widgets 
- Theme

//lesson

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/d7adb07a-c82b-4876-a9a2-073ffaad9a6b

**Comment by quitevisible** [comment]
## Tutorial/Lessons Review Checklist 
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.  

*****  

@westnz This is a great high level overview of Styles. I've learned to explore this section early on in the design process.  

If there's an opportunity to show what happens when you 'Save' your edits, I think that would be helpful.  

Especially when editing styles from a page/post, as compared to going directly into the Style Book from the editor. The changes are global and not isolated to the page/post being edited (if that makes sense?). 

Also, my experience has been that anytime you make a change in Styles, the editor will prompt you to 'Save' them before leaving the editor. 

And Style Book can act a little wonky sometimes with child themes and the Create Block Theme plugin!

Another good one!

**Comment by westnz** [comment]
//published
