### ISSUE TITLE
Using a plugin to create a carousel slider

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2909]

**Comment by westnz** [comment]
//lesson

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/9c6a4e3f-e767-4b5c-aa7f-f12691be2a78

**Comment by westnz** [comment]
Note to self: re-record the voice-over for the introduction.

**Comment by quitevisible** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

*****  

@westnz Uh oh - the carousel slider is back!😆  

- The only thought I had was possibly including a disclaimer of a plugin endorsement. Unless that's acceptable. 

Otherwise, great rundown of implementing sliders in a block theme. Especially one that's Woo compatible!

**Comment by westnz** [comment]
Thanks for the helpful suggestion.

> Uh oh - the carousel slider is back!

😅

**Comment by westnz** [comment]
//published
