### ISSUE TITLE
Lesson: Exploring WordPress 6.7

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#3014]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Exploring WordPress 6.7
- Topic description: Explore new features
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate

# Learning Objectives

Explore key updates
# Related Resources and Other Notes

### Automation Code

//lesson

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/2c517627-7346-4584-a577-8be811f6876e

**Comment by westnz** [comment]
//review

**Comment by westnz** [comment]
Note to self: 
- 00:37 - 00:40 Fix jumping cursor

**Comment by digitalchild** [comment]
Great overview. I don't think the cursor is an issue to be honest. 

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by kaitohm** [comment]
- [ ] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

At the very beginning, you're intro is very simple. You say something like "Let's explore 6.7." To better set the stage, could you add some examples of what the updates are? "In this video, we'll explore 6.7. This update introduced a new theme, changes to X, a brand new Y, and Z, just to name a few. Let's dive in and check those out."

At 3:10, the video mentions how one can't select between Default or Custom when adding a query block to a post or page. Could we add an explanation so that, if someone _does_ want to edit the settings, they know where to go? (I haven't looked into it, so I'm not sure where they'd need to go.)

Otherwise, this looked good to me. Thanks for working on this 🙌

**Comment by westnz** [comment]
Thank you for the reviews!

> At 3:10, the video mentions how one can't select between Default or Custom when adding a query block to a post or page. Could we add an explanation so that, if someone does want to edit the settings, they know where to go? (I haven't looked into it, so I'm not sure where they'd need to go.

I will add some clarity.  The nice thing is that you can automatically edit the settings, so I assume it is custom by default.

**Comment by westnz** [comment]
**Review: Leif Quitevis**

> You were able to pack in a lot of good info on new/updated features in a short amount of time! Good pace and very informative video. 
> 
> The way WP is going, we’re only going to need the shipped default theme to create any website. The theme repo will just become the ‘Patterns’ repo.

**Comment by westnz** [comment]
//published
