### ISSUE TITLE
Titles on Table Headings are white on white

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#308]
It's hard to read white titles on a white background.
See tables on [Pathways to Learn WordPress](https://learn.wordpress.org/handbook/pathways-to-learn-wordpress/)

```

table thead {
        color: #555!important;
}
```

**Comment by jonathanbossenger** [comment]
@courtneyr-dev I see that the current CSS for that thread element is 

```
table thead {
  background: #32373c;
  color: #fff;
}
```

@coreymckrill before I submit a PR, do we know if changing this style will affect anything else? Otherwise, it might be better to apply the CSS on a specific class, so it's just applied to this handbook doc.

**Comment by coreymckrill** [comment]
As far as I know, the handbook at https://learn.wordpress.org/handbook/ is deprecated and the one at https://learn.wordpress.org/meta/handbook/ should be used instead. That's a separate site that is using a theme that is designed to support the handbook plugin, whereas the theme for the main Learn site is not.

**Comment by coreymckrill** [comment]
@hlashbrooke is this correct? If so, maybe we should disable the handbook plugin on the main Learn site so we can avoid more confusion about this in the future.

**Comment by hlashbrooke** [comment]
Yeah, that's correct - we should be using the /meta/handbook instead since it can actually make use of the Handbook plugin correctly.

We cannot disable the Handbook plugin on the main site because we are using the callout blocks that it provides in other Learn content. If those blocks were pulled out into a separate plugin (which would be a neat idea) then we could disale the Handbook plugin on the main site.

**Comment by jonathanbossenger** [comment]
@courtneyr-dev are you able to create this in the handbook at https://learn.wordpress.org/meta/handbook/?

**Comment by courtneyr-dev** [comment]
Update: moved the content to a page on LearnWP, per @hlashbrooke suggestion. https://learn.wordpress.org/pathways-to-learn-wordpress/. Same issue. Hugh might add that CSS.

**Comment by jonathanbossenger** [comment]
@courtneyr-dev I checked the new page and it seems the titles are correct there, if you could please confirm you see the same?

**Comment by courtneyr-dev** [comment]
Yes, closing.

**Comment by jonathanbossenger** [comment]
Thanks @courtneyr-dev 

@hlashbrooke would you mind opening an issue to pull the callout blocks (and anything else that might be needed) into a separate plugin so that we can work towards disabling the handbook plugin on the main Learn site. 

Please ping me there, I'd like to see if I can get that done.
