### ISSUE TITLE
Intro to the Site Editor - Tutorial

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#456]
https://learn.wordpress.org/workshop/intro-to-the-site-editor-and-template-editor/

**Comment by azhiya** [comment]
Here is the link for the workshop: https://learn.wordpress.org/workshop/intro-to-the-site-editor-and-template-editor/

**Comment by azhiya** [comment]
Please review:

- https://github.com/WordPress/Documentation-Issue-Tracker/issues/305
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/306

**Comment by azhiya** [comment]
This needs a review

**Comment by abhansnuk** [comment]
Following discussion with @courtneyr-dev and @azhiya , moved back to ready to help column as has two revisions for 6.0.

**Comment by westnz** [comment]
Reviewed the links.  Due to the Intro nature of the workshop, I did not go into detail about the different types of templates or creating new templates.

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/issues/37407
https://github.com/WordPress/gutenberg/pull/42520

**Comment by westnz** [comment]
I have re-recorded and updated the entire tutorial for 6.1:



https://user-images.githubusercontent.com/89751452/198176810-c1931bbb-4420-42bc-ac55-60fdeb8ab10a.mp4

**Comment by abhansnuk** [comment]
Reviewing. Thanks @westnz .

At 4:8 and 7:13, can we remove the color image behind the text in these slides as this is not good for accessibility.
@azhiya @webtechpooja and @courtneyr-dev  can we add this into the checklists please too?

At 7:37 a query on whether we will be using that kind of opening a page as it can be difficult for some people with visual issues.

Can we hold on the last slide for longer as it closes too quick if someone was wanting to note the useful items within.

It is a really interesting tutorial and great that it has an update for 6.1! I would suggest some of the changes of scenes are a little too fast for different kinds of learning styles and slightly slowing these down in future would be a benefit. A short pause between different concepts / aspects also helps learners process the information and structure their understanding/ learning. These are wider than this video and we can perhaps discuss it elsewhere @courtneyr-dev @webtechpooja and @azhiya? 

**Wider**
On the more general phrases to be careful of that we have started to discuss for a tips to presenters document. A couple of things from this video which we can add to that. 
In general for when anyone is recording 'query loop', it is worth slowing down and making the 'p' clear to avoid it sounding like 'loo'. 
'Template part' is another phrase worth reminding those recording to slow down on and make the 't' clear and even having a very short pause after it especially if it as at the end of the sentence.

**Comment by westnz** [comment]
Thank you for the feedback @abhansnuk

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/intro-to-the-site-editor-and-template-editor/

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/220031166-82f546bc-0101-43ac-829e-ebdf47c1f0ae.mp4

**Comment by westnz** [comment]
Ready for 6.2 release

**Comment by gudrunfrank** [comment]
I think it was great. You spoke slowly and clearly.

**Comment by westnz** [comment]
Thank you for the feedback @gudrunfrank

**Comment by nomad-skateboarding-dev** [comment]
# Overall Impression
This was well done, Wes! I agree with what I hear from @gudrunfrank,  that the information was easy to understand. 🥇 

## Specific Feedback

- Make note that the Nav Menu won't be in 6.2 Sidebar. (I believe [this was the determination](https://wordpress.slack.com/archives/C02RW657Q/p1678729672443549) instead of redoing all videos currently?)
- 1:23 Noting that not all themes will show 'Browse Styles'. Not sure if it's relevant information though. 😄 

Edit: typo

**Comment by westnz** [comment]
Thank you! @nomad-skateboarding-dev

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/intro-to-the-site-editor-and-template-editor/

**Comment by westnz** [comment]
I am currently working on updating this tutorial. I am going to change the title to: "Intro to the Site Editor".

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/2e27c7ac-c429-4cd6-8754-1ed956788721

**Comment by jonathanbossenger** [comment]
A great introduction to the Site Editor in 6.3, well done @westnz

**Comment by digitalchild** [comment]
I always learn something new in these reviews. Great intro @westnz

**Comment by westnz** [comment]
Thank you for the feedback, @jonathanbossenger and @digitalchild. 😃

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/intro-to-the-site-editor-and-template-editor/

**Comment by westnz** [comment]
Updated for the learning pathways project.

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/c3c4ea3c-2207-4f0a-9a6f-ab67541141e6

**Comment by westnz** [comment]
//lesson

**Comment by kathrynwp** [comment]
Great Site Editor overview! Jam-packed with info but at a nice pace that didn't feel rushed.

Couple of small observations:

2:25 - Fonts section - you say: "Click on upload if you want to upload any font from your computer." Is it worth a little caveat that you should make sure you're allowed to use the fonts you're uploading/have the right license? i.e. "Make sure you have the right to use any fonts you're uploading." It's probably not something we'd mention in the context of the Media Library as we assume folks have enough general knowledge not to upload images they don't have the right to use, but since the Font Library is so new, maybe folks don't realize you can't just take any font and use it on your own site? And what about format, is it worth a brief mention of what font file format can be uploaded, or is that out of scope? Maybe there's another lesson somewhere where this will be covered in more detail?

4:52 - Is it worth mentioning somewhere in this section that you can still edit/add pages at WP Admin > Pages, as usual? I just wonder if some folks might assume this method has _replaced_ the older way of creating and editing pages, instead of being _in addition_ to the WP Admin way?

5:38 - "Page" template - I think the more common template name is now "Pages" (plural) – like in Twenty Twenty-Four – rather than the singular "Page." It's a _super_ minor difference though, and not worth redoing the whole demo for this, but maybe something to note for the future. Could be a good idea to use a more standard/recent theme, perhaps? (Same with "Single Post" vs. "Single Posts")

7:36 - For better a11y (i.e. for visually impaired folks) instead of saying "Open the relevant piece of content" it would probably be better to describe the specific steps you're taking, as you show them. So maybe something like "Open the relevant piece of content. Let's go to WP Admin, Pages, and click on the page name or Edit." 

That's it!

**Comment by westnz** [comment]
Thank you very much for the feedback and suggestions!! 😃

**Comment by westnz** [comment]
Updated and published as part of the Beginner User learning pathway in Sensei.

//published
