### ISSUE TITLE
Workshops Archive

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#5]
![workshop-archive](https://user-images.githubusercontent.com/916023/89588864-633d1f00-d7f9-11ea-8de8-31539a3a02e1.jpg)

Filter UI:
![workshop-archive-filter](https://user-images.githubusercontent.com/916023/89588899-70f2a480-d7f9-11ea-94df-52e49275e4da.jpg)

https://www.figma.com/file/UtmG8KQv3Csy8hNtuAWkwZ/Learn-WordPress?node-id=51%3A3565

#### Milestone 1
- Workshop list

#### Milestone 2
- Search
- Filters
- Advanced Features

**Comment by StevenDufresne** [comment]
@hlashbrooke Will the current [`/workshops`](https://learn.wordpress.org/workshops/) be a subset of featured workshops (right now it just pulls everything...)? 

If it is a subset of featured workshops, any preferred method for managing them? (Ie. Category, CPT, etc.)

Additionally, the home page links to "View All" in the "Recent" category, does that link go to the archive page depicted here or the landing page? If it doesn't go to the landing page, I don't see how users will ever be able to find their way to it. Maybe "View All" would make more sense as a "View more"?

**Comment by hlashbrooke** [comment]
`/workshops` should just pull all the workshops (as it does now) - there's no need for a "featured workshops" section I don't think.

Could you explain what you see as the difference between the workshop archive and the workshop landing page? The way I see it, there should only be one workshop archive/landing page with the filters.

**Comment by StevenDufresne** [comment]
Yep, in the initial design, we have 2 different views of workshops.

Workshop Lander:
_We implemented this already._

https://www.figma.com/file/UtmG8KQv3Csy8hNtuAWkwZ/Learn-WordPress?node-id=106%3A0
 

Workshop Archive:
_Not implemented_

https://www.figma.com/file/UtmG8KQv3Csy8hNtuAWkwZ/Learn-WordPress?node-id=51%3A3364


It isn't clear to me how they relate since the designs are different. Do we add the filtering above the large featured workshop we have currently? Or do we build out an archive page with filtering & search & paging.

**Comment by hlashbrooke** [comment]
The idea there is that the initial lander would be for when there's not much content on the site and the second mock-up for the archive with the filters is for when we have enough content for that, so it would replace the older one.

In terms of layout, the mockup with the filtering is where we want to be moving forward - the inital layout with the large featured image was just there since we have so few workshops to start.

**Comment by StevenDufresne** [comment]
Thanks for clarifying.

**Comment by StevenDufresne** [comment]
What about something like this? The tags do a good job explaining the type, although they are a bit loud.
![](https://d.pr/i/kl0FeO.png)

_Disregard the inconsistencies with the titles and the missing tags on item 3 & 4._

**Comment by hlashbrooke** [comment]
I assume this comment was meant to be on #38 instead? I like the design! And I think it works well for the use case.

**Comment by StevenDufresne** [comment]
> I assume this comment was meant to be on #38 instead? I like the design! And I think it works well for the use case.

Meep! Meep! Definitely wrong ticket :) .

**Comment by coreymckrill** [comment]
In the process of building the logic for the filters and the functions for outputting all the available options for each of the filter parameters, it occurred to me that having a column of checkboxes inside a togglable "drawer" won't scale very well when there are dozens of options for any particular parameter. The Language and Captions parameters especially will probably eventually have dozens available, but I could also see dozens of different topics and series as well.

With that in mind, in #107 I started going down the path of using ~Select2~ SelectWoo dropdowns for each of the filter parameters instead of checkboxes. The advantage is that you can find the option you want by beginning to type in the dropdown field and choosing from the partial match results that it shows. Plus, the drawer will always be the same size regardless of how long the list gets for a particular parameter. Here's what it looks like right now:

![new-filter-drawer](https://user-images.githubusercontent.com/916023/92630146-3a8ac800-f284-11ea-9464-df058701e6a9.jpg)

@StevenDufresne pointed out that having to click to open the drawer and then click again to open one of the dropdowns is not great UX, and it made me think that maybe we don't need the togglable drawer at all, we could just show the dropdowns in a bar at the top of the page.

I'd love to get some designer eyes and mind on this. @melchoyce ?

**Comment by melchoyce** [comment]
I figure'd we'd reuse [the existing feature filter we have on themes](https://wordpress.org/themes/) so I didn't put any extra thought into it. Scalability is a good concern here. Would something like this work?

![image](https://user-images.githubusercontent.com/2846578/92772969-30db9000-f36a-11ea-9475-870a21b65820.png)

**Comment by coreymckrill** [comment]
@melchoyce I like this. We still need to have buttons for Apply Filters and Clear All, so in my latest commit I've put them in a fifth column:

![filter-no-drawer](https://user-images.githubusercontent.com/916023/92837519-89268800-f392-11ea-86a9-d05dc91c70f7.jpg)

I'm not sure about listing the items beneath when they are selected. I was kind of thinking they would be single select instead of multiple. But if we do go multiple, what would be the behavior if you keep on adding more language selections? Would it bump all the content beneath it down?
