### ISSUE TITLE
Tutorial: What is flex layout and how to configure with block themes

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#523]
Workshop is submitted through https://learn.wordpress.org/workshop-presenter-application/

CHECKLIST: Workshop Development Checklist
- [ ] Provide feedback of the idea
- [ ] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [ ] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [ ] Workshop created
- [ ] Workshop published on WPTV
- [ ] Workshop created on Learn.WordPress.org
- [ ] Lesson plan has been published
- [ ] Vetted by instructional designers for content idea
- [ ] Vetted by deputies for contributor reputation
- [ ] Workshop published on Learn.WordPress.org
- [ ] Workshop announced to training team
- [ ] Workshop announced to creator
- [ ] Workshop announced to Marketing Team for promotion
- [ ] Workshop post is reviewed for grammar, spelling, etc.
- [ ] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [ ] Gather feedback from workshop viewers/participants

**Comment by annezazu** [comment]
Can pull from this: https://developer.wordpress.org/news/2023/02/intrinsic-design-theming-and-rethinking-how-to-design-with-wordpress/

**Comment by annezazu** [comment]
# Vetting Checklist for SMEs
- Priority - either High, Medium or Low: medium
- Feedback regarding the topic description: N/A
- Feedback regarding the learning objectives: N/A
- Any other feedback: This hasn't gone anywhere. I'd recommend making this a part of a larger course, whether block theme or about creating layouts with blocks, rather than something on it's own. 

@bsanevans curious what you think about closing this out as a result.

**Comment by courtneyr-dev** [comment]
This is intended to be a short Tutorial video. It may be embedded in courses later.

**Comment by kaitohm** [comment]
@courtneyr-dev Could you add a Topic Description and Learning Objectives for this as a short Tutorial? We could re-vet the topic then and asses it's priority.

**Comment by kaitohm** [comment]
Closing, due to not enough information. (See [this Slack conversation](https://wordpress.slack.com/archives/C03B11FA16D/p1688486841217239?thread_ts=1687827128.413619&cid=C03B11FA16D) for more information.)

If you'd still like to see this content created, please create [a new Topic Idea issue](https://wordpress.slack.com/archives/C03B11FA16D/p1688486841217239?thread_ts=1687827128.413619&cid=C03B11FA16D) and fill out the information listed.
