### ISSUE TITLE
Lesson Plan: do_action Non-profit Training

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#527]
**Introduction: What is WordPress?**
High Level Overview
*Basic WordPress Concepts*
One Click Install Using Bluehost
**Getting Started: A Quick-Start Guide to WordPress**
Overview of the Dashboard
Settings
Pages vs. Posts
Setting a Static Page as Your Homepage
Categories vs. Tags
What to Do When You Forget Your Password
*User Management*
**Prettier Posts: Getting to Know the Editor**
*Content Editor Overview*
Managing Media
Managing Comments
**Make It Your Own: Changing the Look and Feel of Your New Site**
Choosing and Installing a Theme
Theme Customizer
Managing Widgets
Managing Menus
*Selecting Plugins*

**Comment by courtneyr-dev** [comment]
this is an older original workshop idea which would involve a series of lesson plans strung together for a half or full day program

**Comment by jomarieminney** [comment]
I've run a do_action before and can confirm that a lesson plan would be of great assistance but I'm unsure if this is necessarily the best content structure. For a start, there are two very different audiences - and this seems to kind of speak to both of them. I think the original idea for this (I remember a similar idea being floated back in the Trello days) was that it was a lesson plan for the charities and focused more about ongoing editing/maintenance of the site, touching on things like security, users/access levels, adding/changing/removing content etc. Some feedback on what is listed based on what did/didn't work for us and how I'd run one if I did it again...
1. I wouldn't go into installation/hosting - for a start, I think it is common from other organisers I spoke to that hosting is often sponsored (ours was, but not by blue host - by VentraIP who are an Australian hosting company and sponsor of WP Australia) and to be honest, the people who are doing this bit are the 'expert' volunteers who have done this before. We don't expect charity volunteers to do the install, because that is why the do_action exists.
2. All of this is spot on - great content and very applicable to the charity volunteers:
- Overview of the Dashboard
- Settings
- Pages vs. Posts
- Setting a Static Page as Your Homepage
- Categories vs. Tags
- What to Do When You Forget Your Password
- User Management
- Prettier Posts: Getting to Know the Editor
- Content Editor Overview
- Managing Media
- Managing Comments (although for most of them the recommendation here would be 'if you're not actively managing them, disable them instead' because otherwise they end up with untrained volunteers down the track clicking on spam links)
3. Of the stuff listed in "Make It Your Own: Changing the Look and Feel of Your New Site" I think only these three are applicable:
- Theme Customizer (widgets are a bit irrelevant nowadays I think.. so maybe this should be called something different idk)
- Managing Menus (definitely)
- Selecting Plugins (definitely - and tips on choosing the best plugin for the job and how to compare them!)

With themes, we actually chose a theme and got all teams to use that. However, again, this is something that I think needs to be targeted more at the WordPress 'experts' than the charity volunteers. Which brings me to my next point...

This really needs to be two separate lesson plans. One of our major takeaways from doing it last time was that we needed more preparation/training for the WordPress 'expert' volunteers (people with prior WP experience who were donating their time to participate, as opposed to volunteers from the actual charitable organisations themselves who would ultimately be managing and maintaining the website). Having some guidelines for them - and even a series of plans for the different roles, such as project manager, designer, developer, content manager - would be an absolute must if I was ever to run one again. We had around 70 'experts' total at ours, varying from hardcore developers to freelance designers who mostly use page builders, to content writers who've only ever blogged in WordPress. All had valuable contributions and opinions but they weren't necessarily all on the same page.

I think the do_action() concept is amazing, and I know that the organisations who attended ours were super grateful and everyone had a good time, but as an organiser it was HECTIC and I also (pro-bono) ended up finishing off the majority of the sites after the event because the teams weren't organised enough and bit off a bit more than they could chew (and we started with installs ready to go, free hosting and experienced project managers). If we want more do_action() events, this Workshop SERIES needs to exist, but it needs to be a collaboration spearheaded by people who've run them before so they can compare what did/didn't work!

I sincerely hope you've enjoyed my essay, [here's my favourite cat video](https://www.youtube.com/watch?v=Awf45u6zrP0)

**Comment by kaitohm** [comment]
@jomarieminney Thank you for the great feedback!

I think a good next step here would be to create two individual Lesson Plan issues, aimed at the two audiences you've mentioned. Each GitHub issue would have its own content outline and could be worked on separately. Would you be interested in doing that? You can create the new issues from https://github.com/WordPress/Learn/issues/new/choose

_By the way, I loved the cat video 😹_

**Comment by jomarieminney** [comment]
The answer to this is "yes, but..." - I don't want to overwhelm myself and I already have a bunch of things I've committed to for Learn and Docs. Can we back-burner this until the Pathways & Mentorship project are completed?

**Comment by kaitohm** [comment]
Absolutely! What I'll do is I'll move this to the "ready to create" column. If someone else comes along in the meantime and picks it up - great! And if not, then it will be there ready for you to work on it once these other projects have been completed 😃 👍

**Comment by gusaus** [comment]
Members of the Sustainability team recently submitted a [NextGen Event format](https://make.wordpress.org/community/2023/08/30/the-nextgen-event-project-your-ideas-your-wordpress-community/) that [extends do_action](https://github.com/WordPress/sustainability/issues/21) to include a variety of training and mentoring opportunities. After the initial proposal was accepted I've been participating in a few Training Team meetings (for example https://github.com/WordPress/Learn/issues/2048) and @bsanevans has been providing valuable feedback in https://github.com/WordPress/sustainability/issues/21#issuecomment-1858693327 and subsequent comments. As mentioned in https://github.com/WordPress/sustainability/issues/21#issuecomment-1861815019 I stumbled across this issue during related conversations with @courtneyr-dev and other Training and Community team members in the #wordpress channel in [Open Collective's Slack](https://slack.opencollective.com/) before the creation of [Sustainability Team](https://sustainwp.com/podcast/episode-7-wordpress-sustainability-team/) gave me a good reason to become more active in the community.

Skimming back though this issue and comments it certainly looks (to me at least) like there's overlap/compliment with what we're trying to do (see [this section](https://docs.google.com/document/d/1CtVJZdx1oNer9FeCIROlx-IiVh1XkrDKuycdR75phfs/edit#bookmark=id.u4kwnt9c0etr) of the proposal draft for more detail).

Would it make sense to focus our discussion and collaboration here?

**Comment by kaitohm** [comment]
Sure, content creation can be discussed and tracked here 👍 

@jomarieminney You indicated interest in this issue in the past. Is this something you're available and interested in working on in the near future?

**Comment by gusaus** [comment]
Here's a summary of goals outlined in https://github.com/WordPress/sustainability/issues/21 and the [Learning and mentoring resources section](https://docs.google.com/document/d/1CtVJZdx1oNer9FeCIROlx-IiVh1XkrDKuycdR75phfs/edit#bookmark=id.u4kwnt9c0etr) of our shared doc (along with comments from @bsanevans)
- Create/extend teaching curriculum for different [teams/groups/audiences](https://docs.google.com/document/d/1CtVJZdx1oNer9FeCIROlx-IiVh1XkrDKuycdR75phfs/edit#bookmark=id.cxws8ublx2ux)
   - Program team - Assuming additional contributors would help sustain and grow the program, could we provide training and mentoring to get folks up and running?
   - Organizer team - training could vary depending on the format (in-person, virtual, hybrid, event series, etc). 
   - Nonprofit representatives - training for those managing, maintaining, and sustaining the website
   - Nonprofit build team - training for all roles referenced in the [do_action organizer guide](https://make.wordpress.org/community/handbook/meetup-organizer/event-formats/do_action-charity-hackathon/getting-particpants/#participant-roles)
- Define and document new contributor roles
  -  extend roles in the [do_action organizer guide](https://make.wordpress.org/community/handbook/meetup-organizer/event-formats/do_action-charity-hackathon/)
   - https://github.com/WordPress/sustainability/issues/2 contains a ChatGPT list of community contributor roles. If there's not yet a master list of community contributor roles residing somewhere on https://make.wordpress.org/, possibly this can be the start of another project Sustainability (and other teams) could contribute to?
- Create [learning pathways](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/) for each [contributor role](https://docs.google.com/document/d/1CtVJZdx1oNer9FeCIROlx-IiVh1XkrDKuycdR75phfs/edit#heading=h.po23kwkpbae0)
  - from @bsanevans: Training has previously helped other teams create content and publish it on Learn. We generally haven't created the content itself, but been available to help with getting content reviewed and published as Sensei content types.
  -  Looking over [Proposal: Creating Learning Pathways for Learn WordPress](https://make.wordpress.org/training/2023/04/05/proposal-creating-learning-pathways-for-learn-wordpress/) it 'seems' like this is another area where Sustainability (and other teams) could contribute
- Extend the current [Contributor Mentorship program](https://make.wordpress.org/community/tag/mentorship-program/) to include mentoring for all contributor roles
  - from @bsanevans: sounds like an exciting prospect. The team ran our pilot Course Cohort program in 2023, and we intend to continue that format in 2024. Using the curriculum made in point 2 above, the team would probably be able to assist with running cohort training sessions.
  - referencing @harishankerr's [Recap of the Contributor Working Group’s Mentorship Chat on December 21, 2023](https://make.wordpress.org/community/2023/12/28/recap-of-the-contributor-working-groups-mentorship-chat-on-december-21-2023/), as we touched on some of the same topics and there seems to be a good bit of overlap and mutual interest in collaboration.

**Comment by gusaus** [comment]
Quick elaboration on this aspect of the previous comment: 

> Create/extend teaching curriculum for different teams/groups/audiences

[This section](https://docs.google.com/document/d/1CtVJZdx1oNer9FeCIROlx-IiVh1XkrDKuycdR75phfs/edit#bookmark=id.eu677aebkbt) of our shared document references hackathons focusing on enabling organizations and contributors in specific interest areas or industry groups including:

- do_action for Publishers
- do_action for Broadcasters and Streamers
- do_action for Creative Arts and Music
- do_action for Jazz  (organizations, broadcasters, musicians, etc.) 

Considering a plugin like [Newspack](https://github.com/Automattic/newspack-plugin) can be [easily installed](https://github.com/Automattic/newspack-plugin?tab=readme-ov-file#how-to-install-newspack-on-your-site) and used as a base for all of the above, we could create and curate teaching curriculum around using and extending (and contributing back to) Newspack. 

With a growing [ecosystem](https://kinshipress.com/newspack-ecosystem/), other [event collaborators](https://twitter.com/wcpublishers/status/1701970048519201275), and a well resourced [team](https://newspack.com/meet-the-team/), we could create high impact training and even career opportunities.

 Would it be possible create specialized training around a particular setup and focus areas like this?

**Comment by gusaus** [comment]
With [project-based mentorship](https://github.com/WordPress/wp-contributor-working-group-tracker/discussions/7) being included in the [Contributor Mentorship Program Cohort #2 (2024 Q1)](https://make.wordpress.org/community/2024/01/12/call-for-mentees-mentors-cohort-2/), I added some of the above in the [project ideas discussion](https://github.com/WordPress/wp-contributor-working-group-tracker/discussions/7#discussioncomment-8098358).

And this wasn't the first suggestion related to training in that discussion!

**Comment by gusaus** [comment]
@bsanevans Thanks for referencing [this](https://make.wordpress.org/training/2023/12/22/training-team-2024-goals-setting/#comment-4115) in the [Training Team 2024 Goals Setting](https://make.wordpress.org/training/2023/12/22/training-team-2024-goals-setting/) discussion. I should point out that most of the projects/programs [outlined above](https://github.com/WordPress/Learn/issues/527#issuecomment-1881649151) are owned/managed by contributors across multiple teams and Sustainability's main role will be to explore and enable options for funding community projects, teams, working groups, and contributors https://github.com/WordPress/sustainability/issues/15
