### ISSUE TITLE
Create a Theme using a Starter Theme

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#558]
CHECKLIST: Development Checklist
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Description and Objectives finalized
- [ ] Gather links to Support and Developer Docs
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn

**Comment by annezazu** [comment]
When building this course out, it will be important to offer both a Classic and Block theme approach, since they are so wildly different. It's not clear to me at a glance which this will be for and whether it'll cover both :) Might make sense to split this in two as a result (a lesson plan for classic and a lesson plan for block).

**Comment by azhiya** [comment]
So we've got: 
- [Classic Child Theme lesson plan](https://github.com/WordPress/Learn/issues/412)
- [Child Theme for Block themes lesson plan](https://github.com/WordPress/Learn/issues/644) 
- [Child Theme for Block themes workshop](https://github.com/WordPress/Learn/issues/510)

Does it still make sense to have this open?

**Comment by annezazu** [comment]
I don't think it does!

**Comment by azhiya** [comment]
Closed as per the discussion above.
