### ISSUE TITLE
Duration is too verbose.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#60]
I don't think we need to show the duration with complete accuracy. Users can get that from the video. I see it more as a "2 min read" experience where you are just glancing at it to have a rough sense of how long it would take. 

### Screenshot
![](https://d.pr/i/8eFxT3.png)

### Solution
I think we can say:

1. Under 1 hour?
 -> "43 minutes"

2. Over 1 hour?
-> "1 Hour, 43 minutes."

3. Between 24 & 48 hours?
-> "1 day" (round up?)

_The last one may not apply._

I think we don't ever show seconds.

**Comment by coreymckrill** [comment]
@hlashbrooke Thoughts on this? The [seconds field](https://github.com/WordPress/learn/issues/35) has [been incorporated](https://github.com/WordPress/learn/pull/51), but I agree that it looks a little bit clunky like this.

**Comment by hlashbrooke** [comment]
I was picturing a display like "43:25" or something like that, but thinking about it now - that would be ambiguous without knowing if it's HH:MM or MM:SS. I think @StevenDufresne's suggestion in this issue is good - the video progress bar shows the actual time, so a more readable display in the metadata would be good.
