### ISSUE TITLE
Quiz not loading, JS error in console.

### ISSUE THREAD

**Issue by vijayhardaha** [WordPress/Learn#659]
The original issue mentioned on the forum https://wordpress.org/support/topic/quiz-doesnt-appear-in-course-getting-started-with-wordpress-get-familiar/#post-15443309

### How to reproduce the issue?
- Open the lesson page and client on **Take Quiz**.
- Page redirects to the quiz page but the quiz content is not loading.

### What I have found in debugging?
- I checked the console log there is a TypeError `Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at learning-mode.js?ver=091bd2aae0934ea8b746f893fc7bf336:1:6216`
- I checked the details js code trying to `addEvent` on `document.querySelector(".sensei-course-theme__sidebar")`
- Element with `sensei-course-theme__sidebar" class is not available in page source.

Needs testing.

**Comment by hlashbrooke** [comment]
Thanks for reporting this! It looks like the issue was caused by the fact that we had the setting enabled for Learning Mode (i.e. the new course UI) to inherit the site's theme styles - that made things look a bit better, but it caused this JS error on the quiz pages. I have now deactivated that setting and the quizzes are showing correctly.

Thanks again for reporting this!

**Comment by vijayhardaha** [comment]
Thanks, the Quizs are loading fine now. However `Uncaught TypeError: ` is still visible on quiz pages as the sidebar is tag is missing.

**Comment by hlashbrooke** [comment]
Good to know. This is all related to Sensei, so I'll report it upstream.
