### ISSUE TITLE
Getting Started With WordPress: Get Familiar - Course

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#725]
Course link: https://learn.wordpress.org/course/getting-started-with-wordpress-get-familiar/

**Comment by melbos** [comment]
Hi there I would like to report a small issue that I came a cross while reviewing available courses on Learn WP platform. In course Getting Started With WordPress: Get Familiar in the Get Found Using the Media Library Quiz for the first question  "Which of the listed image options helps both search engines and assistive technology ‘see’ your media?" there is an extra description text given for the radio button field
"Select the two that apply."
that should not be here since with radio button there is only one possible answer.
![Image](https://github.com/user-attachments/assets/b1ea0a7f-1403-41f9-9bd1-b295af0a90d5)

**Comment by kaitohm** [comment]
Thanks for reporting. This has now been fixed.
