### ISSUE TITLE
Block Locking - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#739]
# Topic Description
What is block locking? What parts of the site editor have locks? (list view, templates, reusable blocks, patterns??)

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.

- https://github.com/WordPress/gutenberg/pull/39183

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Development Checklist:
- [ ] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Create an outline of the example lesson walk-through
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Announce to the Training team
- [ ] Announce to lesson plan creator
- [ ] Announce to marketing
- [ ] Gather feedback from lesson plan users about the quality

# Repo Structure and Lesson Plan Template

> <span style="color:red">Please remove all blockquote comments such as this before publishing.</span>

## Description

> A short paragraph explaining what is covered in the lesson plan. This should be text that can be copied and used in a meetup or workshop description.

## Objectives

After completing this lesson, participants will be able to:

* Objective 1
* Objective 2

> It’s required that you include a bulleted list of objective(s) for each lesson plan. Objectives should be worded as actions that the participant can do once they’ve finished. See [Bloom's Taxonomy of Action Verbs](http://www.fresnostate.edu/academics/oie/documents/assesments/Blooms%20Level.pdf) (PDF) as a reference. Avoid using words like "know," "understand," "be introduced to," etc. There should be one assement item for each objective (see below).

## Target Audience

Who is this lesson intended for? What interests/skills would they bring? Put an "x" in the brackets for all that apply.

* [ ] Users / Content Writers
* [ ] Designers
* [ ] Developers
* [ ] Speakers
* [ ] Organizers
* [ ] Kids

## Experience Level

How much experience would a participant need to get the most from this lesson? Put an "x" in the brackets for all that apply.

* [ ] Beginner
* [ ] Intermediate
* [ ] Advanced

## Type of Instruction

Which strategies will be used for this lesson plan? Put an "x" in the brackets for all that apply.

* [ ] Demonstration
* [ ] Discussion
* [ ] Exercises
* [ ] Feedback
* [ ] Lecture (Presentation)
* [ ] Slides
* [ ] Show & Tell
* [ ] Tutorial

## Time Estimate (Duration)

How long will it take to present this lesson? Put an "x" in the brackets for the one that applies.

* [ ] 1 hour or less
* [ ] 2-4 hours (half-day)
* [ ] 5-8 hours (full-day)
* [ ] 2 days
* [ ] 3 days or more

## Prerequisite Skills

Participants will get the most from this lesson if they have familiarity with:

* Skill 1
* Skill 2

> _For example:_
>
> *   Experience with HTML and CSS
> *   Completed the Basic WordPress Concepts lesson

## Readiness Questions

* Question 1
* Question 2

> A list of questions for participants to see if they have the background and skills necessary to learn and understand the lesson.
>
> _For example:_
>
> *   Do you want to makes changes to your theme yourself?
> *   Do you know how to write CSS?

## Slides

> Change the `/repo-name/` in the link to match the URL name of this repo.

*   [Slides](https://wptrainingteam.github.io/lesson-plans/repo-name/slides/) (files included in this repo)

## Materials Needed

* Item 1
* Item 2

> A list of files, resources, equipment, or other materials the presenter will need for the lesson.
>
> _For example:_
>
> *   A local install of WordPress
> *   The files for the TwentySixteen theme

## Notes for the Presenter

* Note 1
* Note 2

> A list of any handy tips or other information for the presenter.
>
> _For example:_
>
> *  Participants may need to download the TwentySixteen theme before beginning
> *  What to do if there’s no projector or internet available
> *  What to do if a participant doesn’t have the necessary set up
> *  How to handle different opinions about the topic

## Lesson Outline

* First do this
* Then move on to this
* Finish with this

> The plan for the lesson. Outline form works well.
>
> _For example:_
>
> * Talk about what a theme is
> * Demonstrate how to install and activate a theme
> * Practice exercises to have participants find and install a theme on their own site

## Exercises

**Exercise name**

Short description of what the exercise does and what skills or knowledge it reinforces.

*   Short point or step of the exercise
*   And another one

> These are short or specific activities that help participants practice certain components of the lesson. They should not be fully scripted exercises, but rather something that participants could do on their own. For example, you can create an exercise based on one step of the Example Lesson.

## Assessment

There should be one assement item (or more) for each objective listed above. Each assessment item should support an objective; there should be none that don't.

**Write out the question.**

1.  Option
2.  Option
3.  Option
4.  Option

**Answer:** 3\. Correct answer

> A few questions to ask participants to evaluate their retention of the material presented. They should be a measure of whether the objectives were reached. Consider having a question for each objective.

## Additional Resources

* Resource 1
* Resource 2

> An optional section which can contain a list of resources that the presenter can use to get more information on the topic.
>
> _For example:_
>
> * Link to information on the Codex
> * Theme Review Team's Handbook

## Example Lesson

> An example of how the lesson plan can be implemented. Written in script form as one possible way an presenter might use this lesson plan at an event, with screenshots and instructions if necessary.

### Section Heading for Example Lesson

> You will likely need to break the Example Lesson down into multiple sections.

### Lesson Wrap Up

![](https://raw.githubusercontent.com/wptrainingteam/contributor-resources/master/images/lightbulb.png) Follow with the [Exercises](#Exercises) and [Assessment](#Assessment) outlined above.

**Comment by caraya** [comment]
I want to take a shot at writing the lesson plan

**Comment by caraya** [comment]
Ready for Review

**Comment by abhansnuk** [comment]
Under things like 'Experience level', it says put an 'x' in the boxes. In GitHub and on Learn WP, it is a tick. So we will need to change this on this and other lesson plans.

**Comment by azhiya** [comment]
Hi @caraya do you have the link to the lesson plan?

**Comment by caraya** [comment]
@azhiya 

https://learn.wordpress.org/wp-admin/post.php?post=18084&action=edit

**Comment by azhiya** [comment]
Looking good @caraya. Thank you so much for adding alt text to the images. 
You might want to highlight the menu items like this for example: https://learn.wordpress.org/lesson-plan/templates/ in the screenshots for the: 
- Group block under preparing content 
- Lock option for the first screenshot under Locking movement
- Lock and Drag handles in Testing movement lock

**Comment by caraya** [comment]
Question, do we add the images to the media library in the learn.wordpress repo? Right now they are linked to an external site

**Comment by azhiya** [comment]
Please add it to the media library and set to full size for optimal display.

**Comment by caraya** [comment]
I updated the images as suggested

**Comment by abhansnuk** [comment]
It is looking good.

Under presenters notes, suggest a slight tweak of the first two bullet points:
- from "While we can lock specific blocks in the theme, it should be possible for other developers working on the same theme to undo the locks" to "We can lock specific blocks in the theme, it should be possible for other developers working on the same theme to undo these locks."
- from "We ask for a specific theme so we can all be on the same page rather than having to figure out what each theme is doing" to "In this lesson plan, we ask for a specific theme so that we can all work on the same theme for ease."

- There is a dev note on block locking, can this be linked from the lesson plan? Apologies if it is already and I missed it.

**Comment by caraya** [comment]
@abhansnuk 

I incorporated the requested changes.

**Comment by webtechpooja** [comment]
Hi @caraya,

It looks excellent and very well explained. However, I think we can remove the Q&A point from the lesson outline, as you are covering this under assessment. Is there anything else regarding the Q&A section that I am missing?

The lesson outline section is not clear to me. Few points are short written and not self-explanatory. I think It needs more explanation to avoid confusion.

**Comment by caraya** [comment]
> Hi @caraya,
> 
> It looks excellent and very well explained. However, I think we can remove the Q&A point from the lesson outline, as you are covering this under assessment. Is there anything else regarding the Q&A section that I am missing?
It is a place for people to ask questions if they still have any. I make it explicit at the end of all the sessions I create to tell participants that we've set time aside at the end. This is different than assessments but I can see where it would be confusing

> 
> The lesson outline section is not clear to me. Few points are short written and not self-explanatory. I think It needs more explanation to avoid confusion.
Which of the outline points do you think needs further expansion?

**Comment by webtechpooja** [comment]
@caraya, I think the introduction points need more clear explanation. 
What does it cover and why do we include this in the outline section. It would be great if we can do something to make it more clear. As I think if I am getting confused by these points, someone may get the same confusion.

**Comment by caraya** [comment]
> @caraya, I think the introduction points need more clear explanation. What does it cover and why do we include this in the outline section. It would be great if we can do something to make it more clear. As I think if I am getting confused by these points, someone may get the same confusion.


Does it make more sense now? Is this the change you had in mind?

**Comment by webtechpooja** [comment]
@caraya, Now looks good to me. My suggested changes are done.
Thanks

**Comment by westnz** [comment]
Hey @azhiya, seems like this Lesson Plan can be published. 🥳

**Comment by azhiya** [comment]
Scheduled to publish later on today.

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/pull/40263 - nested or inherited block locking

**Comment by courtneyr-dev** [comment]
Include https://make.wordpress.org/core/2022/07/20/whats-new-in-gutenberg-13-7-20-july/#lock
https://github.com/WordPress/gutenberg/pull/41876

**Comment by courtneyr-dev** [comment]
Visuals: [video of exploring a pattern with content lock](https://drive.google.com/file/d/1ofh-A2bwzPazbgUZZpaAI4rIr180_x5i/view?usp=sharing).

Code example: Example of code [found here under Testing Instructions](https://github.com/WordPress/gutenberg/pull/44131).

Adoption approach: Opt-in. Please review the [documentation here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/inner-blocks/README.md#templatelock).

Initial [Add: Content lock ability](https://github.com/WordPress/gutenberg/pull/43037) which introduces the ability to lock blocks in this way. 
[Follow up PR that changed the value](https://github.com/WordPress/gutenberg/pull/44131) to use from noContent to contentOnly.
[Post from Rich Tabor about how to use this feature](https://richtabor.com/content-only-editing/).

**Comment by courtneyr-dev** [comment]
To learn more about locking, please review this [broader resource on curating the editor experience](https://developer.wordpress.org/block-editor/how-to-guides/curating-the-editor-experience/). 

Visuals: [image showing the option](https://drive.google.com/file/d/1QICXKoof-2UuSBB5qtYNpp3a5JG9tnnO/view?usp=sharing) to apply to all inner blocks. 

Adoption approach: n/a

Key Make Posts/GitHub/Trac Issue(s): [Block Locking: Add the 'Apply to inner blocks' option](https://github.com/WordPress/gutenberg/pull/41876#top)

**Comment by Piyopiyo-Kitsune** [comment]
I see @caraya is noted as the assignee-- will they be working on these revisions or do we require re-assigment here?

**Comment by caraya** [comment]
> I see @caraya is noted as the assignee-- will they be working on these revisions or do we require re-assigment here?

I'll work on this after I get done with theme.json

**Comment by caraya** [comment]
@courtneyr-dev 

I don't have access to the extended draft plugin for this post. Should I revert it back to draft? or post the update here as an attachment?

**Comment by caraya** [comment]
I've copied the text of the updated content and attached it to this comment for review. Don't want to make changes to the published content until the updates have been approved. 

# Block Locking Updates WordPress 6.1

The following features related to block locking were introduced in WordPress 6.1.

## Block Locking UI Changes for group block

Locking all children of a group element means that the UI for locking group blocks changed slightly to accommodate the new functionality in blocks that need it.

When locking content in a group or other container, you now have the option of applying the same settings to all the children blocks inside the container

<figure>
  <img src='https://learn.wordpress.org/files/2022/12/block-locking-group-locking-0.png' alt='Block Locking UI' width='800' >
  <figcaption>Block locking UI showing the toggle to apply to all blocks inside the container</figcaption>
</figure>

## Locking content inside container block

<figure>
  <img src='https://learn.wordpress.org/files/2022/12/block-locking-new-setting.png' alt='Block Locking UI' width='800' >
  <figcaption>Block locking UI showing the toggle to apply to all blocks inside the container. The toggle button to apply changes to all blocks is highlighted in red</figcaption>
</figure>

Because now we can choose whether to apply the locks to a group's child elements, there are additional considerations that we need to keep in mind

### Where you make the changes matter

If you make the changes to an individual block then the blocks apply only to that block, regardless of the parent container.

<figure>
  <img src='https://learn.wordpress.org/files/2022/12/block-locking-individual-block.png'
  width='800'>
  <figcaption>Block locking settings for an individual block. These settings will only apply to a single paragraph.</figcaption>
</figure>

Likewise, if you lock the containing group block and apply the lock to all blocks inside, the same settings will be applied to all blocks.

<figure>
  <img src='https://learn.wordpress.org/files/2022/12/block-locking-group-locking-0.png' alt='Block Locking UI' width='800' >
  <figcaption>Block locking UI showing the toggle to apply to all blocks inside the container</figcaption>
</figure>

To change the behavior of individual items inside a group, you need to work on the block you want to change individually either in the list view or in the editor.

## Block Lock Status in List View

You can see whether a block is locked in the list view. Locked blocks have a padlock icon to the right.

<figure>
  <img src='https://learn.wordpress.org/files/2022/12/block-locking-group-locking.png' width='800'>
  <figcaption>List View showing an example of a group block and its children being locked</figcaption>
</figure>


However, we only know that the block is locked. We can't tell if the block was part of a group block that was locked together with the parent or if it was locked independently.

## Benefits for theme developers

The ability to lock blocks from being moved or deleted presents an interesting possibility.

Locking blocks means that people with fewer permissions cannot change or remove the locks but they can edit the content of the blocks but not move or delete them.

There is also an option for `content-only editing` that would combine locking the status of child blocks with removing styling options. Rich Tabor documents it in [How to simplify WordPress patterns with content-only block editing](https://richtabor.com/content-only-editing/) but it is offered as additional material for your review since it's beyond the scope of this lesson plan.

[block-locking-updates-wordpress-61.md](https://github.com/WordPress/Learn/files/10297684/block-locking-updates-wordpress-61.md)

**Comment by kaitohm** [comment]
@caraya I've reviewed these changes, and they look good to me. Feel free to publish the changes and close this issue 👍
