### ISSUE TITLE
Review CSS oddities

### ISSUE THREAD

**Issue by tellyworth** [WordPress/Learn#746]
Following #745 there are a few CSS quirks that should probably be cleaned up. Nothing is broken but it's a bit weird, I'm opening this issue as a reminder for someone to look into it at some point. For example:

* The `h3` tag in that PR has no styles targeting it now
* Code like `<h3 class="... h4">` is confusing and makes it hard to know what's intended
* There are other examples like that elsewhere in templates also

**Comment by StevenDufresne** [comment]
This is a common pattern for CSS libraries. It allows the decoupling of CSS from markup. Should the markup change, and headings change frequently, the CSS does not need to be updated.

Here's how [bootstrap](https://getbootstrap.com/docs/4.0/content/typography/) explains it:

> .h1 through .h6 classes are also available, for when you want to match the font styling of a heading but cannot use the associated HTML element.

The alternative is to introduce classes like `title` or `subtitle` and style them relative to a parent container but that in itself has drawbacks. 

I would always suggest avoiding styles like:

```
.container h2 {
 //...
}
```

**Comment by outdoor2kode** [comment]
Here are things I found for this issue:
1. We can see from the [screencast](https://d.pr/v/49HXxO) that after the change in #745, the style was fixed, which means that originally the style was off and through the clip, it shows that it's messed up by the sensei-lms plugin. The CSS style of the plugin is probably too loose so it affects the style here.
2. No corresponding CSS style for class `card-title`, and both classname `card-header` and `card-entry` have no effect on the final layout.

Since it's important to have the [structural hierarchy](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/HTML_text_fundamentals#why_do_we_need_structure) and `.h1 through .h6 classes are also available, for when you want to match the font styling of a heading but cannot use the associated HTML element.` mentioned by @StevenDufresne. I'd suggest removing the class `h4` and coding the required style in `card-title`.

However, as @tellyworth said `There are other examples like that elsewhere in templates also`. If there are too many other cases out there and somehow it seems not that easy to solve all of them with some simple changes (probably affect too many other associated files), It would be better to leave this issue alone for the moment as the layout seems to have no big problems, and the CSS strategy is not that consistent throughout the whole codebase - it's a mix of the use of different CSS strategies. We can circle back to this issue when we have a unified CSS strategy for this project.

**Comment by jonathanbossenger** [comment]
Hi folks. Given that the entire .org project is undergoing a redesign, which will soon affect Learn WordPress, I'm inclined to close this issue at this time.

Does anyone disagree with that course of action?

**Comment by outdoor2kode** [comment]
I'm fine with closing this issue now, seeing no problem on my side.

**Comment by jonathanbossenger** [comment]
@tellyworth @StevenDufresne I'm going to close this out, feel free to reopen if you think it's necessary.
