### ISSUE TITLE
What is the difference between the Block Editor and Site Editor

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#750]
//tutorial

**Comment by westnz** [comment]
Please review the [workshop](https://wordpress.slack.com/archives/C02RW657Q/p1650879751850259) by Tuesday, 3 May.

**Comment by westnz** [comment]
https://wordpress.slack.com/archives/C02RW657Q/p1650879751850259

**Comment by westnz** [comment]
Published Workshop: https://learn.wordpress.org/workshop/understanding-the-page-editor-vs-site-editor/

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/6c0f431e-7ab9-4ddc-9092-2222de7272fe

**Comment by digitalchild** [comment]
Once again, a great tutorial and overview of the differences between the page editor and site editor. 

At 9:35 you outline how to apply a template to a particular page. It might be worth mentioning that this can also be accessed from the quick edit menu for the page on the list table. Which can be faster than loading the block editor just for applying a template.

**Comment by westnz** [comment]
Thanks @digitalchild 🦾

**Comment by SierraTR** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [ ] Learning outcomes/objectives are clear.
- [ X] Technical concepts introduced in the content are accurate.
- [X ] The speed of demonstrations are easy to follow.
- [X ] The narration audio matches what is shown visually.
- [ X] Spelling and grammar are correct.
- [X ] Sound quality is consistent throughout the video.
- [ X] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ X] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

This one hits one of my 'Hot Buttons".

At 1:00 you say that the 'Page Editor' is for adding content to your pages and posts.  Why is this editor not referred to as the "Content Editor"? Is it not used to add content? Isn't everything that is added to a post or page using this editor displayed within the "Content Block" And yet we refer to this editor as the page editor? Where is the post editor? Why are we confusing new users who don't know what a post and page are and implying that there might be something else they are to use for posts?  </rant>

Personal opinion, change the title to ...Content editor and Site Editor and change the references within the narrative.

Otherwise, good job with a potentially very confusing topic for new users.

**Comment by westnz** [comment]
Thank you for the review @SierraTR 🙏

**Comment by westnz** [comment]
Hey @annezazu! Could you confirm what is the best way to refer to the Page Editor?  Please see the above review.  Your input will be appreciated. As you know all the 'editors' can become confusing...

**Comment by annezazu** [comment]
Hello! Deep apologies for the delay here. I simply did not get to this in time. This is a great question and excellent feedback. It hits at the heart of this "in between" stage we are somewhat in in different places. For example, right now, you can create pages in both the broader wp-admin experience and in the Site Editor. You can't create posts though! Where does this leave us when, in time, the Site Editor should start to "house" more of these actions folks want to take? 

I think for now, we do need resources to help distinguish the difference though. For now, I'd go with "block editor" vs "site editor" as that matches the documentation: https://wordpress.org/documentation/article/wordpress-block-editor/ This may also be a perfect convo to have with folks on the documentation team as this impacts their resources. From a marketing point of view, a lot of work has been put into "block editor" so it might be worth keeping that purely for SEO/brand awareness for now. We also regularly talk about how the site editor brings the block editing experience to your entire site which matches the "block editor" phrasing.

**Comment by westnz** [comment]
That is very helpful. Thank you so much for your feedback. ❤️

**Comment by westnz** [comment]
Published in Sensei as part of the draft Beginner User learning pathway.
