### ISSUE TITLE
Course: Using the WordPress Data Layer

### ISSUE THREAD

**Issue by azhiya** [WordPress/Learn#763]
Turning the Handbook tutorial for [Create your First App with Gutenberg Data](https://developer.wordpress.org/block-editor/how-to-guides/data-basics/) into a course on LearnWP.

The initial draft  by Adam Zielinski
1. Needs assessment statement
-It is nearly impossible to create, read, update, and delete WordPress data from Javascript. All the tools are there, but we do not explain extenders how or why they can use them. As a result, developers must either figure it out on their own, or reimplement these tools from scratch.
2. the target audience
-Intermediate to advanced developers who create WordPress plugins and themes that need to interact with the WordPress REST API
3. a course-level objective (big, abstract instructional goal)
-Learn how to extend WordPress faster by delegating common data-related tasks to WordPress data layer.
4. more specific learning objectives.
-Understand what WordPress data layer can help you with.
-Learn to create, read, update, and delete WordPress data using the provided Javascript utilities.
-Understand the most important resolvers, selectors, and actions provided by WordPress.

**Comment by azhiya** [comment]
The [initial discussion on Slack](https://wordpress.slack.com/archives/C02RW657Q/p1652358110293809) 
@adamziel  will be working on this

**Comment by westnz** [comment]
Updated conversation: https://wordpress.slack.com/archives/C02RW657Q/p1654354018589179

**Comment by westnz** [comment]
Herewith is an updated and fleshed-out version of the:

1. Needs assessment statement
2. The target audience
3. A course-level objective (big, abstract instructional goal)
4. Specific learning objectives.

https://docs.google.com/document/d/1na51OfpLmdGBstwrxVPxXK1XT6G9uasRtxqO9MWK-vE/edit#heading=h.lhx5kjxe3rft

@adamziel You have done an excellent job here!  You have clearly outlined the learning objectives and how learners will be able to see if they have met these objectives. I look forward to seeing the course take shape!

**Comment by westnz** [comment]
A cool quote I thought I'll share: Wiggins and McTighe say, “Teaching is a means to an end. Having a clear goal helps us, educators, to focus our planning and guide purposeful action toward the intended results.”

**Comment by westnz** [comment]
Update: All five parts of the tutorial have been moved to Sensei. Adam will now start adapting them to the course format. 

https://learn.wordpress.org/wp-admin/post.php?post=20048&action=edit

**Comment by westnz** [comment]
Review: 22/08/2022

**Introduction:**

I like the image you have used so that learners can see an example of what they are working towards. The image is not that clear to me.  You could try first adding it to the Learn Media Library and then inserting it to improve image quality. 

I would suggest adding a bit more detail in the introduction - laying out the learning journey. I think you can also touch on why this course came about and how it would benefit learners. 

**Setting up your development environment:**

I am glad you mentioned recording some videos as I think the multimedia approach would be helpful. 

You wrote: _"We'll do all the development inside of a WordPress plugin. Let's start by creating a wp-content/plugins/my-first-gutenberg-app directory in your local WordPress environment. We will need to create four files inside that directory:"_ Would it be helpful to provide some more context here and explain how to do this or would somebody at this level definitely know how to create these files? 

**Retrieving data records**

I like the Reflections you have added to the lessons + the way you ask questions to engage the learner. 

_Step 3. Turn the list into a table._  I was wondering why there is no explanation or text?

The quiz questions in between steps work well.

Great lesson - you've systematically taken the learner through all the steps.  You also gave them time to pause and think about what they are doing.

**Editing WordPress data records & Creating new WordPress data records**

Awesome that you are showing them a glimpse of what they're going to build - and the way you shared all the code at the end to summarise. I also think the conversational style you use throughout the tutorial works very well. 

All the steps in both lessons flow well together.

**Deleting WordPress data records**

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/89751452/186031762-98e90428-6477-4776-9903-29ec6b8b4eb7.png"> What about block themes?

**Final thoughts:**

It is great how you encourage the learner throughout the tutorial.

Question, are there some areas where more screenshots would benefit visual learners?

Another question, are there more lessons coming?  If not, it would be nice to write a final paragraph about the fact that the tutorial is finished and congratulate learners for completing all the tutorial. 

Fantastic work @adamziel!!

**Comment by adamziel** [comment]
Thank you so much for reviewing @westnz! 🎉 

> The image is not that clear to me. You could try first adding it to the Learn Media Library and then inserting it to improve image quality.

I just uploaded all the images to the media library, how does it look like to you now? I noticed a few of them are not crispy on retina, I could re-take those screenshots.

> I would suggest adding a bit more detail in the introduction - laying out the learning journey. I think you can also touch on why this course came about and how it would benefit learners.

I expanded that section more – what do you think now?

> You wrote: _"We'll do all the development inside of a WordPress plugin. Let's start by creating a wp-content/plugins/my-first-gutenberg-app directory in your local WordPress environment. We will need to create four files inside that directory:"_ Would it be helpful to provide some more context here and explain how to do this or would somebody at this level definitely know how to create these files?

I do expect people to know how to create them, but I added a note about how this course requires knowledge of WordPress plugins.

> <img alt="image" width="1006" src="https://user-images.githubusercontent.com/89751452/186031762-98e90428-6477-4776-9903-29ec6b8b4eb7.png"> What about block themes?

Oh that's just a snackbar example. I replaced that screenshot with the page editor to be less confusing

> Question, are there some areas where more screenshots would benefit visual learners?

I'm not sure – there's plenty of screenshots already! What do you think?

> Another question, are there more lessons coming? If not, it would be nice to write a final paragraph about the fact that the tutorial is finished and congratulate learners for completing all the tutorial.

There are more lessons coming! Should I make a note about that at the end?

**Comment by westnz** [comment]
Hey @adamziel 

The image looks much better and great work on adding a solid introduction.

Thank you for the other updates and responses as well.

I am happy with the number of screenshots you have used.  I just wanted to check if you thought there might be some areas that could be supported by more visual material.  If you think there is enough, all good!

Yes, please remember to write a conclusion at the end. I know you would've done that in any case, but I was unsure how many more lessons you were going to add. 

💪

**Comment by adamziel** [comment]
Actually, more lessons might be better suited for a follow-up course. Let's keep this one concise, it already covers plenty of material. I drafted a conclusion in here:

https://learn.wordpress.org/wp-admin/post.php?post=22512&action=edit

How do you like it @westnz ? Are we good to launch?

**Comment by westnz** [comment]
Hey @adamziel 

Sounds great!  The conclusion you have written is perfect.

Let's move ahead with the review process then.

Firstly, if you publish the course, but don’t “feature” it, it doesn’t display on the front end of Learn WordPress. It will be publicly available, but only if you have the link – featuring it makes it appear on the site and also posts it to Training Team channel. It will be useful for “soft launching” the course, to allow folks to review it and provide feedback. 

Once you publish (without featuring it), can I share the link with the Training Team for feedback and in .Org for a technical review by the dotorg-tech-review group?  I was wondering if someone in your team would also be willing to review it and go through the course as a student?

Can we ask folks to complete the review by the end of next week, or the week after?  Let me know if you are happy with this as well as the proposed deadline for feedback.

Lastly, you mentioned, "by the way, once the first version goes out, I’m happy to record some videos to support it".  Are you still keen to work on this once the text-based part is published and live?

Thank you for all the hard work you have put into this course so far!

**Comment by adamziel** [comment]
> Firstly, if you publish the course, but don’t “feature” it, it doesn’t display on the front end of Learn WordPress. It will be publicly available, but only if you have the link – featuring it makes it appear on the site and also posts it to Training Team channel. It will be useful for “soft launching” the course, to allow folks to review it and provide feedback.

Perfect, I just did that!

> Once you publish (without featuring it), can I share the link with the Training Team for feedback and in .Org for a technical review by the dotorg-tech-review group? I was wondering if someone in your team would also be willing to review it and go through the course as a student?

Yes please! Here's the link: https://learn.wordpress.org/course/wordpress-data-in-javascript/

> Can we ask folks to complete the review by the end of next week, or the week after? Let me know if you are happy with this as well as the proposed deadline for feedback.

That sounds perfect.

> Lastly, you mentioned, "by the way, once the first version goes out, I’m happy to record some videos to support it". Are you still keen to work on this once the text-based part is published and live?

Absolutely!

Thank you @westnz and let me know how will the review go!

**Comment by westnz** [comment]
Thank you @adamziel 

I am just going to wait a day or two as we have just asked for feedback for another course as well! 👍

**Comment by westnz** [comment]
Please note:

A technical review was done by @getdave, as well as, @draganescu and @scruffian whilst the course was created.

**Comment by getdave** [comment]
> A technical review was done by @getdave, as well as, @draganescu and @scruffian whilst the course was created.

Just to note that I haven't performed any review on the Learn WordPress course itself. Just the original content that went into the Gutenberg repo.

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/course/using-the-wordpress-data-layer/

**Comment by pbrocks** [comment]
@adamziel @westnz  I reviewed the course and found it to be a great piece of work expanding on the Gutenberg App created in the examples plugin. I was especially impressed by the error handling information. However, there were some errors in the code and typos that could be corrected. Is there a repo for this or some other way to send my comments?

**Comment by westnz** [comment]
Howdy @pbrocks!  Thank you so much for reviewing the course. You are welcome to post your feedback here in any format that suits you best.  You can add a link to a Google doc if you prefer.  Many thanks

**Comment by jonathanbossenger** [comment]
This course has been published, so closing this ticket. If there is any other feedback, I suggest we open new issues. 

https://learn.wordpress.org/course/using-the-wordpress-data-layer/
