### ISSUE TITLE
Course Development Handbook Guidelines

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#778]
**The Issue**
People want to create courses of their very own, but there isn't clear documentation to create it. 

While there are many learning course/unit plan designs out there, none address the unique and wonderful need of bringing in the greater community into account.

**The Process**
@wparasae and @jonathanbossenger have picked up a big task of developing a course on Low-Code Block Theme. As they work on this course, they will also create a replicable process to empower community members to create collaborative courses of their very own. This process will be based loosely upon the Understanding by Design Framework with an eye towards bringing in the greater community.

**The Steps [Subject to Change]**

- [ ] [Chaotic brainstorm](https://docs.google.com/document/d/1zv0QcW305ayObJ0Tbok9CMdnuIBWEjVBA4955qsOKgw/edit?usp=sharing); what is the first thing someone should do when deciding what a course should be?
- [ ] Tracking - Create Github Template for Course Proposals
- [ ] Documentation - Develop documentation on each step of the process
> - [ ] Overall Unit / Course Objectives
> - [ ] Overall Unit / Course Audience
> - [ ] Getting Community Feedback
> - [ ] Finding Existing Resources on learn.wordpress.org
> - [ ] Develop a course outline
> - [ ] Gathering feedback on outline (is this a necessary step?)
> - [ ] Creating & Linking Lesson Plans to Course Outline (Need to decide best practices on this)
> - [ ] Writing Course Text + Creating Course Videos (Need to decide how to embed these within lesson plans)
> - [ ] Course Review Process: Revision + Community Feedback
> - [ ] Course Review Process: Accessibility Checklist (Alt Text, Captions, etc.) 
> - [ ] Course Editing: Style Guide + Community Review
> - [ ] Publishing the Course
- [ ] (Maybe) Course Creation: Walkthrough Process for Contributors

The more I look at this, the more I wonder if a course that walks folks through course creation would be helpful rather than creating a TON of documentation. I will brainstorm on this and decide if it needs a P2 for commenting / Slack meeting. More wild and crazy ideas. :D

**Comment by kaitohm** [comment]
@wparasae @jonathanbossenger Now that the Low-Code Block Theme courses are out, do you have any updates on this project? 😃 

I am also noting #828 and #1452 seem to be related to this issue.

**Comment by jonathanbossenger** [comment]
I think that the process of creating a course, like a tutorial, is different from person to person, and course to course.

So instead of creating detailed documentation, we should rather create a set of guidelines, similar to our [tutorial guidelines](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial/), that cover the high-level things to remember when creating a course, based on the items in the new [course issue checklist](https://github.com/WordPress/Learn/pull/1452).

We can then iterate on those guidelines, and the checklist, over time. 

@wparasae if it's ok with you, I'll start by working on a draft proposal for a set of guidelines to be included in the training team handbook, and share it here for review, before publishing it to the training team blog for further team input.

**Comment by wparasae** [comment]
I really like this idea--rather than it being a prescribed, rigid way, guidelines might provide the needed structure without limiting people's creativity. Let's do it!

**Comment by kaitohm** [comment]
I love the idea also. Thanks to both!

**Comment by jonathanbossenger** [comment]
Most of the ideas and concepts around this have been published in the guidelines for creating [Lessons](https://make.wordpress.org/training/handbook/lessons/), so I'm going to close this out for now
