### ISSUE TITLE
Building a homepage with a block theme - Workshop

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#788]

**Comment by westnz** [comment]
Here is the link to the video: https://wordpress.slack.com/archives/C02RW657Q/p1656902943468929

**Comment by amitpatel0702** [comment]
Hi @westnz,

- You precisely mentioned the agenda/outlines of the workshop.
- You followed the perfect flow for setting a static home page. Navigations/Modules --> Settings --> Header/Footer --> Home page.
- You did a great job by including all crucial aspects in a brief video a making it look very simple and easy to understand.

**A Suggestion:** Can we include a video in form of an attachment and in form of a clickable video as compared to a slack link in order to increase reachability? I hope it makes sense.

Thanks for posting such a helpful video to create a home page with a block theme.

**Comment by westnz** [comment]
Thank you for the feedback @amitpatel0702. Unsure what you are suggesting. Sorry 🙈 Once the review is done, it will be published on learn.wordpress.org for anyone to access.

**Comment by amitpatel0702** [comment]
Thanks @westnz, If i speak with other words, instead of mentioning a video link https://wordpress.slack.com/archives/C02RW657Q/p1656902943468929 as above, is it a good to include the same video in form of a locally uploaded mp4 file uploaded into the content box above? I hope that makes sense.

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/177080881-e81f47a1-073b-463d-8ed9-409e10283737.mp4

**Comment by westnz** [comment]
Thanks @amitpatel0702 That was the original plan, but it was too big.  I have used Handbrake to resize it.

**Comment by amitpatel0702** [comment]
Completely understand @westnz, Thanks for your great efforts and making it happen. It is definitely going to help reviewers to access it directly and after publishing, it's going to help WordPress techies lots.

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/building-a-home-page-with-a-block-theme/
