### ISSUE TITLE
Managing Updates - Tutorial (Brazilian Portuguese)

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#862]

**Comment by westnz** [comment]
Here is the link to the video: https://wordpress.slack.com/archives/C02RW657Q/p1658761265345359

**Comment by paulopmt1** [comment]
Great material! It was a good idea to talk about backups before updating the website!



1. A little problem here:

![image](https://user-images.githubusercontent.com/1044309/181348753-0488fd42-28ac-4088-9107-a297d7b86596.png)

Instead of `Backup é um procedimento que realizar uma cópia...` it should be `Backup é um procedimento que realiza uma cópia`. Just an `r`.

I would suggest rewriting the phrase with: `Backup é um procedimento que realiza uma cópia do seu site numa data particular e a mantém num local seguro`.

**Comment by fellyph** [comment]
Hey @paulopmt1,

About talking about backup coming after showing the dashboard, I was following the English Workshop structure. I can try to edit it and see if it makes sense. If not, I will need to rerecord it.
And about the slide, I can change it quickly.

Thanks!

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/gerenciando-atualizacoes-no-wordpress/

**Comment by paulopmt1** [comment]
Great job @fellyph and @westnz!
