### ISSUE TITLE
Review theme requirements - Lesson

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#868]
# IMPORTANT
**This lesson plan belongs to part of a greater course, [Extend a Low Code Block Theme](https://github.com/WordPress/Learn/issues/821) which depends on the completion of  [Create a Custom Block Theme #1](https://github.com/WordPress/Learn/issues/631)**

**Please reach out to @jonathanbossenger (Jonathan Bossenger) in the #training team Slack if you would like to help with this lesson plan.**

# Topic Description
The goal of this lesson is to review the basic requirements for setting up a new block theme, covering these three lessons from the first course

- [Creating Your Block Theme's style.css](https://github.com/WordPress/Learn/issues/835)
- [Creating Your Block theme’s index.php](https://github.com/WordPress/Learn/issues/836)
- [Your Block Theme’s theme.json ](https://github.com/WordPress/Learn/issues/837)

# Objectives
After completing this lesson, participants will have completed a refresher of the basic theme requirements of a block theme.

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Lesson for review: 

[Block Theme Requirements: A Review](https://learn.wordpress.org/lesson/block-theme-requirements-a-review/)

## Review checklist

Reviewers: this is not an extensive list, but it would be helpful if you can keep the following questions in mind while reviewing.

1. Are there any spelling/grammar issues or anything that doesn't make sense?
2. Is the content technically correct?
3. Does the layering of information successfully build from lesson to lesson
4. Can you follow the steps outlined in the course
5. Does the lesson contain enough relevant links to documentation (WordPress documentation, or any other relevant documentation)

**Comment by jonathanbossenger** [comment]
[Module 01: Lesson 01 - Block Theme Requirements: A Review](https://github.com/jonathanbossenger/block-theme-course/blob/main/module-01/01-Review-Block-Theme-Basics.md)

**Comment by jonathanbossenger** [comment]
Suggested improvements:

1. Add links to the documentation for more technical information
2. Link back to the relevant modules on the [Create a Block Theme (Low-Code)](https://github.com/WordPress/Learn/issues/631) course

**Comment by westnz** [comment]
### Feedback - Block Theme Requirements: A Review

I assume the introduction to the course is still being developed? I think it is great how you jump straight into the lesson and content. You grab the attention of the learner immediately. I get that feeling of 'let's go!'

The sub-headings are very effective.  As a non-developer, even I can follow the requirements step-by-step. 

I was wondering if Note and Do (throughout the course) can be in different colours to make them stand out more. 
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/89751452/192637672-cca13239-3dc0-4d57-9d8b-ee7831d4f335.png">

I like how you already set up the next lesson at the end. 

**Spelling**
In the first paragraph below theme.json - fix the spelling of useful.

**Comment by jonathanbossenger** [comment]
Hey @westnz, thanks for the review feedback

> I assume the introduction to the course is still being developed?

There is actually already a [start of an introduction](https://github.com/jonathanbossenger/block-theme-course/blob/main/01-Introduction.md) here, but I plan to revise it once the first 4 modules are complete.

> I was wondering if Note and Do (throughout the course) can be in different colours to make them stand out more.

Sadly this is one limitation of making this available for early review via GitHub, we don't have the same tooltips/callouts that we do on Learn. However, I plan to use the same callouts with different icons/colors that @wparasae is using for her course.

> fix the spelling of useful.

Done, thanks.

**Comment by annezazu** [comment]
My only piece of feedback when reviewing this is to think about how to incorporate mentioning the Create Block Theme plugin. Perhaps at the end after mentioning all of this requirements, you can mention it as a tool to consider after this:

>You can read more about the minimum requirements for setting up a Block Theme in the section on [Block Themes](https://developer.wordpress.org/themes/block-themes/block-theme-setup/) in the Theme Handbook.

**Comment by jonathanbossenger** [comment]
Thanks for the feedback @annezazu 

One of the early pieces of feedback I received from a developer/training team member when I was putting the outline of this course together is not to rely too much on "external dependencies" for the completion of this course. 

I tend to agree with that statement, to some degree, and so I'm trying to balance teaching block theme development to someone who just has a local WordPress install, and a text editor, without needing to rely on Create Block Theme.

That being said, I'm a big fan of using the plugin myself, so perhaps it would be beneficial to have a discussion about how much one can rely on the plugin being around for the long term, or the functionality eventually being merged into core?

**Comment by annezazu** [comment]
Very true! I could see this evolving as time goes on and the Site Editor tools themselves become more advanced. At the least, you could mention it and link off to here: https://developer.wordpress.org/themes/basics/tools-resources/

**Comment by wparasae** [comment]
**Feedback for Module #1**
I really appreciate how well this first module builds on the beginner-level course I'm working on -- you're definitely covering everything needed, but keeping it brief enough to engage folks who are familiar with this. Bravo!

I especially like your use of terminology. Since this is a review, I'm able to make connections between the elementary-level that I understand as a new developer and a more advanced one because of the language you're using. Well done!

I have three tiny changes (typos and like... two sentences, basically!) 

1. Are there any spelling/grammar issues or anything that doesn't make sense?
a. **Typo: "but it's useful to add data for Theme URI, Author, and _Author UR._" Author UR needs an I to become "Author URI"**

2. Is the content technically correct?
**Finally, a block theme _needs a theme.json file_. This file handles the global settings and styles for a block theme. _This file is not required for a block theme_ to be active on a WordPress site, but for development purposes, it's extremely useful to create it early on.** This statement is slightly contradictory; consider rewriting.

Option for change: New users might benefit from a tiny bit more explanation about author / theme URI's -- this is not covered in my course, but it could be! If your intended audience already has a strong grasp of this, let me know in a comment in [this link to notes I took on style.css](https://docs.google.com/document/d/18_W7OtGt7O9U2RmReyJ7Z9ZeuqpFznwFw5HPByCooYA/edit?

**Comment by jonathanbossenger** [comment]
@wparasae thank you for your feedback. I've updated the content based on your suggestions.

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/block-theme-requirements-a-review/
