### ISSUE TITLE
Adding a Contact Form to Your Site - Tutorial

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#920]

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/189014261-8d731fd1-7918-4f15-a36b-43fa1cb90656.mp4

**Comment by westnz** [comment]
**Review: Hugh Lashbrooke**

"I like that you used a different plugin for each type of form - that's a great way of showing how to use different options! I think it might be good to add a line at the end that says something like “there are lots of other form plugins available in the plugin directory, so you can choose the one that’s right for you."

**Comment by wparasae** [comment]
Review:
I love how clearly you laid out the objectives -- the questions at the beginning do a great job to center the learner and activate background knowledge.

You do a good job with cursor effects. It's very clear where I should look, and that is something I want to emulate in my own workshops.

I really like the way you anticipate concerns a learner might have when navigating from the editor to a preview. That's a good technique!

**Quick Fixes:** 
1. Typo alert-- you'll want to change "subscribtion" to "subscription" on the slide used at :40-:51

Thought:
I both _love_ and worry that you're using real examples from the plugin directory! I love it because it shows such variety in different ways people can achieve one setting; I worry that in the future, when the plugins themselves are updated, some of the options may change, which might make updating this video and ones like it harder in the future. Still, that's not a reason not to publish this, as it's great information!

**Potential Addition:** 
2. Consider adding a disclaimer at the beginning or end of the video stating when this video was recorded and that the examples shown may change over time, but that's normal as WordPress is constantly evolving. :) Just a thought!

**Comment by westnz** [comment]
Thank you @wparasae! 😃

**Comment by jonathanbossenger** [comment]
Nice tutorial @westnz 

I appreciate the way you described how you created the various pages before you start

One comment I might add is to explain that how the forms plugin UI appears/works is dependent on the plugin developer, so not all processes are the same across all plugins. You could do this when you show the initial forms search result or add it on right at the end.

Other than that, and the other review comments here it looks good to go.

**Comment by westnz** [comment]
Thank you @jonathanbossenger! 😺

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/adding-a-contact-form-to-your-site/
