### ISSUE TITLE
Tutorial - Introduction to securely developing plugins

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#949]
# Topic Description
With WordPress now powering over 40% of the web, website owners need to think more about online security. Almost every week a new plugin vulnerability is found and patched, leading to concerns about the security of WordPress.

Fortunately for the new plugin developer, the WordPress developer handbook has an extensive section on Plugin Security. If followed, plugin vulnerabilities can be drastically reduced, and the entire ecosystem is protected.

This tutorial will walk through the 5 areas of plugin security, using easy-to-understand examples.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ] https://developer.wordpress.org/plugins/security/
- [ ] https://github.com/jonathanbossenger/wcjhb-2019-plugin-workshop

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [ ] Vetted by instructional designers for content idea
- [ ] Provide feedback of the idea
- [ ] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Create an outline of the workshop
- [ ] Tutorial submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [ ] Tutorial submitted to WPTV https://wordpress.tv/submit-video/
- [ ] Tutorial published on WPTV
- [ ] Tutorial is captioned https://make.wordpress.org/training/handbook/tutorials/tutorial-subtitles-and-transcripts/
- [ ] Tutorial created on Learn.WordPress.org
- [ ] Tutorial post is reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial announced to training team
- [ ] Tutorial announced to creator
- [ ] Tutorial announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by jonathanbossenger** [comment]
Docs

- https://developer.wordpress.org/plugins/security/
- https://developer.wordpress.org/apis/security/

**Comment by jonathanbossenger** [comment]
Example plugin download 

https://github.com/jonathanbossenger/wp-learn-plugin-security/releases/download/1.0.0/wp-learn-plugin-security.1.0.0.zip

**Comment by jonathanbossenger** [comment]
Tutorial script https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/wordpress-plugin-security.md

**Comment by jonathanbossenger** [comment]
https://user-images.githubusercontent.com/180629/213196807-ef6d1e1e-7c6d-4342-b548-809daa8bb77c.mp4

**Comment by jonathanbossenger** [comment]
Ready for review:

Note to reviewers, this is a big topic, that's hard to fit into a video of fewer than 10 minutes. As such, I've tried to use single, simple examples covering each type of security principle, referring back to the developer documentation each time.

**Comment by nomad-skateboarding-dev** [comment]
I took from the title that it was plugin security for users of plugins, so viewed to review. Obviously not what this is :slightly_smiling_face:. 

As someone ignorant on most of the plugin code, I feel I have a much better grasp of at least what to be aware of and best practices. I read and heard no mistakes or anything that stood out to me as off. It all made sense, it was all clear, and the info you did provide, as I said, at least it gave me a handle on what was going on. I imagine for an actual plugin developer this is fantastic. :raised_hands:

**Comment by westnz** [comment]
You have a fantastic job at condensing such a big topic.  You have effectively made use of slides, annotations and the recording is crystal clear. I love the live coding examples! You explain things very clearly.

**Comment by kathrynwp** [comment]
This was excellent. I found it easy to follow, and the perfect pace... not too slow and not too fast. Nicely done!

**Comment by erwanlr** [comment]
Thank you for putting the time to make this!

I've put some feedback below, based on vulnerabilities and insecure code we see and check at WPScan on a daily basis.

The rule of thumb is that code should be written in a way to be as much as future proof as possible. Some of the below might be cherry picking for some people reading, however we see such mistakes on daily basis when checking plugin/theme code and fixes from vendors related to security issues. Furthermore, while the code provided by this tutorial are examples, some people might (and will, actually) copy it and paste it in their plugin, assuming it's secure by default and fine to use as it (which for some, is really not!), just like they copy and paste insecure code from Stackoverflow :x.

### Sanitizing inputs

The example taken is quite tricky, because even though it appears vulnerable, it's actually not exploitable, because WP core [adds magic quotes](https://github.com/WordPress/wordpress-develop/blob/6.1.1/src/wp-includes/load.php#L1101-L1110) to any GET & POST inputs. /end backstory

That does not mean it should be left like this though, because if the code is updated to something like `$name = wp_unslash($_POST['name']);` or `$name = base64_decode($_POST['name']);` in the future, then it becomes vulnerable. And even with the sanitization suggested, ie `$name = sanitize_text_field(wp_unslash($_POST['name']));`, it would still be vulnerable (and we see such code a LOT).

That is because even though the input is sanitized, it's not escaped when output in the SQL query, which can lead to security issues in some case. And the example given is really not recommended as a code (as it is not secure by default, a single change like mentioned above with `wp_unslash()` would lead to an SQLi), it would be bette to either use:

- A prepared statement:
```
$result = $wpdb->query($wpdb->prepare("INSERT INTO $table_name (name, email) VALUES (%s, %s)", $name, $email));
```
- WP API:
```
$wpdb->insert(
	$wpdb->prefix . 'form_submissions',
	array(
		'name' => $name,
		'email' => $email,
	),
	array(
		'%s',
		'%s',
	)
);
```

Speaking of code not secure by default, when seeing `wp_redirect( WPLEARN_SUCCESS_PAGE_SLUG );`, it tickled me a bit, `wp_safe_redirect()` should be used here. Even though it's not an issue right now, it could become one, and given that the redirect is intended to be on the same blog, `wp_safe_redirect()` is more appropriate.

### Validating Data

Stacked Query attacks (ie use a payload such as `1; DROP TABLE form_submissions;`) are DBMS dependant and such attack won't work on every DBMS. Although I understand the need to use such payload  to demonstrate the issue, saying that the table will be dropped with such payload is incorrect (that won't do anything on MySQL for instance). So maybe changing that to `1 OR 1=1` would be better here.

Although casting to an integer is good, once again, to be future proof, there are better ways:

- Prepared statement
```
$result = $wpdb->get_results($wpdb->prepare("DELETE FROM $table_name WHERE id = %d", $id));
```
- WP API
```
$wpdb->delete( $wpdb->prefix . 'form_submissions', array( 'id' => $id ) );
```

### Escaping outputs

> For the name and email fields, we can use the built-in WordPress escaping function esc_html().

Why `esc_html()` ? It's obvious for you and me, but for most people writing their first plugin, it won't be ;)

I would also add an example where `esc_attr()` has to be used (the amount of time we see code using `sanitize_text_field()` and then output that in an attribute is insane)

> Notice that this code follows a key principle of escaping data, in that you escape the data as late as possible.

Thank you for that one!, This is an **extremely** important one, both for writing secure code, and ease of checking that the code is secure.

### Preventing unauthenticated users

The `wp_learn_delete_form_submission()` should also have a CSRF/Nonce check ;)

Feel free to ask If you have any questions (either here or Slack via our channels/DM)

**Comment by jonathanbossenger** [comment]
@erwanlr thank you for your detailed feedback, all of which I do agree with.

One of the things we struggle with when it comes to creating tutorials for Learn WordPress is that we're limited in how much we can show in one tutorial, vs how much we should show. Generally, folks have a short attention span, so we often have to limit the number of examples we showcase in one video.

I also tend to take into account the "user journey" for the new WordPress developer who is reading, for example, the plugin developer handbook. As you can see from the list of items in that handbook on [Plugin Security](https://developer.wordpress.org/plugins/security/), the five items listed there are the five items I've covered in this tutorial.

However, I am planning at least one more tutorial on plugin security, specifically covering the [Common Vulnerabilities](https://developer.wordpress.org/apis/security/common-vulnerabilities/) section that was recently added to the Common APIs documentation on Security. The goal of that video would be to take the lessons learned from this tutorial and include the additional examples you've described here.

However, I'm cognizant of this concern:

```
Furthermore, while the code provided by this tutorial are examples, some people might (and will, actually) copy it and paste it in their plugin, assuming it's secure by default and fine to use as it (which for some, is really not!)
```

To combat this, may I suggest adding an additional introductory slide to the video that contains the following disclaimer

```
This tutorial was created as a beginner's guide to security when developing plugins. The code used here is merely showing you what to consider, using simplified examples. You should not any of the code verbatim from this tutorial in your plugins. Make sure to read the full documentation on [Security](https://developer.wordpress.org/apis/security/) in the handbook and ensure you understand the correct methods to follow.
```

In reading your notes, I also think a 3rd tutorial would be a good idea, where I review the original plugin code again, and then highlight and fix ALL the vulnerabilities mentioned (and including an example of using esc_attr correctly instead of using sanitize_text_field) as a final "wrap up" on the subject.

This could also make a good mini-course on plugin security, that we could add to Learn WordPress.

Let me know your thoughts on my suggestions here.

**Comment by jonathanbossenger** [comment]
Final thought, I also think I'm going to rename this tutorial to "A beginners guide to plugin security".

**Comment by jonathanbossenger** [comment]
Thanks, @nomad-skateboarding-dev for mentioning this:

`I took from the title that it was plugin security for users of plugins, so viewed to review.`

From that and other feedback, I've amended the title to make it clearer what the video is about.

**Comment by jonathanbossenger** [comment]
Tutorial published, I'll work on the follow-up tutorials and aim to get them published before the end of march.

https://learn.wordpress.org/tutorial/introduction-to-securely-developing-plugins/
